### ISSUE TITLE
Unblock Python 3.9 upgrade by handling transformers dependency

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#10119]
@koernerfelicia shared more context [here](https://rasa-hq.slack.com/archives/C01HHMR4X8S/p1636393237457000?thread_ts=1636122663.368700&cid=C01HHMR4X8S)

**Definition of done**
- [x] Upgrade `transformers` dependency
- [x] Upgrade `keras` dependency
- [x] Verify that there is no impact on performance

**Comment by alwx** [comment]
Just a small update on Python 3.9 + a summary (played with it a bit this morning):
1) One of the proposed solutions (№2) was to update `transformers` to `^4.12.0` which is likely needed either now or later anyway but leads to a lot of issues with `lm_featurizer.py` (and failing tests in `tests/nlu/featurizers/test_lm_featurizer.py`)
2) All those tests fail because of an incorrect usage of `tensor.shape` in `lib/python3.9/site-packages/keras/engine/base_layer.py`
3) The obvious solution in this case is to get rid of this limitation in our `pyproject.toml`: `keras = "<2.7.0"` => upgrade `keras`
4) Updaing keras leads to `tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists`. (which is described here: https://github.com/tensorflow/tensorflow/issues/52951)
5) The only existing solution is to update to either TF 2.6.2 or TF 2.7.0 which we probably cannot do right now :disappointed:
