### ISSUE TITLE
auto-fill warning

### ISSUE THREAD

**Issue by ka-bu** [RasaHQ/rasa#10126]
### Rasa Open Source version

3.0.0.rc

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

Run rasa init, add some slot and entities and extract slot from_entities. Rasa warns that ` UserWarning: Slot auto-fill has been removed in 3.0 and replaced with a new explicit mechanism to set slots. Please refer to https://rasa.com/docs/rasa/domain#slots to learn more.` although no auto-fill has been added.

**Comment by ancalita** [comment]
@ka-bu Yes, this warning will get raised regardless of whether auto-fill is used as a key in the domain and it's because auto-fill was by default enabled if not specified in the domain. 
This was a decision we took with DevRel, see thread [here](https://rasa-hq.slack.com/archives/C01HHMR4X8S/p1632152441013200).

**Comment by ka-bu** [comment]
ah ok, so a warning is supposed to be raised even if auto-fill is not used -> then we'll close this one :)
