### ISSUE TITLE
Markers: the first session in trackers sometimes contains only one event `action: action_session_start` which produces noisy marker statistics.

### ISSUE THREAD

**Issue by aeshky** [RasaHQ/rasa#10192]
**Problem:**
After fixing the `MarkerTrackerLoader` to load full trackers including all sessions, I noticed that the first session usually only contains a single event `action: action_session_start`, followed by `session_started: null` which we use to create new sessions. 

This produces noisy statistics. For example, I created three dialogues using `rasa shell`. The statistics show 6 sessions (which also messes up the percentages), and the per session statistics contain events for these noisy sessions with lots of nans. 

**Example:**
[trackerstore.csv](https://github.com/RasaHQ/rasa/files/7528467/trackerstore.csv)
[stats-per-session.csv](https://github.com/RasaHQ/rasa/files/7528451/stats-per-session.csv)
[stats-overall.csv](https://github.com/RasaHQ/rasa/files/7528453/stats-overall.csv)
[extracted.csv](https://github.com/RasaHQ/rasa/files/7528454/extracted.csv)

**Solution:**
When splitting sessions, consider both `action: action_session_start` and `session_started: null` as part of the same session. 
Otherwise, discard sessions containing only a single event equal to `action: action_session_start`.

**Comment by aeshky** [comment]
**Example:**
[trackerstore.csv](https://github.com/RasaHQ/rasa/files/7528467/trackerstore.csv)
[stats-per-session.csv](https://github.com/RasaHQ/rasa/files/7528451/stats-per-session.csv)
[stats-overall.csv](https://github.com/RasaHQ/rasa/files/7528453/stats-overall.csv)
[extracted.csv](https://github.com/RasaHQ/rasa/files/7528454/extracted.csv)

**Comment by aeshky** [comment]
@usc-m @ka-bu 

I can look into the this and submit a PR/fix. I can also address other small Marker issues at the same time (renaming a column and chaning CLI). WDYT?

**Comment by ka-bu** [comment]
Just to avoid confusion: The “nan”s in the per session results are not noisy per se. If there are no events, then “nan” is only reasonable default (same as used in cases where events exist but no relevant event for the respective marker exist). -- The requirement that had been extracted from the initial implementation was to output "summary statistics" for every session, even if no relevant event was extracted (this case will still exist and will still produce some "nans"). 

The statistic that suffering from the noise caused by empty sessions is the percentage of sessions where a marker applies at least once, since the empty sessions count towards the total number of sessions.
