### ISSUE TITLE
Make `LanguageModelFeaturizer` tests more robust

### ISSUE THREAD

**Issue by mleimeister** [RasaHQ/rasa#10472]
### Rasa Open Source version

3.0.1

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

The Huggingface models that are used in the unit tests are installed in the "Install requirements" step of the CI calling `make prepare-transformers`. This uses the list of models given in [data/test/hf_transformers_models.txt](https://github.com/RasaHQ/rasa/blob/main/data/test/hf_transformers_models.txt). However, one of the models used in the `LanguageModelFeaturizer` tests is `bert-base-uncased`, which is not installed and therefore leads to a flaky tests that's randomly failing due to a connection timeout: [https://github.com/RasaHQ/rasa/runs/4428695015?check_suite_focus=true#step:16:515](https://github.com/RasaHQ/rasa/runs/4428695015?check_suite_focus=true#step:16:515)

The following could be done to improve the test:

*   [ ] Add `bert-base-uncased` model to the list of cached models that gets installed in the prepare step
*   [ ] Check in the unit tests that the HF model that's used is indeed in the list of cached models, otherwise the test should fail
*   [ ] Investigate which other parts of model installation/caching could be improved

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by koernerfelicia** [comment]
> Investigate which other parts of model installation/caching could be improved

Some quick thoughts on this:
- the cache file names are hard-coded based off of where transformers looks for the cached models. This isn't robust, for example, to updates, and will become a problem whenever we upgrade and the default location changes
- the current solution also isn't robust to additions to the `LMFeaturizer` test suite: if a test is added (as was the case here) that requires a model not in that list it will result in flakey tests as the model now needs to be downloaded during the test itself

An ideal solution (IMO), would:
- safeguard against additions like these where a model is used that wasn't cached during this step (maybe a failing CI check? Some sort of registry that is checked before running a test?)
- automatically determine cache location and cache file naming, rather than hard-coding these. This may be dicey because we might have to call transformers code, not sure how much python code we want to run in make, and it would mean we need to install transformers before this step.

Alternatively, maybe we shouldn't be looking at doing this in Make at all, but rather as a pytest setup type fixture? In that case we may also be able to make some gains s.t. the models are only downloaded before tests that actually need them (atm we download *all* of them before any set of tests).
