### ISSUE TITLE
Remove `UserWarning` that gets raised when running `rasa x` with rasa 3.0 once rasa-x adds support for 3.0

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#10480]
This is a wrap-up issue once rasa-x support for rasa 3.0 has been added.

**Definition of Done**:

*   [ ] `UserWarning` raised in `rasa/cli/x.py::rasa_x` is removed, as well as the accompanying unit test `test_rasa_x_raises_warning_above_version_3`

**Comment by emysdias** [comment]
Hello, Has this issue been resolved?

**Comment by melindaloubser1** [comment]
This issue isn't relevant in its original form anymore, since Rasa 3.0 dropped support for Rasa X localmode.

However, there is an exception that now needs to be handled: The command `rasa x --production`, which starts a Rasa Open Source Server (not Rasa X) should not throw this warning, since that form of the command is not deprecated.
