### ISSUE TITLE
EntityMasker component

### ISSUE THREAD

**Issue by Maxinho96** [RasaHQ/rasa#10556]
### What problem are you trying to solve?

Currently, the intent classifier doesn't leverage the information extracted by the entity extractors. In general, entity values add noise to the training data of the intent classifier, because they vary a lot. It would be nice if entity values could be normalized to placeholders instead (that is, entity values are "masked" to the intent classifier, so it doesn't see them but sees placeholders insted).

### What's your suggested solution?

Add a `EntityMasker` component that preprocesses the intent classifier input by substituting entity values with placeholders during training and inference.

### Examples (if relevant)

Imagine an intent classifier that must detect the intent `buy` with the following examples:

*   buy an apple
*   buy a chair
*   buy me a ticket

It would be a lot easier for the intent classifier to detect the intent if the entities are masked with placeholders, like this:

*   buy an `item`
*   buy a `item`
*   buy me a `item`

This way, it will be a lot easier for the intent classifier to learn the intent `buy`, because the noise added by the entity values is removed. The only information that remains is the fact that there is an entity of type `item`, but the actual values are masked.

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

Add the EntityMasker component.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @dakshvar22 will get back to you about it soon! ✨

**Comment by koaning** [comment]
@joejuzl figured I'd ping you on this one, there may be a nice use-case for the graphical backend here. This component would need to sit between an entity extractor and DIET. 

@Maxinho96 while your use-case here is valid, one thing to keep in mind: since DIET is able to detect both intents and entities they can also influence each other. This is actually by design! :smile: Sometimes we'd want the entities to influence the intent prediction!The presence of an item might exclude some intents and that has predictive power.

**Comment by Maxinho96** [comment]
> @Maxinho96 while your use-case here is valid, one thing to keep in mind: since DIET is able to detect both intents and entities they can also influence each other. This is actually by design! 😄 Sometimes we'd want the entities to influence the intent prediction! The presence of an item might exclude some intents and that has predictive power.

Hi @koaning thank you for your response.
I get your point, but what you say is true only for entities that are trained through DIET. Actually, in my use case I use a mix of lookup tables, regexes and a custom component that extracts entities dynamically (see #10554). So in this setting the entity extraction of DIET is completely disabled and there is no way for the intent classifier to have information about the entities extracted by the other components. I proposed this solution because it is easy to implement (I have actually implemented it in my custom component and saw that the intent classification became way better), but this could also be addressed by modifying DIET so that it takes as input features also the entities that have been previously detected by other components.

**Comment by raoulvm** [comment]
I found that DIET is behaving differently if you train it with

\- buy an \[apple](object)
\- buy a \[chair](object)
\- buy me a \[ticket](object)

with `object` being a dummy entity (doesn't have to exist actually if you set DIET not to extract entities),   
instead of
\- buy an apple
\- buy a chair
\- buy me a ticket

DIETs intent predictions seem to give more weight to literals outside entities, so the intent prediction for  
`buy a beer` has a higher confidence for `buy` intent if trained with entity annotations.

Maybe @koaning can point us to an explanation for that.

**Comment by koaning** [comment]
@raoulvm have you seen my algorithm whiteboard videos in DIET? In particular, [this part](https://youtu.be/KUGGuJ0aTL8?t=366) on the internals of the transformer block may be of interest. 

The transformer allows the entity predictions to influence the internal representation of the intent prediction. The reasoning is that the presence of an entity could indicate the presence of an intent and vice versa. If you feel like this is unwanted behavior, then you can choose to run DIET without entity detection, but it's hard to know upfront if this will be better for your assistant. This needs to be verified empirically.
