### ISSUE TITLE
Declarative Project Structures: project.yml validation

### ISSUE THREAD

**Issue by tayfun** [RasaHQ/rasa#10867]
A new project structure declaration file called `project.yml` which has been added to [scaffolding](https://github.com/RasaHQ/rasa/issues/10810) needs to be validated in case users change it.

### Definition of done

- [x] Add `project.yml` schema to `rasa/shared/utils/schemas/`
- [ ] Variable for schema should go to `rasa/shared/constants.py`
- [x] Validate `project.yml` conforms to schema in `ProjectConfig` (see `validate_yaml_schema` function and `read_model_configuration` which reads `config.yml`)
    - File should be validated on every `rasa train` run and other CLI commands
    - If there is no `project.yml`, validation does not fail, it continues working on legacy projects as before, by filling in data from current defaults
- [x] Add tests to confirm schema works as expected

**Comment by ancalita** [comment]
@joejuzl I'm actually actively considering using `jsonschema` instead of `pykwalify` for validation as we do for events [here](https://github.com/RasaHQ/rasa/blob/main/rasa/shared/utils/schemas/events.py). This would also be used in the custom validation function called by `ProjectConfig`. Would that be ok with you?

**Comment by joejuzl** [comment]
> @joejuzl I'm actually actively considering using jsonschema instead of pykwalify for validation as we do for events [here](https://github.com/RasaHQ/rasa/blob/main/rasa/shared/utils/schemas/events.py). This would also be used in the custom validation function called by ProjectConfig. Would that be ok with you?

@ancalita What's the thinking behind this? (I think it might make sense, just interested to hear your thoughts too)

**Comment by ancalita** [comment]
@joejuzl I think `json-schema` is a better option because it is more readable overall through the provision of keywords like `required` and `additionalProperties` which can be used at the root level of the dictionary representation of `project.yml`.
While with yaml schema, we'd have to write `required: True/False` for every key-value pair in `project.yml`.

It's also easier to compose by allowing subschemas using [dedicated keywords](https://json-schema.org/understanding-json-schema/reference/combining.html) if in the future we want to make this file more complex.

**Comment by joejuzl** [comment]
Sounds good to me 👍 
I think that we should probably eventually move all our schemas to json-schema (especially if we still end creating the training data schema package)
I initially suggested pykwalify for `project.yml` schema just because that's what we currently use for the domain. However given we already also have json-schema in our code base, I think it's fine to use it here too, even if eventually we do a more rigorous look into how we want our schemas in general to work.
