### ISSUE TITLE
No module named 'scipy.sparse._coo'

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#10908]
### Rasa Open Source version

3.0.8

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

Recently built models (past week or so) will not load if they use DIET. Here's the error from `3.0.8` but I have confirmed this issue affects `2.8.x` so I think this is somehow related to pip build environment changes.

2022-02-16 06:35:45 ERROR rasa.core.agent - Could not load model due to Error initializing graph component for node 'run_DIETClassifier5', No module named 'scipy.sparse._coo'

This may be related to #5303 and #10883.

### Command / Request

<pre>Running rasa-production using standard Helm deployment</pre>

### Relevant log output

 _No response_

**Comment by rgstephens** [comment]
The problem is related to the [release](https://pypi.org/project/scipy/#history) of scipy `1.8.0` on February 5.  I worked around the problem by going back to `1.7.3`.  I think any models trained in an environment with Scipy 1.8.0 will fail when deployed to a production environment.

**Comment by koaning** [comment]
That's strange. Got a full traceback? I'm curious what part of what library is referring to a hidden module. The modules like `_coo` that start with an `_` are typically not meant to be used publicly.

**Comment by azizullah2017** [comment]
@koaning  rasa==2.8.8
```
         | /opt/venv/lib/python3.8/site-packages/rasa/shared/utils/io.py:97: UserWarning: The model at 'models' could not be loaded. Error: <class 'ModuleNotFoundError'>: No module named 'scipy.sparse._coo'

```

**Comment by rmiaouh** [comment]
+1

**Comment by botsahab** [comment]
did you solve it?

**Comment by rgstephens** [comment]
Yes, see [above](https://github.com/RasaHQ/rasa/issues/10908#issuecomment-1042543450)

**Comment by botsahab** [comment]
@rgstephens  should install with pip install scipy ==1.7.3?  sorry I am beginner in rasa

**Comment by rgstephens** [comment]
yes

**Comment by KHTee** [comment]
I am having the same issue with `rasa 2.8.16`.

The model must be trained with in environment with `scipy==1.7.3`. However, it has no problem with `rasa run` or `rasa test` in environment with `scipy==1.8.0`.

**Comment by Peppershade** [comment]
When I copy my model over from my PC (Python 3.8 venv) to my Docker Rasa container it gives me this error. Anyone know how to fix on Docker?

**Comment by melindaloubser1** [comment]
I can reproduce this problem only in the situation where I train in a `scipy==1.8.0` env and run on a `scipy==1.7.3` env. Both training and running on `scipy==1.8.0` is not a problem. If anyone has experienced this issue in a purely 1.8.0 env, please post the details of what you did and saw, otherwise I would fix this issue by pinning `scipy >=1.8.0`, since 1.8.0 renamed namespaces (like `coo -> _coo`) to be clearer about the public/private divide.

**Comment by sajastu** [comment]
Hi all,

Same problem here. I'm wondering if there is any other solution rather than just downgrading SciPy? I have two sets of files which are created in two environments: (1) with Python 3.6 and SciPy 1.5.4 and the (2) with Python 3.8 and SciPy 1.8.0, where I'm generating some numpy matrices and saving them through pickling module. Unfortunately, files generated with (2) are not readable by (1). I want to see if there is a way to convert files that are generated with (2) to the format which can be read by (1)? 

Thanks,

**Comment by lucasalvarezlacasa** [comment]
> Exalate commented:
> 
> rgstephens commented:
> 
> The problem is related to the [release](https://pypi.org/project/scipy/#history) of scipy `1.8.0` on February 5. I worked around the problem by going back to `1.7.3`. I think any models trained in an environment with Scipy 1.8.0 will fail when deployed to a production environment. It affects both 2.x & 3.x

Can you tell me how to do this with Rasa X? I cannot find how to activate the environment created by it in order to downgrade.

Thanks.

**Comment by melindaloubser1** [comment]
You can downgrade scipy in the training env and upload the new model.

**Comment by lucasalvarezlacasa** [comment]
> You can downgrade scipy in the training env and upload the new model.

Hi @melindaloubser1. I've already tried doing this but it doesn't work. I still get the same error. From other posts I understood that I need to downgrade in the productive instance as well, but  I don't know how to do that.

Do you happen to know?

**Comment by melindaloubser1** [comment]
Glad it's working now - if you have more questions on your specific scenario, please post them in the [forum](https://forum.rasa.com/) since it's no longer about the original issue.
