### ISSUE TITLE
Invalid rasa/examples/rules/data/nlu.yml file

### ISSUE THREAD

**Issue by w-jaworski** [RasaHQ/rasa#11112]
### Rasa Open Source version

3.1

### Python version

3.6

### What operating system are you using?

Linux

### What happened?

Hi,

I am exploring examples provided with rasa, and I recognized that file
rasa/examples/rules/data/nlu.yml is identical with rasa/examples/formbod/data/nlu.yml.
Moreover file rasa/examples/rules/data/nlu.yml is incompatible with the rest of rules domain.

### Command / Request

```shell
I think that content of rasa/examples/formbod/data/nlu.yml file should be replaced with intents adequate to rules domain.
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @camattin will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
@w-jaworski The file is not invalid (format wise); as you say, not all of the contents of that NLU file are used by the rules in the same directory, nor are all included in the domain file, but this will not cause a run time error.

Re. the duplication: The examples are intended to each stand by themselves, so there is a lot of data that is similar across different examples. This is also not a problem and won't cause errors. 

I am changing the type of this issue since it is not a bug, but it is a legitimate observation.
If you would like to update the contents of the file in question to be a more sensible example, please go for it.

**Comment by w-jaworski** [comment]
I disagree with @melindaloubser1. The following intents listed in rasa/examples/rules/domain.yml are not present in rasa/examples/rules/data/nlu.yml:
- activate_q_form
- explain
- stopp
- ask_possibilities
- faq
- switch_faq
- nlu_fallback

As a consequence it is impossible to activate rules that use these intents. Therefore I claim that this issue is a bug.

**Comment by melindaloubser1** [comment]
Although it is not a normal use case, it is in fact possible to include intents in NLU that are not in the domain, and vice versa. It will not break anything. I'm not too hung up on how it gets labeled, but it is helpful to keep the `bug` label for issues in source code that cause behaviour that is not by design. Since this is an example, and there's nothing that declares it should behave differently than it does, it doesn't fall in that category. 
You are welcome to submit a PR change the example to something you find more intuitive.
