### ISSUE TITLE
RasaFileImport load domain time very long

### ISSUE THREAD

**Issue by yuxuan2015** [RasaHQ/rasa#11290]
### Rasa Open Source version

rasa 2.3.1

### Rasa SDK version

rasa-sdk 2.3.1

### Python version

3.6

### What operating system are you using?

Linux

### What happened?

When I train the model, if the domain file is relatively large, such as 6M, it will take at least an hour for RasaFileImport to import the domain, but if I read and load the domain file alone, it only takes 1 minute. I don't know why this happens.
![飞书20220701-143406](https://user-images.githubusercontent.com/15645056/176838729-0bb0b540-24f6-4559-815e-bd39a13fe7b1.png)
![飞书20220701-143443](https://user-images.githubusercontent.com/15645056/176838746-a4b57746-9d03-49e8-9f3f-e39bae93e6c9.png)

### Command / Request

```shell
rasa train core --force -s data --out models
```

### Relevant log output

```shell
start to load domain
domain_path is domain.yml
-----------test4-----------
get domain successed
The time of get domain is 16125.721216s
```

**Comment by twerkmeister** [comment]
Hi @yuxuan2015,

this is most likely due to the different yaml parser being used by rasa, which does a lot of extra checks to keep ordering and  comments in files. However, last year we made many speed improvements to the yaml parsing. You might wanna look at upgrading to rasa 2.8. This should get you many of these improvements.
