### ISSUE TITLE
Seems that FailSafeTracker block ability to call retrieve_full_tracker

### ISSUE THREAD

**Issue by fliak** [RasaHQ/rasa#11389]
### Rasa Open Source version

3.2.1

### Rasa SDK version

3.2.0

### Python version

3.9

### What operating system are you using?

Linux

### What happened?

FailSafeTrackerStore used by default in rasa agent and not implement retrieve_full_tracker method, so method from base class TrackerStore used which hides it by call self.retrieve(conversation_id).
So there are no way to fetch full communication history, last session only.

Should I provide pr with  FailSafeTrackerStore.retrieve_full_tracker method implementation?

**Comment by fliak** [comment]
this works with using protected property: 
`tracker = await rasa_agent.tracker_store._tracker_store.retrieve_full_tracker(conversation_id)`

**Comment by melindaloubser1** [comment]
Hi @fliak, if you want to retrieve the full tracker then yes, you'd need to implement a `retrieve_full_tracker` method; it may be that this was not done because the `FailSafeTrackerStore` can call a backup tracker store; this should be taken into account when implementing the method.

If you'd like to contribute your implementation, that would be great; otherwise you would need to subclass tracker store to use locally .

**Comment by kozlice** [comment]
The problem here is that we can't override it in a nice way.

Agent wraps tracker with `FailSafeTrackerStore` during initialization: https://github.com/RasaHQ/rasa/blob/45fe00d3070d8ceb58a4c447f236ca87bed16c59/rasa/core/agent.py#L529

There is no way we could redefine `FailSafeTrackerStore.retrieve_full_tracker`, and it just uses parent implementation, which only does a proxy call to `retrieve`: https://github.com/RasaHQ/rasa/blob/45fe00d3070d8ceb58a4c447f236ca87bed16c59/rasa/core/tracker_store.py#L280

**Comment by fliak** [comment]
@melindaloubser1, what about this?
https://github.com/RasaHQ/rasa/pull/11393

**Comment by melindaloubser1** [comment]
@kozlice Question: How are you wanting to call `retrieve_full_tracker`? Is this about using the existing API endpoint for fetching trackers, or are you doing something custom in another way?
I'm trying to find out a bit more context around why that wrapping happens in the meantime

**Comment by kozlice** [comment]
@melindaloubser1 We have a custom app that initializes and loads multiple Rasa agents with different models. And it needs a custom endpoint to display full message history (not only the most recent conversation) in our CRM.

What we want to have in our code is:
```
tracker = await agent.tracker_store.retrieve_full_tracker(conversation_id)
```

What we have to do now is:
```
tracker = await agent.tracker_store._tracker_store.retrieve_full_tracker(conversation_id)
```
