### ISSUE TITLE
Add new rest api

### ISSUE THREAD

**Issue by nmtri1912** [RasaHQ/rasa#11472]
### What problem are you trying to solve?

I want to add more rest api for the Rasa server such as /info /heath, etc, ...
Does Rasa support this?

**Comment by rgstephens** [comment]
Endpoints for both of these features are already available.  [Health](https://github.com/RasaHQ/rasa/blob/4cdceaab5271a5b51463ec562c8eb55f96b771c5/rasa/core/channels/rest.py#L102) and [version info](https://github.com/RasaHQ/rasa/blob/4cdceaab5271a5b51463ec562c8eb55f96b771c5/rasa/server.py#L692).

Recommend that you post questions on the forum rather than GitHub.
