### ISSUE TITLE
Feature enhancement: Entity Errors during model evaluation

### ISSUE THREAD

**Issue by kapilkathuria** [RasaHQ/rasa#1472]
**Rasa NLU version**: 0.13.4

Just like ‘run_evaluation’ saves intent errors in errors.json, it seems there is no straightforward way to figure out what caused bad precision, recall & F1 Score. 

This is for enhancing Evaluation script to provide entity errors as well so that model can be quickly corrected.

**Comment by akelad** [comment]
I think this is a good idea, thanks for bringing this up. It might be a little trickier than for intents

**Comment by demongolem** [comment]
I would like to take a look at it this evening since it is a good-to-have for me.  I will let you all know what I find

**Comment by demongolem** [comment]
@akelad or anyone else.  Do you know why O gets substituted by no_entity in test.py?  As someone who does NLP and NER a lot, I understand O.  So what I am asking does anyone know if there is any internal or external dependency that makes no_entity necessary?

So I know I have the target entities available to me in test.py, however the merge_labels function strips the labels out of all the entities and this is where the important information is lost.  Definitely workable so far.

**Comment by akelad** [comment]
the `no_entity` thing is to make it clearer for people who don't know what O is. Because we print that out as the evaluation results

**Comment by demongolem** [comment]
@akelad Well I have a solution, the solution I am interested in, but it is a fabulously open question as to how to score it and what constitutes a miss.  So I need some feedback.  Example ...

I have an entity called HolidayName.  Now I am interested in does the entire entity mention get predicted correctly.  There are 13 such entity mentions in my test document 8 of them are found 5 are not found.  Recall is 8/13.  However, the summary results for crf shows a recall of .655 for a support of 29.  Do the math and you see that is 19/29.  So, there are 29 tokens making up the 13 entity mentions and 19 are correctly identified, but that is not at all what I am interested in.

So I need some feedback as how the entities should be scored and how they should be represented in the desired output.  I can't say one way or the other what the originator of the bug was thinking, but for me I need to know if I matched "Memorial Day" and not both "Memorial" and "Day".

**Comment by demongolem** [comment]
I have create a new pull request, #3128, with my proposed changes and we can discuss there.

**Comment by akelad** [comment]
awesome, thanks so much!

**Comment by erohmensing** [comment]
merged in https://github.com/RasaHQ/rasa/pull/4335
