### ISSUE TITLE
RAM Increases with Every Training for fixed model name. How to release memory?

### ISSUE THREAD

**Issue by Greg3108** [RasaHQ/rasa#1585]
**Rasa NLU version**: 0.14.0

**Operating system** (windows, osx, ...): Windows

**Content of model configuration file**:
```yml

```

**Issue**:
I am using currently using Rasa NLU with the 'spacy_sklearn' and 'duckling' pipeline. I have assigned a fixed model name. When I am training the same model it's increased memory every time ~2 GB. I am wondering how to release memory of old model after training completed. Is there any way to release memory?

Many thanks in advance.

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hey @Greg3108,

Can you post me the command you are using to train your model?

**Comment by Greg3108** [comment]
Hi @MetcalfeTom 

We have given the default Fixed Model Name in the argument. below is a link of which I am using 

URL: localhost:5000/train?project=my_project&model=my_model_name

Many thanks in advance for your time and support.

**Comment by MetcalfeTom** [comment]
No problem, I believe this has something to do with the way we cache `ner_duckling` and I'm looking into it now.

**Comment by Greg3108** [comment]
Just to update on the same, we tried with duckling_http but it didn't help much. I'll update accurate findings soon.

**Comment by MetcalfeTom** [comment]
Hello again,

This turns out to be related to Spacy, not duckling.  Unless you are changing the `max_training_processes` option for your server via the command line, then this extra memory usage is expected behaviour: when you _unload_ the model, you are unloading the `rasa_nlu` language model, however the spacy model is still in memory because it is a cached component of the language model pipeline.

[We came into this issue before](https://github.com/RasaHQ/rasa_nlu/issues/875) but decided to deprioritize it.  We could always use more contributions if you decide to implement a workaround.

**Comment by Greg3108** [comment]
Hi @MetcalfeTom , 
At present the we are keeping this max_training_processes to 1 (which is default) and facing this extra memory usage. Or to redefine the same, every time we load model, memory just keeps increasing (either we keep fixed model or we go with new model and unload earlier one).

Many thanks for making it clear that it doesn't help to release memory occupied by spacy model. And probably, that's creating this memory heap. Do you have any suggestions or know any way to unload spacy model? Or just some cents of advise for us to move ahead (even in terms of further research), it would be great aid.

Thanks again.

**Comment by devendrasoni18** [comment]
Hello @MetcalfeTom ,

I am facing the similar kind of issue. I have created a custom component for sentiment analysis and loaded a pre-trained model. Due to which each time when I train the model in docker, the memory increases.

As a workaround, I implemented cache_key() method to cache the custom component so that it would not load the pre-trained model again. This trick works when I run rasa_nlu project directly from my machine. But **caching doesn't works** while I run the same with my custom **Docker image**.
`customComponent

    @classmethod
    def cache_key(cls, model_metadata):
        # type: (Metadata) -> Optional[Text]
        return cls.name
    @classmethod
    def load(cls, model_dir=None, model_metadata=None, cached_component=None, **kwargs):
        if cached_component:
            return cached_component
        else:
            # Do something else
`
Is there any known issue with docker for caching?
Kindly help me with the same. 
Thanks in advance!!

**Comment by pavei** [comment]
Hi! I'm getting this same problem. 

When we do a train after complete the "multiprocessing" task keeps on memory and still growing. We are doing a lot of trainings a day, so almost every day we have to reboot our training machine twice.
