### ISSUE TITLE
multiple domains

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#1801]
Currently, you can only have one domain. We need to make that clear in the documentation. In the meantime, we should think about ways to support multiple domains.

**Comment by karthikbalu** [comment]
But lets say we are serving multiple domain for different use case and not related to each other, fallback policy wont be the solution i guess, any alternate solutions pls?

**Comment by akelad** [comment]
we're looking into multiple domains for the future, we have no update as of yet though

**Comment by Patrick-DS** [comment]
I just wanna add in my input too : currently I am building FAQ bots and to structure my data correctly I create one file per FAQ question that generates all the relevant data for that question : the stories, the training examples for NLU, and the stuff that needs to be added in the domain. I store all those things in temporary files (for testing purposes, since my code is a bit experimental haha) so I get one mini domain per question. Before training NLU and Core I use the merge function of the Domain class, and that works well enough for me. 

I think that since Rasa already enables multiple policies, if someone has a use-case where bot behavior changes drastically and permanently depending on a single input from the user, it's good to write a custom policy that decides which policies should be considered "active" and which ones shouldn't (for example, on a customer service use-case, if a user is either a private customer or a business customer, turn on/off the corresponding policies at the point where the bot gets that information if that changes the conversation drastically). The option of training multiple NLU interpreters to deal with different intents can also be figured out with a bit of engineering. 

I'm open for discussions :)

**Comment by bamba518** [comment]
@karthikbalu  would your solution require lots of resources as you need to spun up servers for each core, ideally if it could be like the nlu solution where one server is running and it uses the files based on the parameter passed

**Comment by karthikbalu** [comment]
So far I’m using it with multiple server ports, I know it’s not as scalable but there isn’t a better way that I’m aware of...

**Comment by solyarisoftware** [comment]
@karthikbalu  what do you mean with 

> based on the selected agent domain given as part of the input message,

? May you  give us an example?

**Comment by chikubee** [comment]
Hi, 
does RASA support
1. Identification of multiple intent in the same domain from the utterance (faq/rasax , faq/channels) -> utterance that talked of both.
2. Identification of multiple intent across diff domains from the utterance (greet + faq/channels)
