### ISSUE TITLE
Allow configuration of logging format

### ISSUE THREAD

**Issue by kumarkrish85** [RasaHQ/rasa#2546]
**Rasa Core version**: 0.11.3

**Python version**: 3.6.2

**Operating system** (windows, osx, ...): window

**Issue**:
This is for an analytics purpose. Current debug logs doesn't have the timestamp details like when the query is sent from the user. Please suggest

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by dmitryzykov** [comment]
Any updates on that? 
We need logs in json format

**Comment by thusithaC** [comment]
Changing some configs in rasa command line required required a lot of surgery. I had an issue where we wanted a custom logger, and there was no way to configure it using the default commandline. Ended up creating my own start scripts and stubbing methods in `rasa.server` and `rasa.utils.common`.

**Comment by AKASHY1102** [comment]
Hello i was wondering if there is any way to create the logs file after the size of previous log file crosses 10MB because its hard to investigate when all logs in the same file and one more thing the file keeps getting bigger on my server that even i cant open it anymore

 rasa run -p 7001 --enable-api --log-file out.log --debug &

i am using this command

any ideas how i can do it ?
