### ISSUE TITLE
tests should run locally

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#3151]
Currently, the tests do not run locally. Tests are failing due to different reasons. You need to push your changes and wait for travis to tell you, if you broke some tests or not.

Problems detected so far:
- If the MITIE model file is not located in `/data` you will get the following error message `Exception: Unable to load total_word_feature_extractor detector from data/total_word_feature_extractor.dat`. 
- `pytest-pep8` is not included in the `requirements_dev.txt`, but needed to execute `make test`.
- There exists no documentation on how to run only unit tests (without slow/integration tests).

Expected behaviour:
The tests should run locally. You should be able to tell, if tests are failing before you push.

Things to do (list might be incomplete):
- [ ] Update `requirements_dev.txt` to include `pytest-pep8` to be able to run `make test`
- [ ] Update documentation on how to run tests: How to run only unit tests? How to run all tests including slow/integration tests?

**Comment by federicotdn** [comment]
I've thought of some ways we could solve this problem:
- Add, to README.md, specific instructions of what needs to be installed in order to run all tests. This list would need to be kept up-to-date as the project's dependencies change.
- Add a new recipe to Makefile, e.g. `install_dev_dependencies` that installs all necessary dependencies. This would more or less run the same things that .travis.yml currently does on `install`, without including the OS-specific stuff (like `apt-get install...`). Then, add `make install_dev_dependencies` to .travis.yml and to the test instructions in README.md.

Additionally, we could:
- Move `coveralls==1.7.0` from .travis.yml to requirements-dev.txt.
- Fix the `test` recipe on Makefile so that it doesn't undo the effects of `pip install -e .` (required for tests to run).
- Make .travis.yml run `make test` instead of `py.test tests --cov rasa -v`. This way, all the required test steps will be at only one place (Makefile).
- .travis.yml installs MITIE from github.com/tmbo/MITIE. Maybe we could create a fork of MITIE from the RasaHQ account, so that the project itself and all of its internal dependencies are under the RasaHQ account.

The general idea would be to write all necessary setup and testing steps in Makefile and then reference them from README.md and .travis.yml.

**Comment by federicotdn** [comment]
Also: add `black==X.Y.Z` and `pytype==X.Y.Z` to requirements-dev.txt and remove `pip install black` and `pip install pytype` from .travis.yml.

**Comment by federicotdn** [comment]
Related: https://github.com/RasaHQ/rasa/issues/3860

**Comment by federicotdn** [comment]
Related: https://github.com/RasaHQ/rasa/pull/3994

**Comment by federicotdn** [comment]
Hey @tabergma, with https://github.com/RasaHQ/rasa/pull/3994 merged would you consider this issue done? Is there anything else important that we could be missing?

**Comment by tabergma** [comment]
Thanks for tackling this! 🚀 I consider this issue as close. If we discover something else, we can open a new issue. Great work!
