### ISSUE TITLE
consider replacing os.path uses with pathlib

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3153]
The standard python library `pathlib` makes interactions with paths much easier. We should consider replacing the old `os.path` with the pathlib `functions`.

**Comment by icaropires** [comment]
Hi, this issue is opened to community?

**Comment by wochinge** [comment]
Hi @icaropires,
Sure! Do you want to take it on? That would be amazing! I would just suggest that we do it in multiple smaller PRs instead of one big one.

**Comment by icaropires** [comment]
Great! I'll do it :smiley:

**Comment by wochinge** [comment]
Awesome! Thanks a lot! Just tag me when you have got one PR ready 🎉

**Comment by wochinge** [comment]
How is it going @icaropires ?

**Comment by icaropires** [comment]
@wochinge Sorry, I've been busy but I'll be working on this on the next week!

**Comment by wochinge** [comment]
@icaropires How is it going?

**Comment by icaropires** [comment]
Hi @wochinge , I'm very sorry for the delay, I ended up getting busier than I expected and that's why I couldn't finish this issue yet. And unfortunately, I will be very busy for at least another month.

As this issue requires a massive amount of changes, I will share how far I did (through a PR draft) and I hope it will be useful for someone.

I expect to be able to contribute again soon. Sorry again for the delay.

**Comment by wochinge** [comment]
Thanks @icaropires the draft is super helpful !

**Comment by RomuloSouza** [comment]
Hi, @silvasara and I would like to work on this issue. Is this still relevant?

**Comment by wochinge** [comment]
Hi @RomuloSouza , it's still relevant 👍

**Comment by jps12** [comment]
Hi,
Is there anyone working on this issue? 
I'd like to get this issue to work on.

**Comment by wochinge** [comment]
Feel free to take it @jps12 I'd suggest to split up in multiple pieces to make it easier to review e.g. doing < 200 lines of diff and then do a PR to the repository.
