### ISSUE TITLE
docs for form validation updates

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3215]
when [this PR](https://github.com/RasaHQ/rasa_core_sdk/pull/63) goes through, we have some docs to update:

To do in this repository: 
- [x] update formbot/restaurant bot? to discuss
- [x] update form documentation to add an example of a validate_{} function
- [x] make it clear in docs that the user is responsible for validating any other slots that are filled in a validate func

**Comment by Ghostvv** [comment]
please add to the docs, that validation by default only happens if the form is executed immediately after user input, it can be customized by overriding `_validate_if_required(...)` method: https://github.com/RasaHQ/rasa_core_sdk/blob/cd66dba3d0c1116388a66f31b22a60a31ef4d3a7/rasa_core_sdk/forms.py#L438
