### ISSUE TITLE
Fallback to InMemory tracker store if mongo / sql / redis is not reachable

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3243]
If you defined an external tracker store, and the tracker store is not reachable, Rasa should automatically fallback to use the InmemoryTrackerStore. Otherwise this leads to weird behavior.

**Comment by wochinge** [comment]
@akelad Should we just do this at the initial connection attempt or also when the tracker store crashes somewhere in between? As far as I remember this should also handle the second case.

**Comment by wochinge** [comment]
Never mind, nearly through with the production code impl

**Comment by Mhdi-kr** [comment]
This feature cause us so many problems, in environments where there are network issues to postgres database, rasa should fail to save new messages! because fallingback to inMemoryTrackerStore where it doesn't insert to sqlTrackerStore when it's up and running again means you're gonna lose messages

what can we do about this?
