### ISSUE TITLE
Getting a ModuleNotFoundError: No module named 'trainers' (although 'trainers' is present in SitePackages)

### ISSUE THREAD

**Issue by yendada** [RasaHQ/rasa#3293]
**Rasa version**:0.7.2

**Python version**: 3.6.8

**Operating system** (windows, osx, ...):Windows 10

**Issue**: Getting a ModuleNotFoundError:  for trainers but in my Site PAckages that folder is already present

Trying to train the ML model run. (following the https://github.com/bhavaniravi/rasa-site-bot)

python -m rasa_nlu.train -c AI-engine/config_spacy.json --data AI-engine/data/sitebot-data.json
 from trainers.spacy_sklearn_trainer import SpacySklearnTrainer
ModuleNotFoundError: No module named 'trainers'

trainers is present in Site packages. 
C:\Python3.6\Lib\site-packages\rasa_nlu\trainers

**Content of configuration file (config.yml)**:
```yml 

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @paulaWesselmann  will get back to you about it soon.

**Comment by paulaWesselmann** [comment]
Hey @yendada,
please ask this question in the [forum](https://forum.rasa.com/).
As this is a usage issue and rasa version 0.7.2 is very outdated and not supported anymore I'll close this issue here. 

You might be able to fix your issue by upgrading to a newer version of rasa_nlu.
For the newest version of rasa_nlu for example run `pip install rasa_nlu==0.14.6`.
Information on how to migrate to newer versions can be found [here](https://rasa.com/docs/nlu/0.14.6/migrations/)
