### ISSUE TITLE
rasa run core  can't load models

### ISSUE THREAD

**Issue by wpfnlp** [RasaHQ/rasa#3305]
(base) wpf:tutu_chatbot weipengfei$ python -m rasa run core -m models --endpoints endpoints.yml
2019-04-23 23:44:22 INFO     engineio.server  - Server initialized for sanic.
2019-04-23 23:44:22 INFO     root  - Starting Rasa Core server on http://localhost:5005
[2019-04-23 23:44:22 +0800] [43583] [INFO] Goin' Fast @ http://0.0.0.0:5005
2019-04-23 23:44:22 INFO     sanic.root  - Goin' Fast @ http://0.0.0.0:5005
**2019-04-23 23:44:22 WARNING  rasa.core.interpreter  - No NLU model found. Using RegexInterpreter instead.**
2019-04-23 23:44:23.002616: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-04-23 23:44:23.003033: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.
[2019-04-23 23:44:24 +0800] [43583] [INFO] Starting worker [43583]
2019-04-23 23:44:24 INFO     sanic.root  - Starting worker [43583]

**core-20190423-233713.tar.gz and  nlu-20190423-233521.tar.gz has been generated under the models folder.**

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by nietzschecong** [comment]
@wpfnlp it looks like a bug, do you has fixed it? or some other solution？

**Comment by erohmensing** [comment]
Hey there @nietzschecong, looks like you're trying to train a full model -- in the new CLI, full models are trained and run as one model instead of as separate core and nlu models. You want to train using `rasa train` instead of `rasa train core` and `rasa train nlu`. Then you want to run the model using `rasa run` instead of `rasa run core`.

**Comment by nabito** [comment]
@erohmensing do we have a proper documentation on how to use this new cmdline?

I find running rasa train for both NLU and Core at once to be unintuitive for me (do we need to mix policies.yml and nlu_config.yml into one file as supply via -c option?)

**Comment by erohmensing** [comment]
@nabito there will of course be full documentation when the new command line interface is released, but not at the moment. Yes, you'll want to copy one of your configs into the other and supply via `-c` (or just name it `config.yml`, as that's where it looks for the default one. 

We don't recommend using master because of instability, especially right now as it requires use of the new CLI, which has many bugs that we are currently working through. If you decide to use it, know that you might run into bugs which stop you from being able to do what you want, and we've already likely found these bugs and are working on them -- which means you should be constantly pulling master for changes if you are using it.

**Comment by imane6** [comment]
@erohmensing  hey! can you please help me with this  error:
![error](https://user-images.githubusercontent.com/50795847/62455967-b78d6900-b777-11e9-9af5-46b325ce0026.PNG)
this is my custom action:
from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

from rasa_sdk import Action
from rasa.core.actions.action import Action

from rasa_sdk.events import SlotSet
from rasa_sdk.events import AllSlotsReset

import pandas as pd
from fuzzywuzzy import fuzz 
from fuzzywuzzy import process

class GetAnswer(Action):
	def __init__(self):
		self.faq_data = pd.read_csv('./data/faq_data.csv')

	def name(self):
		return 'action_get_answer'
		
	def run(self, dispatcher, tracker, domain):
                print('ON ')
                query = tracker.latest_message.text# to get the user entered text
                questions = self.faq_data['question'].values.tolist()#converting the column 'question' to  list

                mathed_question, score = process.extractOne(query, questions, scorer=fuzz.token_set_ratio) #use process.extract(.. limits = 3) to get multiple close matches

                if score > 50: # arbitrarily chosen 50 to exclude matches not relevant to the query
                        matched_row = self.faq_data.loc[self.faq_data['question'] == mathed_question,]
                        match = matched_row['question'].values[0]
                        answer = matched_row['answers'].values[0]
                        response = "Here's something I found,  \n Question: {} \n Answer: {} \n".format(match, answer)
                else:
                        response = "Sorry I couldn't find anything relevant to your query!"
						
                dispatcher.utter_message(response)
                return[]
		
	
Thank you

**Comment by imane6** [comment]
when i run rasa shell --debug i get that:
![error2](https://user-images.githubusercontent.com/50795847/62457393-0a1c5480-b77b-11e9-8d94-950fab6bf9dc.PNG)

**Comment by erohmensing** [comment]
@imane6 this is irrelevant to this (already closed) issue, and is a usage question. Please make a post on the [forum](http://forum.rasa.com)
