### ISSUE TITLE
Converting from JSON to Markdown writes newlines

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#3338]
Having a `\n` in the text of an intent example works for JSON, but when we use `rasa.nlu.convert` to dump to Markdown, this prints newlines, which splits the example in two at train time

**Comment by therahulkumar** [comment]
@MetcalfeTom I am working on this issue, what do you think a good way to remove the above bug. 
if you have a \n in json file the escaping it with \\\n while converting to md file works as follows.

original training_data.json
`{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "intent": "affirm",
        "text": "ye\ns"
      }
]
  }
}
`


converted to md file



> ## intent:affirm
> - ye\ns

Now when you convert the above md file back to json file the json encoder encode '\n' with '\\\n' so you will get new json file as follows

`{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "intent": "affirm",
        "text": "ye\\ns"
      }
    ]
  }
`

Other way to solve this problem is to remove \n from texts while converting to md file, in that also we won't be able to regenerate the origin json file from converted md file.
