### ISSUE TITLE
Update Docker Walkthrough docs to new repository structure

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3425]

**Comment by amn41** [comment]
is the idea to provide a tutorial on how to use the `rasa` cli entirely through docker? locally or is this about deployment?

**Comment by wochinge** [comment]
The idea was more to update the docker walkthrough to new container infrastructure (one stack instead of Core / NLU)

**Comment by mark-collins-voxsio** [comment]
@wochinge Great that you're looking into this - any idea when it will be ready?

Could I ask you to bear in mind the challenges faced by users of Rasa? I've had quite a gnarly time trying to understand the various Rasa examples, some of the problems I hit are created by how the examples are structured; Code version changes invalidate previous flags/settings/paths etc. In a lot of the examples it is not always clear to users which files need to be altered, nor what the initial state was if the code only shows additions.  Nor is it clear whether certain steps like pipeline definitions are required. The docker walkthrough is actually one of the better pieces of Rasa documentation but it is fragile because it does not define which version it is for, so when the latest version moves, the thing breaks and is useless.

The user just wants to be able to go top-to-bottom and be confident that the code will produce a working bot. Too many times the documentation is either a fragmented explanation of code and execution flags (which require advanced understanding of the coding concepts in use and lose relevance and meaning when the code base shifts) or is otherwise impeded because of not stating which files should have what content in the final state. A lot of this could be improved if the documentation is specific about when it was written, which version of the code is being used in that example and to make that bullet-proof there should be a downloadable part of the example which is a complete runnable/buildable instance that is explicitly tied to that build version. That way future changes will not break the example. In this instance it would be a docker-compose.yml with references to specific builds 0.15.0 or whatever

Best wishes,

M

**Comment by amn41** [comment]
thanks @mark-collins-voxsio for chiming in. With the new setup, the cli requires far fewer flags to be set, so the commands look like `rasa train` rather than `python -m rasa_core.train -s stories.md -d domain.yml -o models/core ...` . So long as you stick with the standard project structure, you almost never have to provide any flags. That simplifies the examples, and means they won't change much between versions. Would love to get your take on the new documentation when it's ready in the next couple of weeks.

**Comment by mark-collins-voxsio** [comment]
@amn41 That's great, sounds like a much better approach :1st_place_medal: 

Let me know when it's ready, at the minute I'm homebrewing my rasa docker instances and that's just a waste of everyone's time

Best wishes,

M
