### ISSUE TITLE
domain format for slack menus

### ISSUE THREAD

**Issue by asyaFaiz** [RasaHQ/rasa#3455]
**Rasa Core SDK version**: 0.12.4

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubunutu 14.04

**Issue**:
domain format to display buttons & images in slack is given. Can't message menu s be displayed similarly? What is the format for message menus?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by erohmensing** [comment]
This is now supported with the new Rasa 1.0 release. Since slack is the only channel that supports dropdown menus, they are not a domain template type -- however you can do it two ways:
1. Using the [`- custom:` template](https://rasa.com/docs/rasa/core/domains/#custom-output-payloads)
2. Using the dispatcher method `utter_custom_json()` from custom actions to send a json dictionary to the output.

Both of these methods would use the slack-defined API call format described in [their docs](https://api.slack.com/messaging/interactivity#select-menus).
