### ISSUE TITLE
Duplicate event in SQLTracker

### ISSUE THREAD

**Issue by claudio-7lieues** [RasaHQ/rasa#3676]
**Rasa version**: 1.0

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): osx / postgreSQL

**Issue**: Duplicate event in SQLTracker. It seems the FLOAT precision can't handle the timestamp correctly. Actually, the field has a 5 digits precision, it needs at least 7. 

The column type should be change to numeric.

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by feynmanliang** [comment]
This issue is also arising during interactive training since https://github.com/RasaHQ/rasa/blob/master/rasa/core/training/interactive.py#L235 expects the entire event history to be replaced (as done in the `InMemoryTrackerStore` https://github.com/RasaHQ/rasa/blob/master/rasa/core/tracker_store.py#L131) but the `SQLTrackerStore` only appends events that are after the greatest timestamp (https://github.com/RasaHQ/rasa/blob/master/rasa/core/tracker_store.py#L411) without replacing previous events

**Comment by wochinge** [comment]
@claudio-7lieues In which setting did you see this problem?
@feynmanliang Thanks for the digging into this problem and providing the fix.
I have a look at your pr immediately.

**Comment by claudio-7lieues** [comment]
During normal usage.
