### ISSUE TITLE
Rasa_core.processor - Circuit breaker tripped. Stopped predicting more actions for sender ‘default’ 

### ISSUE THREAD

**Issue by NomanSaleem4** [RasaHQ/rasa#3680]
**Rasa version**: 0.1.1

**Rasa X version** (if used & relevant):

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): UBUNTU

Why am i getting this error, and how can i resolve it. As two actions get predicted one after each other without action_listen. I have attached the logs for clarification. Help would be much appreciated. I have tried to solve it through stories but no use.

![a](https://user-images.githubusercontent.com/17758473/58760102-d0e22100-854c-11e9-8b20-d3234ccb3c26.png)

**Comment by akelad** [comment]
Not sure what version 0.1.1 is -- do you mean 1.1.1? In any case, please post these kinds of questions in our [forum](https://forum.rasa.com). Something is likely wrong with your stories

**Comment by stacks13** [comment]
This happens when there is an active form and there's a new intent to start another form. FormPolicy and KerasPolicy get stuck in a loop.

Solution:
1) Create stories to deactivate the ongoing form using `action_deactivate_form` when there's an intent for another form
2) Modify the code of rasa.core.processor to handle this. There is a part where `on_circuit_break` is called. You can modify it so that it call an action (like fallback or twostagefallback or any other remote action of your choice) to take care of this.

**Comment by NomanSaleem4** [comment]
Great. This is what I was looking for.
So do I also need to handle it with stories by deactivating form if I am
also changing code in rasa. Core. Processor? Or I can skip step 1 in that
case?

**Comment by stacks13** [comment]
Actually, they are both separate solutions and not steps.
The first solution is for avoiding the error. The second is to handle it if at all it occurs. I'd recommend doing both, if there are many forms. If there's only a couple or so forms with less intents, you can make do with adding more stories.

**Comment by NomanSaleem4** [comment]
Great. Than you so so much.
