### ISSUE TITLE
Rasa as a Service?

### ISSUE THREAD

**Issue by mishushakov** [RasaHQ/rasa#3728]
Hi, thanks for building Rasa!
I have some questions.
So, let's say, I want to make a PaaS like Dialogflow with Rasa NLU as a backend

1. How can I have multiple Agents on a single instance? I can't afford to run a new Rasa server for each Agent. Your documentation does not say anything about running multiple Agent on a singe port/process
2. How can I route the NLU to a custom fulfilment (webhook) to generate the response? Rasa Core Actions with custom Python code looks non-sense for my task. I also does not want to run additional software as a proxy (like a request comes from outside world to a proxy, then a proxy forwards it to NLU, then the NLU response is forwarded to the fulfilment and finally the fulfilment response is returned to the outside world) I want it to be linear like in Dialogflow (outside world <-> Dialogflow NLU <-> Fulfilment)

Do you guys plan to make Rasa more flexible? How can I design an infrastructure with Rasa, which could be consumed by a big amount of customers with many chatbots and webhooks? It doesn't seems possible right now, without reinventing the wheel.

In my biggest dreams, I'd like to have a Rasa, where I could create and train as many Agents as I want, control and query them using REST API and make it possible, that NLU can return webhook results using HTTP :)

Thank you so much!!!

**Comment by amn41** [comment]
1. In versions <1.0, your Rasa NLU server can have multiple projects, see https://github.com/RasaHQ/rasa/issues/3259 
2. if you goal is to reproduce dialogflow, you may want to look at [this project](https://github.com/paschmann/rasa-ui) for inspiration, since I think it aims for something similar (though not as a service as fast as I understand). Another source of inspiration might be [myNLU](https://www.mynlu.com/)
