### ISSUE TITLE
Telegram channel markdown syntax problem

### ISSUE THREAD

**Issue by selphe** [RasaHQ/rasa#3750]
**Rasa version**:
rasa                    1.0.9
rasa-core               0.13.7
rasa-core-sdk           0.13.0
rasa-sdk                1.0.0

**Rasa X version** (if used & relevant):
rasa-x                  0.19.0

**Python version**:
Python 3.6.8

**Operating system** (windows, osx, ...):
Windows 10

**Issue**:
Seems default telegram connector doesn't support markdown syntax

**Command OR request that led to error**:
1. Add to `action.py` or `domain.yml` text with url in markdown syntax
2. Check your action/template in bot

**Result:**
You: test
Bot: `test link: [test](https://rasa.com/)`

**Expected result:**
You: test
Bot: test link: [test](https://rasa.com/)

**Content of configuration file (actions.py)** (if relevant):
```python
dispatcher.utter_message('test link: [test](https://rasa.com/')
```

**Content of domain file (domain.yml)** (if relevant):
```yml
  utter_test_url:
    - text: "test link: [test](https://rasa.com/)"
```

**Comment by akelad** [comment]
That's something telegrams frontend would need to handle so i'm afraid there's nothing we can do about this

**Comment by selphe** [comment]
Thank you for reply.
may be parameter `parse_mode = markdown` is missed?
https://core.telegram.org/bots/api#sendmessage

Not sure, how can I send it through domain.yml?
(https://github.com/RasaHQ/rasa/blob/master/rasa/core/channels/telegram.py#L98)

**Comment by akelad** [comment]
oh i didn't realise that was a parameter! @erohmensing could you look into that actually?

**Comment by erohmensing** [comment]
@selphe I believe if you change 
```
self.send_message(recipient_id, message_part)
```
to 
```
self.send_message(recipient_id, message_part, **kwargs)
```

you should be able to do it in your domain.yml (so just add `parse_mode = markdown` to the utterance). Same with actions.py, just add it as a keyword argument. 

I'd suggest making that utterance with the `parse_mode` key channel-specific though, as the reason we don't currently pass the kwargs to e.g. `send_message` is because if we did this in all channels and you switched, another channel wouldn't know what to do with the parameter and might not render your message.

**Comment by selphe** [comment]
Hello @erohmensing , thanks for workaround :) 
Any chance you add the ```parse_mode``` parameter as default to telegram channel?
Just to minimise channel specific settings in domain.yml...

**Comment by selphe** [comment]
@akelad any chance `parse_mode` parameter will be default in future?

**Comment by erohmensing** [comment]
@selphe it's possible that the change to `self.send_message(recipient_id, message_part, **kwargs)` will be default, we'll have to think about how this would affect the channels we already have. If we did change that then we could set the default to markdown because you could still pass HTML by declaring it. 

However, as I said, i'm wary about doing that because of other channels ending up failing with `got unexpected keyword argument "parse_mode"`. 

If you'd like to customize your text message, perhaps an even better workaround is using [custom output payloads] to specify your api call directly. E.g.
```
utter_test_url:
    - custom: 
       text: "test link: [test](https://rasa.com/)"
       parse_mode: markdown
```
or via 
```
dispatcher.utter_custom_json('test link: [test](https://rasa.com/', parse_mode='markdown')
```

**Comment by selphe** [comment]
@erohmensing thanks!
I misunderstood previous message, sorry.
I thought what i need to change source files to use this, but this workaround above, solves my case.

One remark, your example works when payload inside `{}`: 
```
dispatcher.utter_custom_json({'text': '[test](https://rasa.com)', 'parse_mode': 'markdown'})
```

**Comment by erohmensing** [comment]
Sorry, of course, thanks for the fix! Yes it's a json payload so it definitely needs to be everything inside the curly braces as you have it. 🙂 was a little late for me 😅 glad you are able to customize the message without changing the source code. That's why we added the custom functionality in the first place! :)
