### ISSUE TITLE
Rasa X - Couldn't get conversations from tracker store

### ISSUE THREAD

**Issue by dmlapteacru** [RasaHQ/rasa#3775]
Hello Rasa Team,

I have configured the tracker store (pgsql), but when I run Rasa X the conversations do not populate, even if I use API to chat (prod).

Tracker store (endpoints.yml):
![image](https://user-images.githubusercontent.com/33374107/59422368-f25acc80-8dd8-11e9-8ab0-602c3ad6c07f.png)

Sending message (postman):
![image](https://user-images.githubusercontent.com/33374107/59422432-0a325080-8dd9-11e9-82a7-2d566c659ba4.png)

Rasa X:
![image](https://user-images.githubusercontent.com/33374107/59422506-2f26c380-8dd9-11e9-82e7-d225c8279c5c.png)

Without tracker store, everything works, but I need data be saved.
Guide me please.

**Comment by akelad** [comment]
Please use the correct issue template when submitting a bug report in future.

@wochinge can you take a look at this?

**Comment by wochinge** [comment]
@dmlapteacru Which version of Rasa X are you using? In the latest versions there should already be a warning if you are using another tracker store then the sqlite one with Rasa X CE locally since Rasa X installed with pypi currently only works with the Sqlite tracker store (https://github.com/RasaHQ/rasa/issues/3702). We will be working on this soon. However, you can deploy Rasa X on a server and then you should be able to use different tracker stores: https://rasa.com/docs/rasa-x/deploy/

**Comment by dmlapteacru** [comment]
@wochinge I am using Rasa 1.0.6. 
Alright, got it. So other stores wont work locally, only on deploy.
Is it necessary to deploy all of the components in docker-compose?

**Comment by wochinge** [comment]
@dmlapteacru Yes except
* the `logger` component
* `duckling` (if you are not using it)
