### ISSUE TITLE
duckling suddenly can’t parse local timestamp

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#4006]
This happens when ~you don’t pass a timezone to the~ duckling ~configuration and it~ tries to get your time using [reference time](https://github.com/RasaHQ/rasa/pull/395/files#diff-32a523d525344ac72297ce3a019dadfeR88). 

I thought this was my new computer sending weird timestamps, but it’s happened on both old and new and was recently reported by a [community member](https://forum.rasa.com/t/tutorial-form-error-could-not-parse-timestamp/12873).

Warning:
```
2019-07-13 14:24:32 WARNING  root  - Could not parse timestamp fc976cc217934115b1f4b5d44b236d80. Instead current UTC time will be passed to duckling. Error: invalid literal for int() with base 10: 'fc976cc217934115b1f4b5d44b236d80'
```

**Comment by erohmensing** [comment]
This is a different warning, but may be related, when running `rasa x`, i got 
```
2019-07-17 17:47:16 WARNING  rasa.core.jobs  - apscheduler could not find a timezone and is defaulting to utc. This is probably because your system timezone is not set. Set it with e.g. echo "Europe/Berlin" > /etc/timezone
```

**Comment by msamogh** [comment]
Just encountered the first error myself. By "need to change something in rasa/duckling", do you mean the Docker image `rasa/duckling` or "rasa or duckling"?

**Comment by erohmensing** [comment]
i meant `rasa/duckling`, but I get the error even when docker isn't running. I was wrong, the error gets thrown [here](https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/extractors/duckling_http_extractor.py#L140) (why the hell as root though?)

**Comment by msamogh** [comment]
> when you don’t pass a timezone to the duckling configuration

I did pass a timezone and still got the same error.

**Comment by azharameen** [comment]
Hi, Is this issue fixed,

**Comment by erohmensing** [comment]
It isn't, the warning still shows. However, it doesn't seem to stop duckling from parsing dates at all, though it might be defaulting to UTC instead of time zone, i'm not sure.

**Comment by azharameen** [comment]
Thanks @erohmensing.
In my app I want date of birth, the intent goes below threshold and default fallback action is executed. I thought this might be the reason. Thanks for the reply, i'll check my training data.

**Comment by erohmensing** [comment]
@azharameen you can use `rasa shell nlu` to see how your bot parses messages, to see if it's picking up the entities correctly.

**Comment by anushkmittal** [comment]
bump same issue. I believe this is why it's giving me UTC -7 co-ordinates even though I am using "America/New_York" under time zone

**Comment by fanlu** [comment]
replace ```"locale": self._locale()```with```"lang": self.language```

**Comment by erohmensing** [comment]
@fanlu does this give the correctly-timezoned timestamp as well? If so, I'd love to take a contribution from you to fix it! 😃

**Comment by fanlu** [comment]
Yes, I think there is no problem with timezone.
this is my test case below.
```
curl -XPOST http://0.0.0.0:8000/parse --data 'dims=time&lang=en&l&tz=Asia/Shanghai&text=tomorrow morning&reftime=1573475247000'
[{"body":"tomorrow morning","start":0,"value":{"values":[{"to":{"value":"2019-11-12T12:00:00.000+08:00","grain":"hour"},"from":{"value":"2019-11-12T00:00:00.000+08:00","grain":"hour"},"type":"interva
l"}],"to":{"value":"2019-11-12T12:00:00.000+08:00","grain":"hour"},"from":{"value":"2019-11-12T00:00:00.000+08:00","grain":"hour"},"type":"interval"},"end":16,"dim":"time","latent":false}]
curl -XPOST http://0.0.0.0:8000/parse --data 'dims=time&lang=en&l&tz=Europe/Berlin&text=tomorrow morning&reftime=1573475247000'
[{"body":"tomorrow morning","start":0,"value":{"values":[{"to":{"value":"2019-11-12T12:00:00.000+01:00","grain":"hour"},"from":{"value":"2019-11-12T00:00:00.000+01:00","grain":"hour"},"type":"interval"}],"to":{"value":"2019-11-12T12:00:00.000+01:00","grain":"hour"},"from":{"value":"2019-11-12T00:00:00.000+01:00","grain":"hour"},"type":"interval"},"end":16,"dim":"time","latent":false}]
```

**Comment by kremio** [comment]
About the warning and the weird timestamp (https://github.com/RasaHQ/rasa/issues/4006#issue-467714715)

I tracked it down to https://github.com/RasaHQ/rasa/blob/master/rasa/core/interpreter.py#L288
```
result = self.interpreter.parse(text, message_id)
```
However, the interpreter ```parse``` function expects a ```datetime.datetime``` as its 2nd parameter (see https://github.com/RasaHQ/rasa/blob/f950f7c734e2482fd49bd97fb5a955d0708a1287/rasa/nlu/model.py#L354)

In turn ```parse``` instantiates a new ```rasa.nlu.training_data.Message``` (see: https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/training_data/message.py) . From the source code, it's not clear what the type of the parameter *time* in the constructor of ```Message``` should be.
However, the warning is triggered because the Duckling extractor tries to convert the value of the attribute ```time``` to an *int*.

Currently it breaks because the *weird* timestamp is the message_id passed by the interpreter in lieu of the expected datetime.

I'm not quite sure how it should be fixed because I have no idea what is the intended usage of the time attribute in the ```Message``` class beyond setting the reference time for the duckling engine. Maybe someone with a deeper knowledge of RASA's source code can look into it.

**Comment by nataliiao** [comment]
This warning occurs because (as you can see) `fc976cc217934115b1f4b5d44b236d80` is not a timestamp.
In rasa/core/processor.py:

`parse_data = await self.interpreter.parse(message.text, message.message_id, tracker)`

Where `self.interpreter` is an instance of the class RasaNLUInterpreter (in rasa/core/interpreter.py), and its `parse` method runs the following command:

`self.interpreter.parse(text, message_id)`

But `self.interpreter` in RasaNLUInterpreter is an instance of the Interpreter class (rasa/nlu/model.py) and its `parse` method takes `text` and `time` (**not message_id**) as arguments. So it receives message_id and tries to treat it like a timestamp, it can't and gives you a warning.
