### ISSUE TITLE
Not all intents are returned when doing parse

### ISSUE THREAD

**Issue by jahirfiquitiva** [RasaHQ/rasa#4029]
Hello

When doing a call to `http://localhost:5000/parse`, I'm not getting more than 10 intents in the response, but there are actually 18.

Is this the expected behavior? or is there something wrong?

Additionally, I wanted to ask, how many phrases would you say make an intent gain enough confidence?

**Comment by psds01** [comment]
This is actually an expected behaviour. You can find it [here](https://github.com/RasaHQ/rasa/blob/737484a36bc4a1c0fb1584232f79d978f6fdb592/rasa/nlu/classifiers/__init__.py#L3) 
If you want all of them, set the above to `None` : `INTENT_RANKING_LENGTH = None`.

> Additionally, I wanted to ask, how many phrases would you say make an intent gain enough confidence?

There's no rule of thumb, start with 2 which is `rasa`'s default min count of examples per intent then start adding more to gain good performance.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
