### ISSUE TITLE
rasa/rasa-x end point to display predicted entities

### ISSUE THREAD

**Issue by cyrilthank** [RasaHQ/rasa#4046]

**Comment by cyrilthank** [comment]
can you please share the http api end point to use to display predicted entities
along with the rasa/rasa-x version to use for this

followup to 
https://github.com/RasaHQ/rasa/pull/3128

**Comment by erohmensing** [comment]
@cyrilthank as described in the issue template, please do not ask questions on the Github. Questions like these belong in the forum (if you choose `question` rather than `enhancement` or `bug`, it likely does not belong here). The [HTTP API](https://rasa.com/docs/rasa/api/http-api/) is well documented, you are looking for https://rasa.com/docs/rasa/api/http-api/#tag/Model/paths/~1model~1parse/post. AFAIK rasa-x uses the same endpoint for NLU parsing.
