### ISSUE TITLE
Request /model/parse: when the value of text starts from / , confidence is always 1

### ISSUE THREAD

**Issue by zengande** [RasaHQ/rasa#4161]
**Rasa version**: 1.2.0

**Python version**: 3.6.8

**Operating system** (windows, osx, ...):  Ubuntu 18.04.2 LTS

**Issue**:
When I request `/model/parse` and the `text` value is start with `/`, I get an amazing result.

Request: `curl http://localhost:5005/model/parse -X POST --data '{"text":"/everything"}'  `                                
Response:
```
{"text":"\/everything","intent":{"name":"everything","confidence":1.0},"intent_ranking":[{"name":"everything","confidence":1.0}],"entities":[]}
```

**Comment by zengande** [comment]
Please forgive my poor English. You can try it.

**Comment by erohmensing** [comment]
HI there! This is actually intended. We use this format to bypass the NLU to test out the dialogue management, and for direct intent payloads for e.g. initial payloads from the front end, buttons, etc. So your buttons might have payloads like 
```
buttons: 
- title: "Yes"
  payload: "/affirm"
- title "No"
  payload: "/deny"
```
using the intent format (this is what we call it) makes it so that the success of these buttons in driving your dialogue flow has nothing to do with how well your model can parse "yes" and "no". It's not a bug 🙂

**Comment by zengande** [comment]
@erohmensing  Thank you for your reply, I understand. ☺
