### ISSUE TITLE
Rasa X /api/domain?store_templates=true fails

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4400]
**Rasa X version**: 0.20.2

**Issue**:

I just upgraded Rasa X to 0.20.2 and the endpoint for `PUT /api/domain?store_templates=true` returns a status 500.

If I call `PUT /api/domain` the call succeeds.

Has the `store_templates` option been dropped?  If so, there's no mention of this in the changelog or latest API docs.

**Comment by sara-tagger** [comment]
Thanks for the issue, @gausie will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by gausie** [comment]
It hasn't been dropped - this is a bug. I'll get this sorted.

**Comment by wochinge** [comment]
@rgstephens Could you please retry with `0.20.3` (there will be also another release late today, early next week)? I believe this was caused by a wrong database type, which didn't allow template names longer than 255 chars.

@tangochris If you install Rasa X the compatible Rasa version is automatically installed with it. However, you are right, it's currently not really transparent which `rasa` versions you can use if you want to manually update `rasa`. I'll discuss this with my team so that we can work on a solution for that. `0.20.3.` should be compatible with `rasa` `1.2.x`. Our next release will then be compatible with Rasa `1.3.x`.

**Comment by tangochris** [comment]
@wochinge Upgrade to 0.20.3 solved our issue. Thanks!

On the topic of compatible versions, we deploy a custom docker image to an ECS cluster on AWS, so we're not able to benefit from any automatic installation.

**Comment by wochinge** [comment]
> @wochinge Upgrade to 0.20.3 solved our issue. Thanks!

Great! 

> On the topic of compatible versions, we deploy a custom docker image to an ECS cluster on AWS, so we're not able to benefit from any automatic installation.

thanks for your feedback! It's already an item on our todo list, but I added your feedback to push it a bit 🙂
