### ISSUE TITLE
Rasa X Renaming models

### ISSUE THREAD

**Issue by neumann-d** [RasaHQ/rasa#4518]
**Description of Problem**: When uploading a model file via `curl` command to Rasa X, it checks that the model name not already exists. To upload an external updated model it needs to be renamed before on the client side. When training a model with Rasa X, it creates an autogenerated name `timestampXYZ.tar.gz`.

**Overview of the Solution**: Add functionality to rename a model in the UI and maybe also to allow override an existing model with the same name.

**Examples**: Helps to improve users flexibility when sharing models or to sort models.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@federicotdn will get back to you about it soon!✨

**Comment by Ben-Mark** [comment]
Any updates on this feature request?

**Comment by Ben-Mark** [comment]
?

**Comment by federicotdn** [comment]
Hey @Ben-Mark, apologies for the delay. @TyDunn do you know if we have this feature planned for the future?

**Comment by TyDunn** [comment]
Hi @Ben-Mark. As long as I upload a model with a unique name to Rasa X, I am able to upload it with any name. Is that not the case for you? 

Why would you want to override an existing model with the same name?

**Comment by neumann-d** [comment]
Hi @TyDunn. Overriding an existing model would allow easier interaction with Rasa X and other services (plain Rasa servers etc.) via Rasa X API.

Example for override: You have a running Rasa instance with a model `myAwesomeModel` loaded. Then you want to make some improvements to that model in Rasa X. You could just upload `myAwesomeModel` to Rasa X, improve it (train it in Rasa X) and fetch `myAwesomeModel` externally to reload it into your Rasa instance.

Example for renaming: If you manage two chatbot models with Rasa X `myPizzaBot` and `myHotelBot`. When both are uploaded to Rasa X and retrained, then you don't know if the new trained models belongs to `myPizzaBot` or `myHotelBot` due to the autogenerated name `timestampXYZ.tar.gz`.

**Comment by TyDunn** [comment]
Hi @neumann-d. I have a couple more questions to understand how you are using Rasa X 😄

Override: what advantages do you see in training a model in Rasa X instead of training it in a CI/CD pipeline (e.g. improve `myAwesomeModel` in Rasa X --> push changes in Rasa X UI to remote Git repo --> triggers a CI/CD pipeline that trains the model, naming it `myAwesomeModel`, and automatically uploads `myAwesomeModel` externally to reload it into your Rasa instance)?

Renaming: Why are using Rasa X for two assistants: `myPizzaBot` and `myHotelBot`?

**Comment by neumann-d** [comment]
Hi @TyDunn.

Normally when I use Rasa X, then I train it serveral times in Rasa X to directly test the changes. The new Git integration feature would be also a nice way to apply changes to another service, right. But I think not all users want to setup an additional Git Repo and implementing the option to override/renaming should not be that big deal.

Rasa X needs a lot of resources to boot up/run in a mircoservice environment. Therefore it is nice to only launch one instance for improving multiple assistants.

**Comment by Ben-Mark** [comment]
@TyDunn 
Every model I train via rasa-x is saved in s3 (unfortunately with another node service hack that manages the i/o changes on the machine's disk since the s3 storage feature is not working, added a different issue for that.)

The problem is that I need to go all the way to s3 and to rename the models , simply to give them meaningful names.

that's a real pain because all the trained models via rasa-x get a date-time name which is unreadable 

I wish I had the option to click on the model name and a rename capability would exist.

That way, I can focus on my NLP training and not go back and forth to my s3 models repo.

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
