### ISSUE TITLE
e2e evaluation raises ZeroDivisionError

### ISSUE THREAD

**Issue by ricwo** [RasaHQ/rasa#4520]
**Rasa version**: 1.3.6

**Python version**: 3.6

**Operating system** (windows, osx, ...): osx

**Issue**:

e2e story evaluation always raises `ZeroDivisionError`

**Error (including full traceback)**:
```
Processed Story Blocks: 0it [00:00, ?it/s]
2019-09-25 15:30:06 WARNING  rasa.core.training.generator  - There is no starting story block in the training data. All your story blocks start with some checkpoint. There should be at least one story block that starts without any checkpoint.
2019-09-25 15:30:06 INFO     rasa.core.test  - Evaluating 0 stories
Progress:
0it [00:00, ?it/s]
2019-09-25 15:30:06 INFO     rasa.core.test  - Finished collecting predictions.
2019-09-25 15:30:06 WARNING  rasa.nlu.test  - No labels to evaluate. Skip evaluation.
Traceback (most recent call last):
  File "/Users/ric/.envs/platform/bin/rasa", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "/Users/ric/dev/rasa/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/ric/dev/rasa/rasa/cli/test.py", line 88, in test_core
    kwargs=vars(args),
  File "/Users/ric/dev/rasa/rasa/test.py", line 108, in test_core
    rasa.core.test(stories, _agent, out_directory=output, **kwargs)
  File "uvloop/loop.pyx", line 1448, in uvloop.loop.Loop.run_until_complete
  File "/Users/ric/dev/rasa/rasa/core/test.py", line 483, in test
    completed_trackers, agent, fail_on_prediction_errors, e2e
  File "/Users/ric/dev/rasa/rasa/core/test.py", line 430, in collect_story_predictions
    in_training_data_fraction = _in_training_data_fraction(action_list)
  File "/Users/ric/dev/rasa/rasa/core/test.py", line 383, in _in_training_data_fraction
    return len(in_training_data) / len(action_list)
ZeroDivisionError: division by zero
```

**Command or request that led to error**:
```
$ rasa test core --stories e2e.md --e2e
```

**Comment by melindaloubser1** [comment]
I ran into this too. It looks like the problem is that if a e2e story specifies intents as `/intent` (or actually if the intent line contains a forward slash `/` anywhere), they will match the regex for NLG format (see `rasa.nlu.training_data.loading.guess_format` ), and therefore `rasa.data.is_nlu_file` will return `True`, since the format is not `UNK`. In the function `rasa.data._find_core_nlu_files_in_directory`, if a file is found to be NLU format, it is not checked whether it is e2e/story format, and therefore not added to the story data to load, leading to empty trackers and the ZeroDivisionError. 
This was my temporary work around:
```
def _find_core_nlu_files_in_directory(directory: Text,) -> Tuple[Set[Text], Set[Text]]:
    story_files = set()
    nlu_data_files = set()

    for root, _, files in os.walk(directory):
        for f in files:
            full_path = os.path.join(root, f)

            if not _is_valid_filetype(full_path):
                continue
            ##FIXME: finds NLG format for e2e stories with /intent declarations, therefore does not add any files to story_files, therefore causing ZeroDivisionError later in e2e testing
            if is_nlu_file(full_path):
                nlu_data_files.add(full_path)
            if is_story_file(full_path): #elif
                story_files.add(full_path)
```

**Comment by melindaloubser1** [comment]
If I understand the expected NLG format correctly, modifying `_nlg_markdown_marker_regex` to exclude the pattern `: /` should solve the problem without affecting the loading of other data formats i.e. `_nlg_markdown_marker_regex = re.compile(r"##\s*.*\n\*.*(?<!\: )\/.*\n\s*\t*\-.*")`

**Comment by wochinge** [comment]
Hi @melindaloubser1 , is this something you would like to work on? I'd also help you with the implementation, just tag me in the PR 🙂

**Comment by melindaloubser1** [comment]
@wochinge sure, I can work on it. Haven't contributed to an open source project before though, just fyi, but I'd like to get started.

**Comment by melindaloubser1** [comment]
Hi @wochinge - sorry to take so long to get to this. Do you know where I could find examples of NLG story files? I've looked through the readers for that format but can't figure out when one would be loading that kind of data or what exactly it would look like.

**Comment by wochinge** [comment]
> . Do you know where I could find examples of NLG story files?

What do you mean by `NLG story files` @melindaloubser1 ?

**Comment by melindaloubser1** [comment]
@wochinge I'm looking for the `nlg_markdown` format that e2e-format stories are getting identified as.  It's described in rasa.nlu.training_data.loading (line 50):
```
# looks for pattern like:
# ##
# * intent/response_key
#   - response_text
_nlg_markdown_marker_regex = re.compile(r"##\s*.*\n\*.*\/.*\n\s*\t*\-.*")
```
I thought it might be the format returned by an NLG server, but it looks like that isn't the case. Since E2E stories that look like:
```
* intent: /intent
    - action
```
are getting identified as `nlg_markdown`, I wanted to check that any changes I make don't change the handling of `nlg_markdown` formatted files, hence why I'm trying to find out what they look like and when they would be used.

**Comment by wochinge** [comment]
What you found is actually for https://rasa.com/docs/rasa/core/retrieval-actions/ .

The reader for end 2 end stories is here: https://github.com/RasaHQ/rasa/blob/99cd0d849021b5d27e5f0c6023c0da9f729e41d0/rasa/core/training/dsl.py#L33

**Comment by melindaloubser1** [comment]
Ok, thank you, that is what I was looking for (the retrieval actions template).

**Comment by erohmensing** [comment]
@wochinge did the PR close the entire issue?
