### ISSUE TITLE
Status endpoint doesn't return the name of the actual model

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#4586]
The `/status` currently returns the name of the deserialised model stored in the tmp folder rather than the name of the actual original model

- [x] implementation done
- [ ] adding tests

**Comment by btotharye** [comment]
I'll look at this soon, should be around https://github.com/RasaHQ/rasa/blob/master/rasa/server.py#L395 just making notes for myself

**Comment by btotharye** [comment]
@msamogh any suggestions on what we might should call this other status object since this model_file is used quite a bit in the code as the actual file for training and such, so I think we should still show that filename but also give something like `original_model` or something maybe to give the original filename.

Thoughts? 

I'm still digging through to figure out the best place to add this because it doesn't appear the `app.agent` object from the server.py has anything but the `model_directory` value atm and none of the other objects I can see have this original value as a value anywhere yet.

**Comment by btotharye** [comment]
https://github.com/RasaHQ/rasa/tree/fix_model_status is the code for this so far, mainly just need feedback on the name of `latest_model`

**Comment by msamogh** [comment]
I'm actually wondering if there's any reason to output the temporary path at all. We should just be able to replace it with the output of `model.get_latest_model()`. Of course, in that case, we'd have to wait for the next minor release (as it'd be a breaking change).

**Comment by btotharye** [comment]
yea the only reason I can think to keep it around would be for troubleshooting purposes in case we wanted a easy way to know where the actual tmp model file is, do you think that would be useful at all?

If not I can just update this and do a PR for it to replace model_file

**Comment by msamogh** [comment]
I mean you can always look at the identical file in the `models/` directory to perform any inspection. @wochinge Thoughts?

**Comment by wochinge** [comment]
I think there is no reason to keep the `tmp` one around 👍 If the unpacking fails, there should be enough other errors.

**Comment by btotharye** [comment]
Still leaving this open a little longer since I need to write tests for this, so general FYI

**Comment by wochinge** [comment]
if you don't have time to tackle it this week, I'd actually create a separate issue for that.

**Comment by btotharye** [comment]
Actually I don't need to write tests they are already there since I only updated the name https://github.com/RasaHQ/rasa/blob/master/tests/test_server.py#L110 right? @wochinge

**Comment by wochinge** [comment]
True, but shouldn't we test that this actually a valid file + not in `tmp`?

**Comment by btotharye** [comment]
created new issue https://github.com/RasaHQ/rasa/issues/4681 to track the tests @wochinge so can we close this one out now?
