### ISSUE TITLE
Jupyter notebook docs should be updated to use RasaFileImporter

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#4624]
The docs [https://rasa.com/docs/rasa/api/jupyter-notebooks/](https://rasa.com/docs/rasa/api/jupyter-notebooks/) should be updated to use [https://rasa.com/docs/rasa/api/training-data-importers/](https://rasa.com/docs/rasa/api/training-data-importers/).

**Comment by joaorobson** [comment]
I am interested in working with this issue. Only to clear up for me, the change that you are referring to is related to the way that the Jupyter docs page shows how a model should be trained, passing as parameters to the train method the paths to the relevant files. Instead of that, a custom file importer should be used?

**Comment by erohmensing** [comment]
The notebook code has to be updated in order to do this -- it's still running rasa 1.1.3. So @joaorobson it may be easiest if I update that first and then let you know when its ready, since it involves changes to another repo as well

**Comment by wochinge** [comment]
> Instead of that, a custom file importer should be used?

Not a custom one, the `RasaFileImporter` would be fine.

**Comment by erohmensing** [comment]
Oh boy. Still need to update the binder. Thanks stalebot 😅
