### ISSUE TITLE
Rasa sends entire conversation history to NLG server, causing "Request Entity Too Large" errors

### ISSUE THREAD

**Issue by tangochris** [RasaHQ/rasa#4713]
**Rasa version**: 1.4.3
**Rasa X version**: 0.22.0

**Issue**: In request to NLG server, Rasa sends entire event history. If a conversation is long, the API request to NLG server gets very large and causes errors.

Please provide a method to limit the amount of history sent to the NLG server. This may be tangentially related to #3011.

**Error**:

Python warning from logs:
```
/build/lib/python3.6/site-packages/aiohttp/payload.py:228: ResourceWarning: 
Sending a large body directly with raw bytes might lock the event loop. 
You should probably pass an io.BytesIO object instead
```

Error from our NLG server from logs:
```
2019-10-31 19:13:25 DEBUG rasa.core.processor - 413, Payload Too Large, 
body='b'request entity too large''

```

**Command or request that led to error**:

Chatbot becomes unresponsive when a user reaches about 600 turns in a conversation. In the logs we see that our Koa-based NLG server returns a "413 Request Entity Too Large" error for these long conversations because the API request exceeded the (default) 1MB.

Our fix was to patch Rasa to entirely skip event history in the API request to our NLG server. We don't like this fix as we're messing with Rasa core.

The core issue is that the NLG server only needs the name of a single template — it has no need for the entire event history. **Sending the entire event history is a waste of bandwidth, processing power and storage.**

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
@tangochris Thanks for the issue and the detailed description. 

Do you want to fix the bug yourself and create a PR for it? Otherwise, I'll add it to our backlog and we will fix this as soon as possible.

**Comment by amn41** [comment]
its not quite so straightfoward, because for example in the default NLG implementation you can use slots to fill in data. So at the very least slots need to be passed along as well. So maybe we can send the tracker but give the user the option to exclude the list of events?

**Comment by tangochris** [comment]
@tabergma @amn41 As Alan inferred, I think this might be better for you to do as there are a lot of implications. 

As a near-term fix, an option to exclude or limit the list of events would solve our problem.

I would imagine that longer-term, you may want to limit the events as the default. Oftentimes this issue won't surface during development because there won't be enough turns in test conversations. It'll surface after the bot is in production and real people are having long, regular conversations. I'm thankful we had a very committed test user so we discovered this one early.

**Comment by wochinge** [comment]
This will be solved when we tackle https://github.com/RasaHQ/rasa/issues/3011

**Comment by amn41** [comment]
@wrathagom  does rasa 1.6.0 now only send events from most recent session to action server?

**Comment by wrathagom** [comment]
Assuming this was meant for @wochinge not me.

**Comment by amn41** [comment]
haha thanks caleb!

**Comment by wochinge** [comment]
>  does rasa 1.6.0 now only send events from most recent session to action server? 

Yes! I'll this issue then.

**Comment by benos** [comment]
I'm not sure this issue has been solved by #3011 :

Within a session, the action server can still get sent a really large request of the conversation gets long, causing errors

Also, it doesn't seem to be doing what it is supposed to. I.e. if the session expires, the json payload still contains the entire history. 

In the screenshot is the count of the events in the tracker sent to my action server (note that it is a custom one written in node.js and not the Python SDK). Within that sequence, multiple session restart happen (both using a one minute timeout and action_restarts in the stories.md) but the count keeps growing. I'm fairly sure the restarts are successful because the slots get rest.

![image](https://user-images.githubusercontent.com/1001662/74955196-91be6d80-5404-11ea-9f69-6d3197fe94cb.png)

Am I missing something? If not then I would suggest this needs revisiting. In my view we need a way to limit the amount of events being sent, but if the session expiring is the only control then it should at least work :-)

Using RASA 1.7.0, in memory tracker and a custom action server.

**Comment by benos** [comment]
Not a massive expert on the RASA codebase, but it seems to me this is the guilty line in action.py:

![image](https://user-images.githubusercontent.com/1001662/74958776-bec14f00-5409-11ea-9cb4-e95753d634b1.png)

I think EventVerbosity.AFTER_RESTART would be the correct one for #3011 to deliver on it's promise 

(though I would still advocate for a limit within the session).

**Comment by tangochris** [comment]
@benos I took a look at our logs to see whether this problem is still occurring for us. As far as I can tell, the request to our NLG server is correctly sending only the events for the current session. Sounds like your issue concerns action server requests rather than NLG server requests, so perhaps this should be a new ticket?

On a related note, sending the event history is entirely unnecessary. All our NLG server needs is the template name.

**Comment by benos** [comment]
@tangochris Thanks for the input. 

You're right, I got confused by the question "does rasa 1.6.0 now only send events from most recent session to action server?" https://github.com/RasaHQ/rasa/issues/4713#issuecomment-567461205

@wochinge  New ticket or can we continue the conversation here?

**Comment by wochinge** [comment]
@benos Good catch with this line https://github.com/RasaHQ/rasa/blob/96a46713869b7ef7dd40885d1d173f6d97d07bfe/rasa/core/nlg/callback.py#L60 . However, when using the `SQLTrackerStore` or the `MongoTrackerStore` there should only be events since the last session in the `tracker` so that would be fine. 

> On a related note, sending the event history is entirely unnecessary. All our NLG server needs is the template name.

I guess that depends on the implementation of the NLG server. However, we could make this configurable 🤔 Can you create a feature request for this please?

**Comment by benos** [comment]
@wochinge Actually I meant this one :-)

https://github.com/RasaHQ/rasa/blob/96a46713869b7ef7dd40885d1d173f6d97d07bfe/rasa/core/actions/action.py#L389

(@tangochris and myself have different concerns: He is on the NLG side whereas I am having issues with the action server)

> However, when using the SQLTrackerStore or the MongoTrackerStore there should only be events since the last session in the tracker so that would be fine.

OK, good to know. I'll try with the SQLtrackerstore.

> However, we could make this configurable 🤔
+1

To add one data point: 

At the moment I only have one situation where I need more history than the latest event and I could code around that. So a config where I could specify the max amount of turns to send to the action server would be ideal. 

If not then a config to switch off sending events altogether would be preferable in my view.

In fact, my ideal payload would also exclude the domain - it seems odd to send a static config that can get quite large with every single request.

This would reduce the payload to a stable few dozen lines rather than the hundreds or even thousands it easily grows to now.
