### ISSUE TITLE
add info about how to upgrade rasa to docs

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#4879]
Right now, the installation section tells you how to install, but not how to upgrade your installed version. we should add that info to the documentation. Inspired by [this forum post](https://forum.rasa.com/t/how-do-you-upgrade-rasa/21845)

**Comment by JulianGerhard21** [comment]
Hi @erohmensing ,

I am not sure if you read my Slack post, in case not here is it again:

_"Hi all, I justed wanted to share an observation out of the Forum: Currently a lot of people are struggling installing Rasa / Rasa X because of the latest update to Tensorflow 1.15.0. Mostly this is due to outdated pip versions or incompatible python versions. For example, Python 3.8 is currently not supported and everyone should update his/her pip version to 19.3.1. Here is a list of all prebuilt wheels, since building it from scratch is a bit tricky sometimes: https://pypi.org/project/tensorflow/1.15.0/#files . "_

Alan asked me if I could update the installation docs accordingly in a PR and I stumpled upon your Issue here and thought that maybe it may be worth to consider aswell. 

What do you think?

Regards
Julian

**Comment by sekhar2017** [comment]
Yes I would like to contribute to fix this.

**Comment by sekhar2017** [comment]
Please assign me.

**Comment by erohmensing** [comment]
great @sekhar2017 thank you! I think it should live on the [installation page](https://rasa.com/docs/rasa/user-guide/installation/) under a new header, like `Updating Your Rasa Open Source Version`. 

I usually include information about 
1. how to upgrade to the latest version 
2. how to download a specific version

**Comment by sekhar2017** [comment]
Hi 

Can i get the guidance on this to proceed ?
Lately i couldn't login due some health issues.

**Comment by erohmensing** [comment]
Hey @sekhar2017, you can definitely still take this one on as it hasn't been handled yet! The instructions I put above still stand :)
