### ISSUE TITLE
If pipeline validation failed - suggest a component to fix the pipeline

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#496]
Eg. if the pipeline fails with "Can't find "tokens"." The suggestion would be to add a tokenizer (any of the components providing "tokens") to the pipeline before the component where the validation failed.

**Comment by hsm207** [comment]
can I work on this?

**Comment by erohmensing** [comment]
@hsm207 sorry we didn't see your comment, are you still interested in working on this?

**Comment by hsm207** [comment]
@akelad sure. but is there someone around to help me with questions I have about this issue? For example, where in the code base should I start looking at to see the ways in which the pipeline validation can fail?

Also, could you please have a look at my comment on issue #2865 ?

**Comment by erohmensing** [comment]
Probably best if you stick to one issue at a time actually. I will ping tmbo to get him to respond to your py-redis questions.

**Comment by erohmensing** [comment]
Since the other was closed, I guess this one works then 😄

> @erohmensing sure. but is there someone around to help me with questions I have about this issue? For example, where in the code base should I start looking at to see the ways in which the pipeline validation can fail?

@dakshvar22 can help you with questions on this issue. I believe you want to look at the `requires` sections of each component (e.g. [here](https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/extractors/crf_entity_extractor.py#L30) and if the required parameter is missing, you can recommend another component that `provides` that parameter and tell the user to add it to the pipeline before the failed component.

**Comment by dakshvar22** [comment]
@hsm207 Are you still working on this issue? Let me know if you have any questions.
