### ISSUE TITLE
Identify model testing blockers

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#5099]
To make it easier to integrate model testing and validation as part of a CI pipeline, we need to identify current blockers / things which are not smooth. 

Suggested setup:

1. Rasa project including action server 

Things to do:

1. Validating training data
2. Testing NLU
3. Testing Core
4. e2e testing of the model

The docs should help on the single steps: https://rasa.com/docs/rasa/user-guide/evaluating-models/

**Comment by alwx** [comment]
I used several different rasa bots (newly created project initiated with `rasa init`, `examples/formbot` and `examples/restaurantbot`) for testing. Everything went smooth, except for one very small thing:

When I tried validating `restaurantbot`, it showed me a stack trace and the following error:
```
rasa.nlu.model.InvalidModelError: Model 'en' is not a linked spaCy model.  Please download and/or link a spaCy model, e.g. by running:
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en
```
I understand that the error is expected and it can be fixed in a minute, but maybe we should either check if all the prerequisites are satisfied before running tests or just download and link the spacy model automatically.

**Comment by wochinge** [comment]
How was writing the end-to-end tests for you? Did you find enough documentation? How did end-to-end testing go with the action server? Did you start it before and then executed things?

**Comment by alwx** [comment]
I will check it out one more time and update you with more information later today/tomorrow.

**Comment by wochinge** [comment]
@alwx Any news on this?

**Comment by alwx** [comment]
@wochinge not really, because I am currently busy with other issues. 
But I will find the time, check it tomorrow, and update you.

Sorry for the delay.

**Comment by wochinge** [comment]
Cool, thanks. Just important so that we can decide what to do here for our okr

**Comment by alwx** [comment]
@wochinge 
So I spent some time today checking it again and remembering my previous experience.

Again, everything was relatively easy and straightforward, but maybe that's because I already know that the action server needs to be running and how some of the things work.

> How was writing the end-to-end tests for you?

Honestly, the `examples/formbot/tests/end-to-end-stories.md` helped me more than the documentation: https://rasa.com/docs/rasa/user-guide/evaluating-models/#end-to-end-evaluation
But that's just me — I prefer learning by exploring examples. Anyway, the process of writing e2e tests is relatively easy and straightforward — the only thing I am thinking of is giving more examples in the documentation or just providing links to already existing ones.

> Did you find enough documentation?

Yes, I think https://rasa.com/docs/rasa/user-guide/evaluating-models doc gives more than enough information.

> How did end-to-end testing go with the action server? Did you start it before and then executed things?

I've forgotten to start it when I was executing tests for the first time, but then I saw an error and understood that the server needs to be running because otherwise actions cannot be executed. I guess it's more or less obvious for everyone who's writing code and running tests, and I am not sure if any explicit information needs to be added (especially considering the fact that it's very hard not to notice errors).

**Comment by wochinge** [comment]
cc @TyDunn

**Comment by TyDunn** [comment]
@wochinge Thanks for the nudge. I have been thinking about and am now writing my thoughts down here: https://docs.google.com/document/d/1PNavef4M3WyA6drAT9KPStSx8FuUPvWcFICpKS0epZU/edit

**Comment by TyDunn** [comment]
@wochinge I have been thinking about this and will now record my thoughts. I will polish this scope and then ask for feedback from the squad later today: https://docs.google.com/document/d/1PNavef4M3WyA6drAT9KPStSx8FuUPvWcFICpKS0epZU/edit
