### ISSUE TITLE
Support for tensorflow/keras OR pytorch policies

### ISSUE THREAD

**Issue by staticdev** [RasaHQ/rasa#5188]
**Description of Problem**: current rasa version is tightly coupled with tensorflow and is not practical for the use of pytorch. Pytorch is growing very fast and is ofter considered as an option for ML solutions.

**Overview of the Solution**:
A possible solution is the creation of PytorchPolicy as it exists with KerasPolicy. Transformer embedding policies should also choose if it uses Tensorflow or Pytorch. This way, tensorflow would not be a requirement for rasa anymore (it would be optional the same way as pytorch).

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:
- [x] Tests are added
- [x] Feature described the docs
- [x] It is possible to install and create a rasa bot without tensorflow installed.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by JustinaPetr** [comment]
Hi @staticdev. Thanks for your suggestion. At the moment we don't have plans to implement pytorch policies. This is based on our approach that we implement new policies if they benefit a new method instead of just supporting new underlying libraries.

Nonetheless, thank you for your suggestion! 😊 

I will close this for now.
