### ISSUE TITLE
Issue with /restart and slot

### ISSUE THREAD

**Issue by AsfiaKawnine** [RasaHQ/rasa#5205]
Hello. I have developed a bot and created a custom action, where I will take input from the users and store their input in slots, later the input is used for authentication. The problem is when the action against slot is triggered, the /restart action doesn’t work. I want to clear the log when /restart action is called. How can I solve this problem?

![Capture](https://user-images.githubusercontent.com/39495209/74099873-60b38280-4b52-11ea-9fca-34473b4607ef.PNG)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by IgNoRaNt23** [comment]
The problem here is the action prediction. There are at least two policies in play, the MappingPolicy, which handles the restart action and the FormPolicy for any FormAction. Both policies predict their action with a confidence of 1.0 in your case, but the FormPolicy has a higher priority than the MappingPolicy, which means that the FormPolicy always wins. So no restart may be triggered, if the form is never left. Which may happen, when you have 'self_from_text'-mapping for your slot. 

My solution to the problem is to use an additional custom-mapping policy, which handles the restart (and some custom debug actions in my case) with the highest priority of all policies, so it will always win the policy race.

**Comment by AsfiaKawnine** [comment]
Thanks for your reply. Is there any documentation for custom-mapping policy? I am new to rasa, so it would be great if I could look into any example or documentation. Also is there any way to call action_restart while checking slot validation inside a form?

**Comment by IgNoRaNt23** [comment]
Well, you could fix this in a really ugly way. Since youre overwriting the 'required_slots' method anyway, you could check there, if the current intent is 'restart' and raise an ActionExecutionRejection there, which will get you out of the form action.
