### ISSUE TITLE
Reformer Embedding Dialogue Policy (REDP)

### ISSUE THREAD

**Issue by staticdev** [RasaHQ/rasa#5295]
**Description of Problem**: Google announced an optimization of Transformers, which is the based of Rasa's embedding policy with reduced complexity and equivalent results according to their [accompanying article](https://arxiv.org/abs/2001.04451). Offering this policy is a great improvement since training models represents costs for all Rasa's users.

**Overview of the Solution**:
Maintain the Embedding Policy but instead of using Transformers, use the Reformer implementation (this is provided by [Trax](https://github.com/google/trax) Python library). 

**Definition of Done**:
- [x] Tests are added
- [x] Feature described the docs
- [x] Feature mentioned in the changlog

**Comment by amn41** [comment]
thanks @staticdev for the suggestion! I think it's a cool idea, but the scalability of the reformer (as I understand it without having read the paper in detail) is related to the length of a sequence. Since we don't have many stories with hundreds or thousands of turns, I don't think it's the most urgent thing for us to work on.
