### ISSUE TITLE
Setup TensorFlow environment

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5350]
In [https://github.com/RasaHQ/rasa/pull/5266](https://github.com/RasaHQ/rasa/pull/5266) we discussed when and how to call `tf_env.setup_tf_environment()`. We should find a solution for users that call the train methods directly.

**Comment by tabergma** [comment]
@dakshvar22 Is this still relevant?

**Comment by dakshvar22** [comment]
Probably yes, we haven't changed it since then.

**Comment by samsucik** [comment]
@dakshvar22 sorry, I'm struggling to find the context for this one, could you perhaps briefly summarise? And what kind of users does this affect?

**Comment by dakshvar22** [comment]
@samsucik `tf_env.setup_tf_environment()` is used to initialize CPU/GPU related environment variables of TF. We currently call this inside `rasa/__main_.py`. Hence, it works well when rasa open source is being invoked as a framework through the CLI or HTTP API. If a user tries to use it as a library where they try to write custom python code and pick bits and pieces of Rasa in their custom code, e.g. training an NLU model in a jupyter code, then depending on their code tensorflow environment may not configured correctly. So, this issue was about finding a more appropriate place inside the code to place it. I think it never got tackled because no one from the community really brought up an issue like that indicating that this may not be even needed.

**Comment by samsucik** [comment]
@TyDunn what's your take on this? Do we wanna support use cases like those described by Daksh? cc @koaning because when I hear "training an NLU model in a jupyter code" I think of you 🧇
