### ISSUE TITLE
NLU comparison does not plot results with more than one run

### ISSUE THREAD

**Issue by TEGELB** [RasaHQ/rasa#5426]
**Rasa version**: 1.8.1

**Python version**: 3.7.5

**Operating system** (windows, osx, ...): Windows

**Issue**:
When running the comparison of different pipeline configurations with default settings out of a folder, as laid out [here](https://rasa.com/docs/rasa/user-guide/evaluating-models/#comparing-nlu-pipelines), the diagramm is not plotted and an error occurs. 
Error occurs when comparing two as well as six configurations.
All files are saved correctly up to that point.

No error occurs when the amount of runs is set to one manually.

**Error (including full traceback)**:
```
![grafik](https://user-images.githubusercontent.com/56721736/76779152-2ec5b980-67ab-11ea-92fb-73765fbdaefc.png)

```

**Command or request that led to error**:
```
rasa test nlu
```

**Comment by chkoss** [comment]
I already traced down that the following happens when running e.g. `rasa test nlu --runs 2`.

Here, `number_of_examples` is plotted vs. `mean`, where `mean` is an average over runs of what's in the file `output`:
https://github.com/RasaHQ/rasa/blob/master/rasa/test.py#L219

The problem is, the shapes don't match. Let’s call the value of `--runs` r and the number of percentages in `--percentages` p. Then `number_of_examples` has shape `(r*p,)`, the content of `output` has shape `(r, p)` and `mean` therefore has shape `(p,)`.

This is caused by how `number_of_examples` is determined in `compare_nlu`:
https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/test.py#L1413
This function simply appends all the values for each run and percentage into one 1D array of shape `(r*p,)`.

**Comment by melindaloubser1** [comment]
Just ran into this too - it works in 1.7, in case that helps

**Comment by m-vdb** [comment]
I was able to reproduce the issue using the doc here: https://rasa.com/docs/rasa/user-guide/testing-your-assistant/#comparing-nlu-pipelines and the right configuration files.
