### ISSUE TITLE
Pass along a location/context parameter used to select a response

### ISSUE THREAD

**Issue by cajoek** [RasaHQ/rasa#5442]
**Description of Problem**:

I have a Rasa bot running on my website where it guides the users around the site. This means that in some cases the same question should have different answers and it only depends on where on the site the user is currently.
I would like to be able to pass the location information to the chat bot and use it to select a response. The solution would have to be scalable because there are quite a lot of pages on my site.

See: https://forum.rasa.com/t/pass-along-users-current-location-on-website-as-a-paramter-to-rasa/25908

**Overview of the Solution**:

Maybe Retrieval Actions or Knowledge Base Actions could be passed a parameter that first selects a subset of possible responses.

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described in the docs
- [ ] Feature mentioned in the changlog
- [ ] A location/context parameter can be passed along with the request to the chat bot
- [ ] That parameter is considered when selecting a response

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @wochinge will get back to you about it soon! ✨

**Comment by akelad** [comment]
Hey @cajoek, I think you could do this by passing the page the user is on in the `metadata` field, and then dealing with that information in your custom action. You can read more about the metadata field [here](https://rasa.com/docs/rasa/user-guide/connectors/custom-connectors/#id1)

I'm going to close this issue, since it's more of a usage question than an issue. Feel free to tag me in your forum post if you have further questions
