### ISSUE TITLE
ease debugging of augmented stories

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#5610]
**Description of Problem**: There is a `-~~persist-nlu-data` option which saves the NLU data with the model. This request is for a `~~-persist-core-data` or similar option to save the core stories with the model. This would be useful for build workflows that store a release in a separate release artifacts store.

**Definition of Done**:

**Comment by wochinge** [comment]
@rgstephens Interesting idea! I see the goal and the usefulness, but I'm not sure sure if this is within the scope of Rasa Open Source. Whoever trains a model using Rasa X, has the training data themselves and they can store both input and output wherever and however they want. 

I do think it's in the scope of Rasa X and e.g. could be handled by Integrated Version Control. @TyDunn thoughts on this?

**Comment by akelad** [comment]
@wochinge we used to have `--dump-flattened-stories` as a flag, but then removed it (https://github.com/RasaHQ/rasa/commit/10b68fec364bdd02847ffae1a30b304d8992194a). As to why, I think it was because we told people to do it separately if they needed it? @tmbo ?

As for a use case, I definitely think there is a few (wherever it lives): 
1. knowing what data your model was trained on (to be honest that should probably be solved differently)
2. For debugging purposes - if your model is doing weird stuff, it's possible that story augmentation did something weird, so having your flattened stories is useful

**Comment by rgstephens** [comment]
What is the use case for `--persist-nlu-data`?

**Comment by ricwo** [comment]
@akelad @wochinge what's the status here?

**Comment by akelad** [comment]
@wochinge ?

**Comment by wochinge** [comment]
In my opinion we shouldn't do it and even think about removing `--persist-nlu-data`. I think both use cases you brought up should be solved differently

**Comment by akelad** [comment]
in what way should they be solved?

**Comment by wochinge** [comment]
> knowing what data your model was trained on (to be honest that should probably be solved differently)


Use Integrated Version Control or create the artifacts yourself. 

> For debugging purposes - if your model is doing weird stuff, it's possible that story augmentation did something weird, so having your flattened stories is useful

Should be less of an issue with rules and I'd image that a command like `rasa data stories dump --flat` would be nicer than to extract things from a zip.

**Comment by akelad** [comment]
yeah this is only something we should address for debugging purposes, agreed about the other use case. So it shouldn't be addressed for NLU data at all, but for stories we should have an alternative like the one you mentioned - I would leave this issue open, potentially renaming it

**Comment by mmmiitr** [comment]
@akelad currently is there a way to see augmented stories? 
I am currently using rasa:1.10.18-full with augmentation and would like to see what stories were added due to the augmentation flag, as my model is definitely behaving weird, I have requested help for the same [here](https://forum.rasa.com/t/wrong-utterance-story-predicted-second-time/37612)

**Comment by melindaloubser1** [comment]
Bumping this up again: It is really hard to debug checkpointed/ORd/augmented stories without this option. 

> I'd image that a command like rasa data stories dump --flat would be nicer than to extract things from a zip.

that would certainly help!

**Comment by melindaloubser1** [comment]
For anyone who wants to do this in the meantime, here's a script:

```
import asyncio
from rasa.core.training import load_data
from rasa.shared.core.domain import Domain


DOMAIN_PATH = "domain.yml"
DATA_PATH = "data/stories"
AUGMENTATION_FACTOR = 0
OUTPUT_PATH = "flattened_stories.yml"

domain = Domain.load(DOMAIN_PATH)

loop = asyncio.get_event_loop()
trackers = loop.run_until_complete(load_data(DATA_PATH, domain, augmentation_factor=AUGMENTATION_FACTOR))

for tracker in trackers:
    tracker.export_stories_to_file(OUTPUT_PATH)```

**Comment by melindaloubser1** [comment]
born of https://github.com/RasaHQ/rasa/issues/9473 - another example where dumping flattened stories is required while investigating a problem

**Comment by NareshDen** [comment]
This would help in debugging the stories.
