### ISSUE TITLE
Change automatic session behavior in Rasa shell

### ISSUE THREAD

**Issue by kevinthemself** [RasaHQ/rasa#5641]
**Description of Problem**:

**Original Problem:** As mentioned [here](https://forum.rasa.com/t/chatroom-let-the-bot-start-the-conversation/2738/13?u=nivek), it can be confusing to start `rasa shell` and not see the typical welcome messages you might see on channels that support simulating the bot starting the conversation.

**Update:** Documentation changes to address original issue above have already been separated from this issue in #5675.

**Current Issue:** current `rasa shell` behavior starts a session regardless if `/session_start` was sent (even though this behavior might be desirable in a deployed environment), which is not desirable, as that might incur unwanted side effects.

**Overview of the Solution**:

Prevent a session from being started and use temporary state until a session is explicitly started. This is similar to what `rasa shell nlu` does, which allows for you to test intent detection based on inputted phrases.

**Definition of Done**:

*   [ ] change shell behavior to only start a session when `/session_start` is explicitly sent

**Comment by lluchini** [comment]
I don't think it's necessary if your chat plugin/room sends the payload like 'greet' and you train RASA to respond adequately this feature is innocuous and possibly harmful.

I say harmful because a lot of developers use the session start to bill the use of the bot, and if it automatically starts a session I'll charge the client even if the users didn't use the bot.

At `rasa shell`  you just have to send the same payload that the plugin/room will send, and the behavior will be the same.

**Comment by ortsaCniveK** [comment]
Wouldn't you just handle being in a local/dev/staging environment in your action server to determine if you need to bill usage? If you're developing the bot locally without that check you're still billing you client. It's harmful insofar as you're using the session start to bill clients, which is also not an out-of-the-box use case for the session start action to begin with.

For new users of Rasa it's not intuitive to have to send that payload by default unless they read through the session configuration docs, and/or they might not be using a channel where they set up the session start interaction.

**Comment by lluchini** [comment]
The billing was only an example, who knows how many other uses will be broken changing this behavior?

> For new users of Rasa it's not intuitive to have to send that payload by default unless they read through the session configuration docs, and/or they might not be using a channel where they set up the session start the interaction.

I think this is necessary and implicit before start dealing with defaults actions. Perhaps an improvement in the documentation about the session start event would suffice.

**Comment by ortsaCniveK** [comment]
`action_session_start` is still called for the first user message in `rasa shell`; the suggestion simply removes the need to explicitly send the `/session_start` message.

Overriding any default action leaves the onus of side effects on the developers and the default `action_session_start` simply copies over slot values, so I'm still failing to understand how this is suggestion is harmful for anyone that uses `rasa shell`.

Agreed that documentation needs to be better for these cases.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by melindaloubser1** [comment]
I agree with @lluchini  that this would be best handled by updating the documentation. An issue for that is open https://github.com/RasaHQ/rasa/issues/5675

**Comment by ortsaCniveK** [comment]
What if instead of automatically starting a session, session behavior is disabled unless they specifically send the `/session_start` message?  According to the docs the purpose of the `rasa shell` command is:
To start a chat session with your assistant on the command line.

**Comment by ortsaCniveK** [comment]
A documentation update is fine, but I still think that a session should be started by default, since the docs on `rasa shell` state:

> # Talk to your assistant
> [To start a chat session with your assistant on the command line, run:](https://rasa.com/docs/rasa/user-guide/command-line-interface/#talk-to-your-assistant)
> ...

I think that the mention of a chat session is key, so to avoid confusing new users those docs need to be updated as well.

However, if we wanted to replicate the same behavior as `rasa shell nlu`, which is strictly to test intent detection for specified phrases, we should just disable session behavior on user messages (i.e. prevent `action_session_start` from running on the first user message), unless they send a `/session_start` message to explicitly start a session.  That would prevent unwanted sessions from being started, while still providing that as an option.

Curious to hear your thoughts on that, @lluchini @melindaloubser1

**Comment by lluchini** [comment]
Hello @ortsaCniveK 

> However, if we wanted to replicate the same behavior as rasa shell NLU, which is strictly to test intent detection for specified phrases, we should just disable session behavior on user messages (i.e. prevent action_session_start from running on the first user message), unless they send a /session_start message to explicitly start a session. That would prevent unwanted sessions from being started, while still providing that as an option.

This is an example of one more change that will need to be done if we change the behavior, how many others will be needed to make it consistent? (I don't know, and that's the problem to me)

As I mentioned before, many implementations already made would need to be revised. In my specific case, I would change the logic drastically, once I bill the client by session, and the session starts only when the user interacts with the bot, and when I want to do it automatically I just send a payload automatically after the frontend was loaded. 

At the shell, I just send a payload same way I would do on the frontend. This way I think that's even more informative, so the developer has to know what happens when happens and who triggers it.

So, until now we already have 3 tasks to be done beyond the improvement itself:

-  Update documentation with the new behavior (on event and shell cases when will it work automatically);
-  Update tests with new conditions (as you described before); and
-  All users of the event review their implementations.

As I mentioned, I don't know how many other items will popup, so IMHO I don't think it's worth it.

**Comment by ortsaCniveK** [comment]
I see your point about sending the payload as being more informative, as long as we're communicating that to new users (already separated to #5675). I have no problem with the current behavior, I'm just trying make `rasa shell` more intuitive.

Let me reiterate to be clear, since I think my suggestion is being misunderstood: 

Disable *automatic* session behavior in `rasa shell` **unless `/session_start` is explicitly sent**.  This means that when you run `rasa shell`, `action_session_start` is **not** run automatically after the first user message (which is the current behavior and not desirable as you've described yourself, @lluchini).  It would be akin to sending a request to [`/model/predict`](https://rasa.com/docs/rasa/api/http-api/#operation/predictModelAction) until a session is started.  This would be in line with the documentation changes.

**Comment by melindaloubser1** [comment]
```
Disable automatic session behavior in rasa shell unless /session_start is explicitly sent. This means that when you run rasa shell, action_session_start is not run automatically after the first user message
```
I see your point with that. Whether a change is made or not, the docs should definitely note the behaviour.

**Comment by saraswathykrk** [comment]
Can you please let me know if the above solution works for rasa x too?

**Comment by cryoff** [comment]
Is there any clear way to initiate the interaction by bot first (at the current 3.0 stage of Rasa HQ)?

**Comment by humanlost** [comment]
> 

+1

**Comment by humanlost** [comment]
> Is there any clear way to initiate the interaction by bot first (at the current 3.0 stage of Rasa HQ)?

+1

**Comment by melindaloubser1** [comment]
>Is there any clear way to initiate the interaction by bot first (at the current 3.0 stage of Rasa HQ)?

 Is this a question about `rasa shell` behaviour, or in general about how to have the bot initiate the interaction on any channel?
 
 If it is the former, can you clarify how it relates to `rasa shell` specifically?
 
 If it is the latter, please see the instructions on [customizing `action_session_start`](https://rasa.com/docs/rasa/default-actions#customization) and post follow up questions on [the forum](https://forum.rasa.com/) since it is not related to this issue.

**Comment by humanlost** [comment]
> > Is there any clear way to initiate the interaction by bot first (at the current 3.0 stage of Rasa HQ)?
> 
> Is this a question about `rasa shell` behaviour, or in general about how to have the bot initiate the interaction on any channel?
> 
> If it is the former, can you clarify how it relates to `rasa shell` specifically?
> 
> If it is the latter, please see the instructions on [customizing `action_session_start`](https://rasa.com/docs/rasa/default-actions#customization) and post follow up questions on [the forum](https://forum.rasa.com/) since it is not related to this issue.

For me, my problem is about `rasa shell`. I use `dispatcher.utter_message` to show any text like "welcome" in `action_session_start`, but it just print "welcome" text after my first input, not the beginning.

**Comment by melindaloubser1** [comment]
Gotcha, that would require the opposite of what @kevinthemself is suggesting: 
> Disable automatic session behavior in rasa shell unless /session_start is explicitly sent. This means that when you run rasa shell, action_session_start is not run automatically after the first user message

**Comment by humanlost** [comment]
> Gotcha, that would require the opposite of what @kevinthemself is suggesting:
> 
> > Disable automatic session behavior in rasa shell unless /session_start is explicitly sent. This means that when you run rasa shell, action_session_start is not run automatically after the first user message

Maybe set a parameter of `action_session_start` to control this?

**Comment by cryoff** [comment]
@melindaloubser1 yes, I also refer to the default behavior of `rasa shell`. Probably, the parameter to control the behavior is the better option.
