### ISSUE TITLE
Add roles and groups to entities extracted by duckling

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5716]
**Description of Problem**: Entity roles and groups are currently only support by `CRFEntityExtractor` and `DIETClassifier`, e.g. components that extract custom entities. It might be helpful to add support for `SpacyEntityExtractor` and `DucklingHTTPExtractor` as well. If you are building a larger bot, you might have lots of different entities that are "number". Example:

 I need a table for 4 with one seat for a toddler

**Overview of the Solution**: We don't have a clear solution in mind. One idea was to split off the role classification part from e.g. the `CRFEntityExtractor` and then wrapping that around the duckling extractor.

However, the more challenging part is the annotation of the training data. For `SpacyEntityExtractor` and `DucklingHTTPExtractor` you don't need to annotate anything right now. But if you want to learn specific roles for e.g. a "number", we need some kind of training data. One idea was to just annotate tokens in the training data with roles. For example:

 The car has <span class="error">[4]</span>

 {"role": "wheel-count"} 

 wheels and <span class="error">[2]</span>

 {"role": "door-count"} 

 doors

**Comment by edubrigham** [comment]
Hi this exactly the issue I'm trying to solve right now. Can i use CRFEntityExtractor to extract "related" numbers based on "entity groups" by having training data as follows?

- can I have [2]{"entity": "itemQty", "group": "1"} [beer]{"entity": "itemName", "group": "1"}  [1]{"entity": "itemQty", "group": "2"} [water]{"entity": "itemName", "group": "2"} and [4]{"entity": "itemQty", "group": "3"} [mojito]{"entity": "itemName", "group": "3"} 

And what happens if the user uses cardinals instead of numbers? usually this is done by DucklingHTTPExtractor, which does not read "groups" or "roles"

**Comment by pawan-datascience** [comment]
Any updates on this?
Makes sense to annotate tokens in the training data with roles:
 
`The car has [4]{"role": "wheel-count"} wheels and [2]{"role": "door-count"} doors`

**Comment by JEM-Mosig** [comment]
It should be easier to add this support after resolving [this issue](https://github.com/RasaHQ/rasa/issues/7173)
