### ISSUE TITLE
Py3.8+ / TensorFlow 2.2 Support

### ISSUE THREAD

**Issue by clungzta** [RasaHQ/rasa#5822]
**Description of Problem**:
I'm using the default python 3.8.2 on a fresh install of Ubuntu 20.04.

When I proceed to install rasa (`pip3 install rasa`) I get:
```
ERROR: Could not find a version that satisfies the requirement tensorflow<2.2,>=2.1 (from rasa) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow<2.2,>=2.1 (from rasa)
```
and

```
ERROR: Could not find a version that satisfies the requirement tensorflow-addons<0.8.0,>=0.7.1 (from rasa) (from versions: none)
ERROR: No matching distribution found for tensorflow-addons<0.8.0,>=0.7.1 (from rasa)
```

There appears to be a version mismatch between rasa support and available tensorflow releases on py3.8+ (similar to #5722?).

I did made a quick and dirty attempt to manually override the TensorFlow version constraint to 2.2.0. While that did get the rasa install completed, it introduced runtime errors due to incompatibility:
```
ModuleNotFoundError: No module named 'tensorflow_core'
```

**Overview of the Solution**:
It would be excellent if rasa could support Tensorflow 2.2.0 to eliminate the mismatch with available py3.8+ TensorFlow releases.

**Definition of Done**:
I'd simply like to be able to follow the quick installation procedure as indicated (`pip3 install rasa`) on my Ubuntu 20.04 system (python 3.8.2) without running into dependency issues.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by melindaloubser1** [comment]
@clungzta , as per the [installation requirements], Rasa requires Python 3.6 or 3.7. That might change in the future, but it's really not a mismatch issue since 3.8 is not supported

**Comment by ortsaCniveK** [comment]
@melindaloubser1 something I realized might be confusing is that the `README.md` has the 3.8 pin, but it's not fully compatible with that Python version.

Just as well in [`pyproject.toml`](https://github.com/RasaHQ/rasa/blob/563f06da7e5a84546c3e2bec661a28f4a3880fdd/pyproject.toml#L67) we might want to specify the compatible versions of Python (not just `python = ^3.6`, which in `poetry` [would include python 3.8+](https://python-poetry.org/docs/dependency-specification/#caret-requirements)

**Comment by melindaloubser1** [comment]
That's a good point!

**Comment by joselpart** [comment]
Hi, I also had the issue of not finding a compatible version of tensorflow-addons on Ubuntu 20.04 with Python 3.8.2. The poetry.lock file used by the published rasa package specifies tensorflow-addons<0.8.0,>=0.7.1 but the one available for this python version is 0.10.0. The way I went about this issue was to install rasa from source, since I didn't want to fiddle with multiple versions of python... The procedure is as follows:

1- Clone the rasa repository:

```
git clone https://github.com/RasaHQ/rasa.git
```

2- Create a virtual environment where you are going to install rasa and its dependencies, and source it.

3- Install [poetry](https://python-poetry.org/docs/), which is what rasa uses for dependency management, and source it:

```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

source $HOME/.poetry/env
```

4- Within the rasa repository folder, install rasa dependencies with the command below. There are two ways you can do this. You can go ahead with the poetry.lock file commited in the rasa repository (doing ```poetry install```) or do what I did which is update all dependencies and regenerate the poetry.lock by doing:

```
poetry update
```

5- Then you can install rasa:

```
make install
```
(alternatively, if you delete the ```poetry.lock``` file, you can skip step 4 since the ```make install``` command will basically update and install the dependencies and regenerate the locked file from the versions listed in the ```pyproject.toml``` file, effectively doing everything in one step.)

6- After doing this, there were still a few dependencies missing. You can install them like this:

```
pip install zipp spacy
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en
```
Finally, I will point out that I have CUDA 11 installed with cudnn 8.0.2. I was expecting Tensorflow to complain since it is supposed to support up to CUDA 10.1 (according to several threads online) but it seems to work just fine... I just run the example in the tutorial so far but I'll update if I have any issues in the future.

**Comment by nirajmalpani** [comment]
Does rasa support tensorflow 2.2??

**Comment by gamersalpha** [comment]
I can't install it on ubuntu 20.04 ?????
Tensorflow 2.2 is not supported ?

wHy  ???

**Comment by melindaloubser1** [comment]
The place to check dependencies is [here](https://github.com/RasaHQ/rasa/blob/c71c18c7b41694c5b0d1af3a9e71a8001be84371/pyproject.toml#L115) - for current latest (rasa==2.2.5), that means tensorflow >=2.3.0 < 1.4.0. (see https://python-poetry.org/docs/dependency-specification/) You may still be able to use rasa with other versions of tensorflow installed, but don't be surprised if you run into issues - the dependencies are given for a reason.

**Comment by melindaloubser1** [comment]
Keep in mind tensorflow has CPU and GPU versions, and if you have a GPU version, it needs to be compatible with your CUDA version, which is separate from  Rasa (see the last part of  [joselpart's comment above](https://github.com/RasaHQ/rasa/issues/5822#issuecomment-665902432).
