### ISSUE TITLE
Can't take user input while having fallback policy how to solve this issue

### ISSUE THREAD

**Issue by Jainu-s** [RasaHQ/rasa#5871]
I created a form and taking user input as name, email and when user enters the input then rasa shows custom fallback policy message like "I cannot understand what you are telling". This is caused just because the user name is not in trained intents. How to solve this issue.

**Comment by ortsaCniveK** [comment]
This sounds like something work asking about in the [forum](https://forum.rasa.com)

**Comment by vishnupriyavr** [comment]
Hi @Jainu-s , summarising from the solution as given in the forum below,as suggested by @ortsaCniveK , since your issue seems to be the same : 
`did you annotate your username and password as entities? Otherwise you should use from_text slot mapping. See docs and linked tutorial there for details: Forms 48`. 
Please go through the link given below for further details:
https://forum.rasa.com/t/how-to-create-rasa-form/15917/4

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tttthomasssss will get back to you about it soon! ✨

**Comment by joejuzl** [comment]
Closing as this is a question rather than an issue. Please post in the forum if you need any further help.
