### ISSUE TITLE
Update action server without redeploying K8 cluster every time

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#5924]
We are running Rasa X on a Kubernetes cluster. We know that the external action server can be added via the environment variable ACTION_SERVER_TAG but how do we continually update Rasa when we make changes to the action server? Do we have to manually go into the kubernetes cluster every time, change the environment variable and redeploy those changes to the k8 cluster? It doesnt seem manageable. We can continually make changes to the core/model using the UI or github and we would like a similar continuous development solution for the action server since we make changes to the action server almost as often as we make changes to the core.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tttthomasssss will get back to you about it soon! ✨

**Comment by tczekajlo** [comment]
I think I don't understand the issue here.

You mention the `ACTION_SERVER_TAG`, so I'm guessing you're using the `get-rasa-x.sh` script? (the script uses the rasa-x helm chart)

If you use a Kubernetes cluster and you apply changes to your current deployment you should use helm directly, that gives you all options to update your deployment.

**Comment by mprazz** [comment]
Any updates here @tatianafrank @tczekajlo ? Is this an actual issue or can it be closed?

**Comment by tczekajlo** [comment]
I'm closing it due to a lack of information.
