### ISSUE TITLE
Rename the `form:` event in stories for 2.0

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#6279]
See discussion on Notion [here](https://www.notion.so/rasa/Feedback-on-2-0-4574eaacc0764967ac0b8b82fbc72904#0b5fd7f8b76e4186a1a21c9d821a4958).

A Form is now just a special version of the more general LoopAction, this event in the stories should be renamed to make it clearer what's happening. The current best suggestion is: `active_loop` (open to other suggestions if there are any)

Old version:
![image](https://user-images.githubusercontent.com/32450038/88528460-f22e8800-cffe-11ea-9c80-00f12f223864.png)

New version:
![image](https://user-images.githubusercontent.com/32450038/88528411-e773f300-cffe-11ea-9aeb-16dff3431a8d.png)

**Comment by akelad** [comment]
@TyDunn this should probably also be put in planned for this sprint

**Comment by wochinge** [comment]
@akelad @chkoss Should `form:` still work (with a deprecation warning)? I'm a bit torn as the YAML syntax is completely new on the one hand, but users might expect it to work when coming from the markdown format. Due to UX it slightly lean towards  keeping support for `form:` combined with a deprecation warning

**Comment by chkoss** [comment]
I would find it a bit funny to include something deprecated already in the first release of 2.0. The `form:` key like this was never part of any "real" release, so I'd lean towards not supporting it if we don't want to encourage its usage.

If we expect users to "accidentally" use it because of prior expectations, we could also add a descriptive error message that tells them to use `active_loop` instead.

**Comment by akelad** [comment]
yeah i would say it shouldn't work, it's not really the same. I was honestly super confused what the `form:` thing was at first in the yaml format, and i've written 1000 form stories in my life :D so i don't think users will be confused

**Comment by wochinge** [comment]
ok, then let's merge 👍
