### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by rudigiesler** [RasaHQ/rasa#6319]
**Description of Problem**: We want to be able to have metrics (response time, traffic load, error rate, most used endpoints, etc) on our Rasa bot. I would like to suggest having a metrics endpoint that exports prometheus metrics.

**Overview of the Solution**: I see that there is a prometheus sanic library that we could use: [https://github.com/dkruchinin/sanic-prometheus](https://github.com/dkruchinin/sanic-prometheus) , which should give us a bunch of metrics for "free" (without having to instrument them manually.

**Examples**: [https://prometheus.io/docs/introduction/overview/](https://prometheus.io/docs/introduction/overview/) [https://github.com/dkruchinin/sanic-prometheus](https://github.com/dkruchinin/sanic-prometheus)

**Definition of Done**:

*   [ ] Discussion on whether this is something we want to do
*   [ ] Add sanic prometheus library
*   [ ] Use library to add endpoint

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rgstephens will get back to you about it soon! ✨

**Comment by kaustuk** [comment]
@wochinge Any updates on it? 

Because current I don't think rasa provide any metrics or anything else which can help/provide information on what's going on with rasa as a system. Correct me if I am missing something?  Not have basic metrics or not knowing what's going on with production system is scary and risky :). This feature will be more essential as more and more bot build on top of rasa will be deployed on production.


Let me know what do you think? I would be happy to contribute/help in implementing this feature.

**Comment by wochinge** [comment]
@kaustuk I full agree. As far as I know @rgstephens is currently working on related things. He'd be the best person to give you input on it.

**Comment by rgstephens** [comment]
I have an example branch with OpenTracing but not metrics. @kaustuk or @rudigiesler would either of you consider submitting a PR with sanic-prometheus?

**Comment by kaustuk** [comment]
Hi @rgstephens thanks for the reply. Yeah sure I would like to submit PR with Sanic-prometheus.


Just wanted some pointers around what should this PR consist of. Just integrating with Sanic-prometheus and extracting default metrics is enough for now? Or it should consist of custom metrics and other thing as well?

**Comment by rudigiesler** [comment]
I think the basic metrics will be a great start, since I'm not sure what custom metrics we would want? Probably a separate discussion/PR.

Just to note, we should probably also add metrics to the SDK https://github.com/RasaHQ/rasa-sdk/ , so that custom action servers can also be monitored.

**Comment by kaustuk** [comment]
Hi @rgstephens @rudigiesler, Sorry I couldn't started working on this earlier. Need to some pointer/help on where we integrate Sanic-prometheus. Here is where I am thinking.


**Purposed solution:**

* Before this line we will be adding/integrating Sanic-prometheus https://github.com/RasaHQ/rasa/blob/493e520e1ba36c1d03a16201cdb176ccf923c467/rasa/core/run.py#L220

* From behaviour point, since the prometheus-client support multi-process monitoring if and only if `prometheus_multiproc_dir` environment variable exist otherwise it will not monitor metrics across multiple processes. So was think of added 1 more check here if this environment variable is present then only use whatever is provided by user otherwise use default value of no of workers (1) . https://github.com/RasaHQ/rasa/blob/493e520e1ba36c1d03a16201cdb176ccf923c467/rasa/core/utils.py#L504 
* Also whatever directory path user has provided we need to create it if doesn't exist and delete all the previous file present inside the folder before starting it. As mentioned [here](https://github.com/dkruchinin/sanic-prometheus#multiprocess-mode). So this new function(handling this cleanup and creation part) would be called from above point once condition for environment variable present satisfied





what do you think? is above approach fine? I will raise PR according.

**Comment by rudigiesler** [comment]
@kaustuk 
1. Yes that looks to be a good place to add it to me
2. Looks good to me. I'm assuming here that if `num_workers>1`, and `prometheus_multiproc_dir` is not set, then we'll log a descriptive error telling the user how to fix it, and then only run 1 worker?
3. I'm worried about randomly deleting files in a directory. What about instead doing the same as the env var, logging a descriptive error for the user, and then running a single worker, if the directory has files in it? If the directory doesn't exist, I think we can create it for the user, provided that we have correct filesystem permissions.

**Comment by bshivkumar15** [comment]
Do we have any update on this feature ? It would be great to have rasa metrics exposed

**Comment by bshivkumar15** [comment]
@rudigiesler @kaustuk Do you think the below can be used?

https://github.com/dkruchinin/sanic-prometheus

**Comment by rudigiesler** [comment]
@bshivkumar15 Yes, I think so. That's the library I suggested in the original post: https://github.com/RasaHQ/rasa/issues/6319#issue-671896797

**Comment by rgstephens** [comment]
I built an [image](https://hub.docker.com/r/stephens/rasa-otel) of `2.8.1` with sanic-prometheus and also with OpenTracing/Jaeger. See the image readme for a description of how to enable the `/metrics` endpoint in your `endpoints.yml`.

**Comment by DSigmund** [comment]
I like the metrics! can we expect this to land in the "official" rasa image?

**Comment by rgstephens** [comment]
@TyDunn is the best person to ask about an official release.

**Comment by TyDunn** [comment]
As you can learn about at the top of the repo README [here](https://github.com/RasaHQ/rasa/blob/main/README.md#rasa-open-source), we are no longer accepting enhancements for Rasa Open Source 2.8.x. All improvements like this will need to target Rasa Open Source 3.x. We are focused on delivering 3.0 at the moment, but `tracing + metrics` is high on the roadmap after this major release
