### ISSUE TITLE
Rasa --version now breaks on Windows

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#6496]
This issue was originally mentioned [here](https://forum.rasa.com/t/issues-in-installing-rasa-alpha-version-2-0-0-a2-in-windows-setup-with-python-version-3-7-9/33041). 

**Rasa version**:
1.10 onward 

**Rasa SDK version** (if used & relevant):
1.10 onward 

**Rasa X version** (if used & relevant):

**Python version**:
3.7 

**Operating system** (windows, osx, ...):
Windows

**Issue**:

A few months ago I changed the `rasa --version` command to also show more information like operating system and python version. PR [here](https://github.com/RasaHQ/rasa/pull/5726). The goal was to make it easier for folks to list all relevant debugging information in one go. It seems however, that it breaks on windows because of [this line](https://github.com/RasaHQ/rasa/blob/2.0_format_docs/rasa/__main__.py#L71) of code: 

```
python_version, os_info = sys.version.split("\n")
```

On a non-windows system `sys.version` returns two lines of text. It seems that on Windows 10 it lists a single line and it is breaking the `rasa --version` call. We now get a `ValueError: Not Enough Values to Unpack`.

**Comment by martinavalogia** [comment]
The version of Windows I use is Microsoft Windows build 1809 and this Value error I get that after installation of Rasa2.0.0a2 and after checking to see if the installation has been done for the corresponding version.Instead of getting the version number Rasa2.0.0.a2 I get this value error ! The other thing I faced was incompatility issues for tensor flow. I ve got the below results after giving rasa init.I ve been able to train and talk to my moodbot without any trouble

![image](https://user-images.githubusercontent.com/19143859/91447095-e819d680-e895-11ea-9660-c2afbf704d3f.png)

![image](https://user-images.githubusercontent.com/19143859/91447130-f10aa800-e895-11ea-9d64-f8f250791760.png)

![image](https://user-images.githubusercontent.com/19143859/91447155-f9fb7980-e895-11ea-8895-5def3beaea64.png)

![image](https://user-images.githubusercontent.com/19143859/91447171-ff58c400-e895-11ea-8604-961d5b829067.png)

![image](https://user-images.githubusercontent.com/19143859/91447192-067fd200-e896-11ea-853c-0b85c82eb7f2.png)

![image](https://user-images.githubusercontent.com/19143859/91447233-13042a80-e896-11ea-8f84-2a0acddf4c27.png)
