### ISSUE TITLE
Improve documentation on writing a custom channel

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#6626]
Inspired by this issue: https://github.com/RasaHQ/rasa/issues/6519

We should improve the custom connector page to make it clearer what your custom channel needs to implement and how to reference it from other things, e.g. channel-specific response variations, the `?output_channel` query parameter, etc.

**Comment by mlkorra** [comment]
HI any update,regarding the documentation? I am having trouble as a beginner to understand the custom connectors.

**Comment by stefanvantchev** [comment]
FYI ... this has not been resolved - the documentation remains the same, which has caused us to also spend quite some time.
https://rasa.com/docs/rasa/connectors/custom-connectors#the-name-method

**Comment by melindaloubser1** [comment]
@stefanvantchev you can see the diff here: https://github.com/RasaHQ/rasa/pull/7647/files
This is reflected on the current docs. 
Not sure what you mean by 
>the documentation remains the same
?

**Comment by stefanvantchev** [comment]
Well, since this ticket is related (inspired - I like that word) by https://github.com/RasaHQ/rasa/issues/6519 .... 

And 6519 specifically talks about: https://github.com/RasaHQ/rasa/issues/6519#issuecomment-689716808

And if you look at the content of the page https://rasa.com/docs/rasa/connectors/custom-connectors/ 

you will see the python scripts aren't quite updated:

`
from rasa.core.channels.channel import InputChannel

class MyIO(InputChannel):
    def name() -> Text:
        """Name of your custom channel."""
        return "myio"
`

**Comment by melindaloubser1** [comment]
Ah I see, good catch  - would you like to open a PR to fix it?

**Comment by stefanvantchev** [comment]
It's up to you guys - all I wanted to do is bring it your attention :)
