### ISSUE TITLE
Add list of unmodified predicted tags to message for evaluation

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#6647]
**Description of Problem**: Entity tags are might be updated after the model prediction according to some heuristics. The tags are converted into entity objects and stored in the message object. During testing the entity objects are converted to a list of tags again in order to calculate our testing metrics. As we don't have access to the originally predicted tags in our evaluation methods anymore, we cannot easily evaluate how good our heuristics in updating the tags are.

**Overview of the Solution**: Add the list of predicted tags (not updated and updated) to the message so that those can be used during our evaluation methods.

We need to discuss how much effort this is and if it is worse it.

**Comment by samsucik** [comment]
@Ghostvv you might have more context on this one: This is basically a research enabler, right? Did we at any point discuss/consider trying different heuristics (which could be compared once this issue is done)? I'm trying to understand what the potential of this issue is, especially given that we're not currently focusing much on improving entities (beyond bringing them to TED).

**Comment by Ghostvv** [comment]
this issue describes that current output of rasa test is "fake" in some sense, and hides the truth of what ML algorithms actually classify. I wouldn't call it enabler, rather things that should be done the correct way

**Comment by Ghostvv** [comment]
@aeshky are you working on it? should it be moved to `in progress`?

**Comment by aeshky** [comment]
@Ghostvv I assinged myself to this issue but then started working on a different one. Should I unassign myself for now?
