### ISSUE TITLE
Number of CPU Cores Used In Model API

### ISSUE THREAD

**Issue by sahinbatmaz** [RasaHQ/rasa#6678]
**Rasa version**: 1.10.10

**Python version**: 3.7

**Operating system**: Ubuntu 16.04

**Description of Problem**:
I train an nlu-only model and serve the model with 'rasa run' command.
I send requests to the api and monitor the cpu usage.
I have 8 cpu cores but it seems like the usage is limited to 4 cpu cores. 
I tried to set environment variables SANIC_WORKERS, TF_INTER_OP_PARALLELISM_THREADS and TF_INTRA_OP_PARALLELISM_THREADS to 8. But the result is the same, the model does not use more than 4 cpu cores.

How can i increase de cpu usage in the api of 'rasa run' command?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @degiz will get back to you about it soon! ✨

**Comment by degiz** [comment]
Hey @sahinbatmaz 

You've correctly spotted the `TF_INTER_OP_PARALLELISM_THREADS` and `TF_INTRA_OP_PARALLELISM_THREADS` variables, since Rasa Open Source uses TensorFlow. 

I can only assume that TF itself limits itself to `4` threads, since your `8` cores are actually `4`, but each is split into 2 virtual cores.

You can try to set both variables to `0`, it will tell TF to pick up the best available configuration.
