### ISSUE TITLE
incorporate removed content from the docs

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#6767]
A few pieces of the old docs were removed because they didn't have a natural place in the new docs. We should consider where this information should go, if it still needs to be available. This includes: 

- the [core](https://github.com/RasaHQ/rasa/blob/1.10.14/docs/core/about.rst) and [nlu](https://github.com/RasaHQ/rasa/blob/1.10.14/docs/nlu/about.rst) "about" pages --> incorporate into rasa open source landing page
- [architecture](https://github.com/RasaHQ/rasa/blob/1.10.14/docs/user-guide/architecture.rst) page --> this probably needs to be fleshed out -- not only architecture of a model and how it integrates with a user, but also the architecture of a deployed rasa instance (with e.g. tracker store and optional lock store + event broker) 
- [using nlu only](https://github.com/RasaHQ/rasa/blob/1.10.14/docs/nlu/using-nlu-only.rst): not sure about this one
- [language support](https://github.com/RasaHQ/rasa/blob/1.10.14/docs/nlu/language-support.rst) -- seems important, not sure where it goes. may be covered by marketing's FAQ page, but that's not the entrypoint for devs

**Comment by rgstephens** [comment]
Ben & I met. Will:

- Consolidate arch, core & nlu and put in the Intro page (but could move to a new Architecture > Intro if more detailed
- NLU only under Architecture
- Language Support add as a page under Config. Add a link to this page under Config > Overview

**Comment by m-vdb** [comment]
I found out some pages to which we link to but are not in the sidebar. I would assume we want to add them to the sidebar? Also, if this is something deemed important, we could add a unit test (under `tests/docs/`) that checks for this, so that we can detect such issues.

In https://rasa.com/docs/rasa/how-to-deploy#rasa-open-source-only-deployment ⬇️ 
<img width="688" alt="Screenshot 2020-09-29 at 09 22 16" src="https://user-images.githubusercontent.com/1931615/94526286-9ae2a900-0235-11eb-9486-b664c90a4598.png">

**Comment by b-quachtran** [comment]
@erohmensing With the supervised_embeddings pipeline deprecated, do we have any recommendations on what pipeline to use for training a model in any language?
