### ISSUE TITLE
Response containing buttons sent on Whatsapp shows both text and payload together

### ISSUE THREAD

**Issue by askushwah** [RasaHQ/rasa#6773]
**Description of Problem**:
 
The response looks clumsy and the payload should not be visible to the end user.

**Overview of the Solution**:
 
When the Twilio connector sends the response, check if the response contains "(/" and if it does, trim the response from the position where "(/" started till the end. This is safe to do because the payload is always attached at the end of the string after the text.

**Examples** (if relevant):

For instance, if the buttons are Outside and Inside with respective payload, the payload is showed along with the text
Where would you like to dine?
1. Outside (/outside)
2. Inside (/inside)

**Blockers** (if relevant):

User experience

**Definition of Done**:

Writing a code that would remove the payload before sending it to the platform.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨

**Comment by erohmensing** [comment]
You're right, the twilio connector doesn't have a `send_buttons` response, which is why it prints the same way as in `rasa shell`.

Does whatsapp support buttons natively? If so, I'm not sure how twilio sends them through to Whatsapp. Anything we can send needs to be sendable through [twilio-python](https://github.com/twilio/twilio-python). As far as i can see from their documentation, they only support sending plain SMS when it comes to messaging.

**Comment by erohmensing** [comment]
If you would just like the payloads removed, then you probably shouldn't be using buttons, Especially because users might try to respond with `1` or `2`. Consider rephrasing your response to "Would you like to dine inside or outside?"

**Comment by workaya-samarth** [comment]
You are right but when we deploy the same bot to different platforms (like slack and WhatsApp) where the buttons work fine on slack but because WhatsApp does not support buttons, it just shows the payload attached to the text which is aesthetically not appealing and should not be visible to the end-user.

**Comment by askushwah** [comment]
You are right but when we deploy the same bot to different platforms (like slack and WhatsApp) where the buttons work fine on slack but because WhatsApp does not support buttons, it just shows the payload attached to the text which is aesthetically not appealing and should not be visible to the end-user.

**Comment by erohmensing** [comment]
If one of your channels supports buttons and another does not, I would recommend using [Channel-specific response variations](https://rasa.com/docs/rasa/responses#channel-specific-response-variations).

**Comment by askushwah** [comment]
Seems like a viable alternative. Will close the discussion,

**Comment by digitalWestie** [comment]
For various reasons I won't go into, I'm not able to use channel specific responses. I have a custom channel (inheriting from the twilio channel classes), with its own [send_text_with_buttons](https://github.com/RasaHQ/rasa/blob/ea8eda23f5c68256080faa99d31e08b07b2a35da/rasa/core/channels/channel.py#L271) function. This calls a custom `button_to_string` function that formats the button text without payload: 

```
def button_to_string(button: Dict[Text, Any], idx: int = 0) -> Text:
    """Create a string representation of a button."""
    title = button.pop("title", "")
    if title == "" and "payload" in button:
        title = button.pop("payload")
    button_string = "{idx}: {title}".format(idx=idx + 1, title=title)
    return button_string
```
