### ISSUE TITLE
add possibility to define optional slots for forms

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#6939]
we could add `optional` key when define slot mappings in the domain, so that slot_mappings for extra slots could be defined, but the form shouldn't ask these slots

**Comment by domsammut** [comment]
Agreed. This is a pretty big regression from the forms in 1.0. With the move to yaml structure, this forces you to move into python and add custom code to perform slot mappings for anything that is either optional or conditional. Previously you could map intents/entities/text to any slots regardless of if they were required, optional or conditional:

```python
def slot_mappings(self) -> Dict[Text, Union[Dict, List[Dict]]]:
    return {
        'test_slot': [
            self.from_intent(intent='test_intent', value=True)
            self.from_entity(entity='test_entity', value=True),
            self.from_text()
        ]
    }
```

**Comment by rgstephens** [comment]
@m-vdb Where was this feature added? I haven't noticed anything new that addresses the comment from @domsammut or the original idea of an `optional` keyword in the domain.

**Comment by rgstephens** [comment]
Optional slots are a common use case and request from users. It would be nice to specify a condition associated with a slot to save writing python in simple cases.

**Comment by m-vdb** [comment]
what part of your use case isn't possible today with the [current Global Slot mappings functionality](https://rasa.com/docs/rasa/domain/#slot-mappings)?

**Comment by totalhack** [comment]
Hey there, I am newer to Rasa and was curious about the same thing. I took a look at the docs @m-vdb linked to but it's unclear how it would be accomplished with that. Perhaps you could provide a simple example of how you think optional slots are possible with the functionality there?

**Comment by rgstephens** [comment]
@totalhack You use the `required_slots` method which is documented under [dynamic form behavior](https://rasa.com/docs/rasa/forms/#dynamic-form-behavior).

**Comment by totalhack** [comment]
Thanks @rgstephens, that's helpful. 

So it seems there is no way to do this directly in the yaml files, even for simple cases, correct?

Also in those examples, aren't you really just dynamically adding another *required* slot, rather than truly having an optional slot? Is there some other way to do the latter that I missed? Basically have a form pick up and fill a slot if the user happened to also provide that information?

**Comment by rgstephens** [comment]
> So it seems there is no way to do this directly in the yaml files, even for simple cases, correct?

Correct, that's what this issue is for and why I'd like it to stay open.

> Also in those examples, aren't you really just dynamically adding another required slot, rather than truly having an optional slot?

It's entirely up to you. The most common place I've used it is when the value of `slot_1` and `slot_2` dictate the requirement to prompt for other slots. It could also be that a form accesses a DB or API that dictates requesting additional information from the user. There may be no other slot to request.

**Comment by Mhdi-kr** [comment]
I've observed that `extract_<slot_name>` and `validate_<slot_name>` methods defined inside a `FormValidationAction` subclass DOES NOT execute for non-required form slots. I reckon using optional form slots can let us run those kinds of validations inside a form context.
