### ISSUE TITLE
'Edit this page' links to wrong url

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#7011]
Due to the way the docs are deployed and versioned, the "edit this page" from `[https://rasa.com/docs/rasa/installation](https://rasa.com/docs/rasa/installation)` goes to `[https://github.com/rasahq/rasa/edit/master/docs/versioned_docs/version-2.0.x/installation.mdx](https://github.com/rasahq/rasa/edit/master/docs/versioned_docs/version-2.0.x/installation.mdx)`. We'd like it to go to `[https://github.com/RasaHQ/rasa/blob/master/docs/docs/installation.mdx](https://github.com/RasaHQ/rasa/blob/master/docs/docs/installation.mdx)`. This goes for all pages, in rasa-sdk as well!

cc @m-vdb

**Comment by lunelson** [comment]
@erohmensing thanks for the issue. IMO it's a bit misleading for the link to say "edit this page" in that case, since a user who is reading a versioned page would expect to be led to a place where they can contribute an edit to _the versioned page_; moreover, not all versioned pages will exist in the master (unreleased) branch, so there is still potential for the path to 404.

Perhaps versioned pages should go to the documentation branch, and unreleased (current) pages should link to the master branch?

In any case think this issue should be transfered to the theme repo, so we can rewrite this logic for all sites, wdyt?

**Comment by erohmensing** [comment]
@lunelson perhaps we could only make it so that the main docs, not the versioned branches, have the "Edit this page"?

**Comment by lunelson** [comment]
@erohmensing We could also disable the feature altogether: do you see this as something people will do? If we only present this link on the `master/unreleased` version, I think most users will never see it anyway, since this is not the main view

**Comment by erohmensing** [comment]
We've definitely seen people do it before! At that time it was at the top, which makes it more visible, but I could still see people doing it especially if we ask them to.

Should have clarified, I guess it makes most sense to have it only on the main (2.0.x) branch and have it edit the 2.0.x branch, as that is the branch any updates to documentation should go into anyway, in comparison to the master branch

**Comment by lunelson** [comment]
I don't think this is something I can generalize in the theme: the only thing the theme can consistently assume is the path to the versioned document within the repo, because the naming pattern of versioned subfolders is determined by Docusaurus. We could customize the edit URL in terms of which branch actually contains all the versions, if that doesn't happen to be `master`; but beyond this, every repo will differ and there's no way to extrapolate from version-strings to branch-names, AFAICT 😬

**Comment by m-vdb** [comment]
@lunelson would it be possible to:
1. if we assume that the first version in the version array is the latest version
2. only show the link on this version in the theme itself; never show it on `master` or other versions

That way we would simply modify the URLs in our docusaurus.config.js (based on the `versions.js` file too). Would that make sense?

**Comment by lunelson** [comment]
@m-vdb @erohmensing yeah that sounds doable then—only show an edit link for the *last* version number—is that what you want to do?

**Comment by fullpoint** [comment]
I think the first order of business is to fix the 404, asap. Suggest we remove the edit feature for now, or redirect all links to the repo main page. This will at least improve the user experience/SEO quickly.

I don't understand the benefit of the extra work to allow edits only to the latest docs?

**Comment by erohmensing** [comment]
Good point with regards to fixing the 404 @fullpoint 

Yes @lunelson i think that makes sense.

> I don't understand the benefit of the extra work to allow edits only to the latest docs?

If i understand our deployment process correctly, just editing docs files on a branch isn't enough to change the versions online, they only update if we cut a micro release. It's highly unlikely that we'd cut a micro release to an old version just because someone wanted to update the old documentation -- in general we don't really maintain old documentation retroactively
