### ISSUE TITLE
Restrict ConveRTTokenizer to work only if model_url was specified.

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#7045]
Since ConveRT was taken offline by the original authors, the tokenizers and featurizers cannot download the model from the original URL of the model.
However, [some users](https://github.com/RasaHQ/rasa/issues/6806#issuecomment-700017350) may already have a copy of the model and they can host the model on their own if they wish to and use it inside the components. To do so, they can specify the URL of the model or path to a local directory as the value to the parameter `model_url` in the configuration of `ConveRTTokenizer`. `ConveRTTokenizer` should throw an error if the `model_url` is not specified in the configuration or it is the same as the URL of the original model which the authors hosted.
Currently, without this check in place the components error out with a model not found error which is not helpful for the user.

👉  [Slack Thread](https://rasa-hq.slack.com/archives/C7B08Q5FX/p1601385771081700)

**Comment by dakshvar22** [comment]
Bumping up the priority as it affects a lot of users.

**Comment by AdityaSingh06** [comment]
Hi Team,

Even I was facing the ConveRTTokenizer unavailibility issue before so i upgraded rasa to '1.10.14' (using the command "pip3 install rasa[convert] ==1.10.14") and made the following changes to the config.yml file --

pipeline:

name: "ConveRTTokenizer"
"model_url": https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
name: "ConveRTFeaturizer"
"model_url": https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
But ever since I made the above two mentioned changes, my model has become extremely erratic (unable to identify entities properly, misclassifying intensions etc.).
My data has not changed and only above mentioned changes are made from my side. Is there anything i am missing or need to do here?
Any suggestion or pointer would be of great help. Thanks community.
