### ISSUE TITLE
Unfeaturize rule snippets for inference through TED

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#7226]
**Description of Problem**:
Currently, during inference to predict the next bot action, the first check is to see if a rule can be triggered. If not, then the prediction is done through ML policies. However, this can potentially cause a problem because these rule snippets may not be part of any story during training and hence during inference the ML policy may be confused by their presence in the tracker. 

**Overview of the Solution**:
We can unfeaturize/revert conversation turns in the tracker which **only** appear as a rule in the training data. That way any rule which was never a part of a training story but is triggered at inference time is not part of the tracker when an ML policy like TED makes a prediction.

For example, we can have a rule -
```
intent: greet
action: utter_greet
```

Let’s say this rule doesn’t appear in any stories. The conversation may proceed as -
```
User: greet
Bot: utter_greet
User: mood_happy
Bot: ...
```
When the bot has to predict the next action after `mood_happy`, we unfeaturize the states corresponding to the conversation turn involving `greet` and `utter_greet`.

One way to do this is to add new event called `RuleReverted` which contains appropriate number of dialogue turns to revert. When `RulePolicy` is trained, it "learns" deterministically from data whether or not to predict this event during inference.

**Comment by Ghostvv** [comment]
I just understood, you cannot do it in `tracker.applied_events`, because rule policy should see this events. Rather, you should create a temporary tracker inside predict ted, and rule policy should "learn" whether this predicted action should be unfeaturized or not. This information (rather logical not) can be extracted from checking rule predictions on stories. Then `RulePolicy` can release optional event
