### ISSUE TITLE
Can I add Docs on Android Integration for Chatbot on Rasa site

### ISSUE THREAD

**Issue by Horizon733** [RasaHQ/rasa#7228]
**Description of Problem**:
Why is this feature needed? Please link any relevant
Many of the creators and developers try to integrate with android applications and other applications too. But there is no pure way to integrate a bot in any docs. This Doc will help developers and creators to add chatbot in their android applications without third party sdks.

**Overview of the Solution**:
I came up with a pure rasa and android integration without any third party sdks. This will help them to integrate easily and quickly without getting stressed or need to search. Since Docs is the best to give them solutions. So, I came up with this plan.

**Examples**:
Here is my blog please take a look for more information about my plan.
1. Part 1: https://medium.com/@dishant_gandhi/rasa-chatbot-android-covid-app-tutorial-part-1-1010f667c06c
2. Part 2 : https://medium.com/@dishant_gandhi/rasa-chatbot-android-covid-app-tutorial-part-2-40b53cab3630
3. Part 3: https://medium.com/@dishant_gandhi/rasa-chatbot-android-covid-app-tutorial-part-3-73c7a69f3c65
This is how chatbot will work after it has been integrated: https://youtu.be/90RshdbXYbc
**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @Ghostvv will get back to you about it soon! ✨

**Comment by Horizon733** [comment]
Hi, its been a while, Can anyone follow up on adding this doc

**Comment by EmmaWightman** [comment]
Hey @Horizon733 

These tutorials are awesome, and I believe they are very useful for the community! However, the docs is probably not the best place for them to live, since they reference specific software, libraries and experience.

I would still like to establish a centralized space for this to live, so that the community can still easily find and use them. This means we would still need to work to keep them maintained. I will discuss where this could be without team and follow up with you.

**Comment by Horizon733** [comment]
Yeah sure thanks ☺️
