### ISSUE TITLE
check if training entities in DIET is still working on e2e

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#7289]
On e2e, we updated tf methods for TED, since these methods are reused in DIET, DIET performance on e2e branch should be benchmarked against DIET in master

**Comment by tttthomasssss** [comment]
@Ghostvv do you have any datasets in mind? Otherwise I would have gone for `carbon-bot` as a start, and then potentially some of the ones we've used in the DIET paper.

**Comment by Ghostvv** [comment]
@tttthomasssss I'd start by running all our dataset through GitHub as we do it for PRs

**Comment by tttthomasssss** [comment]
* #7371 is benchmarking DIET from `master`
* #7375 is benchmarking DIET from `e2e`

**Comment by tttthomasssss** [comment]
@Ghostvv results look pretty similar, the ones from `e2e` seem to be a tiny bit lower than from `master` (on `carbon-bot` and `HERMIT`), though I'd regard them within range still. The stuff from `e2e` also seems to be a bit slower (e.g. up to 2mins for `carbon-bot` and up to 5mins for `HERMIT`). But this might also due to `github`.

**Comment by Ghostvv** [comment]
Great! then I think we can close the issue, @tabergma do you have any other tests in mind?

**Comment by tabergma** [comment]
Great, no, I think that should be sufficient.
