### ISSUE TITLE
Using version: "2.1" in domain.yml raises an warning and skips the file

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7327]
**Rasa version**: 2.1.1

**Python version**: 3.7.9

**Operating system**: Ubuntu

**Issue**:
When using `version: "2.0"` at the start of my domain files, I get a warning that the version of Rasa is higher than the version specified and the file is skipped. However, I am using rasa 2.1.1 (checked with `pip freeze`)

**Error (including full traceback)**:
```
/home/nicolas/anaconda3/envs/chatbot2.0/lib/python3.7/site-packages/rasa/shared/utils/io.py:93: UserWarning: Training data file /home/nicolas/dev/chatbot/domain/actions.yml has a greater format version than your Rasa Open Source installation: 2.1 > 2.0. Please consider updating to the latest version of Rasa Open Source.This file will be skipped.
  More info at https://rasa.com/docs/rasa/training-data-format
```

**Command or request that led to error**:
```
rasa train --domain domain
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml
version: "2.0"
actions:
  ...
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
Wait so your rasa version is 2.1.1 and in your file you added `version: "2.0"`? just to double check as that means something is wrong with the check in the code

**Comment by nbeuchat** [comment]
@tmbo that's right. I resorted to just using `"2.0"` for now

**Comment by stephanrb3** [comment]
I'm getting this same error with 2.2.5, it won't let me specify anything above 2.0 in my training data or it skips them

**Comment by stephanrb3** [comment]
Is anyone working on fixing this? I was able to reproduce this issue on a fresh vm, and I cannot seem to find a workaround other than not using >2.0 and not using any of the features added in 2.1.

**Comment by desmarchris** [comment]
@nbeuchat just to confirm, it's when you put "2.1" as the version in your domain file that you see this error right? I don't think this is an actual bug. This version is referring to the training data format and not the rasa open source version: https://rasa.com/docs/rasa/training-data-format#high-level-structure

If this is what your bug is, I think this is more a usability issue. It should be more explicit that it's the training data format version and not the rasa open source version.

**Comment by nbeuchat** [comment]
@desmarchris That's right. Personally, my feeling is that it should match the Rasa open-source version. Say you introduce a new feature in version 2.4 that adds an option to `forms`, then domains which use this new feature would only be valid with Rasa OSS 2.4 or later. If the training data version does not match the Rasa OSS version, it would be super confusing to know what we're suppose to put in the version field. In the fake example I used, what would be the version after this new feature is added? 2.1? 2.4?

**Comment by wochinge** [comment]
Training data `version` and Rasa Open Source version are currently not coupled. 

**You should always have `version: "2.0"` in your training data files.**

@stephanrb3 This means you need to change your training data version to `2.0` in order to unblock your development.

You raised a very good point about what we actually use the `version` key and when we actually increment that 🙌🏻  As it's slightly different from the current issue, I'll close this one and track the progress on the other item in [this issue.](https://github.com/RasaHQ/rasa/issues/8635)
