### ISSUE TITLE
[Windows unit-test] Windows installation times out after 5 hours

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#7507]
It happened [here](https://github.com/RasaHQ/rasa/pull/7268/checks?check_run_id=1525103814) and [here](https://github.com/RasaHQ/rasa/pull/7471/checks?check_run_id=1525006234) and also [here](https://github.com/RasaHQ/rasa/pull/7284/checks?check_run_id=1529366468).

It times out at the step `poetry run python -m pip install -U pip`

cc @koernerfelicia @tczekajlo

**Comment by tczekajlo** [comment]
Poetry since >= 1.1.0b switched to `vritualenv` (https://github.com/python-poetry/poetry/releases/tag/1.1.0b1). The default version of `vritualenv` used by poetry is 20.0.31, update virtualenv to the latest version helps only partially (I assume this fixed some things https://github.com/pypa/virtualenv/pull/1976), there is still a problem with python 3.6 though.

In the https://github.com/RasaHQ/rasa/pull/7542 I switched back to `venv` that works for Windows and Linux.
