### ISSUE TITLE
Rasa X doesn't load all stories or rules

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#7597]
Raising issue here for visibility, because a forum user brought this to my attention. 

**Rasa version**: 2.1.2

**Rasa X version** (if used & relevant): 0.34.0

**Issue**:

Rasa X 0.34.0 only loads 20 of your stories when going to the stories screen. This definitely wasn't an issue in 0.33.0 (I tested it out on the killer-demo instance beforehand). Sara has 200+ stories, and only 20 of them are there in the updated 0.34.0 instance. Take a look at the screen recording here: https://drive.google.com/file/d/1mN4yVx9DjbSsCO0J0cFMl8DaKDivcN8d/view?usp=sharing

You can investigate this issue on the killer-demo instance (website-demo dot rasa dot com).

**Comment by mjaycub** [comment]
Firstly, this also **appears to affect the rules view also** so I've updated the issue.

@federicotdn I've been looking into this and I think this may be because the backend is not returning the correct `total` value, however, I'm not sure when this changed. I noticed the `total` value returned for a call to the `/stories` or `/rules` endpoints only return the total fetched (so with a `limit` of 20, `total` will be 20, even if there are 40 more fetched stories/rules).

Do you know if this changed during `2.0`, or at any stage? Acc. to the issue this wasn't a problem in `0.33` but became visible in `0.34`.

For comparison, if we call the fetch conversations `/conversations` endpoint with a `limit` of 20, we get 20 conversations but `total` still equals the total number of conversations eg: 202. We use this `total` value for our virtualised lists in the table, so if the value is reached we don't fetch anymore.

**Comment by federicotdn** [comment]
@mjaycub I've checked the code for the stories API and it seems like the value of `X-Total-Count` is always being set as the length of the stories array being returned, see [here](https://github.com/RasaHQ/rasa-x/blob/main/src/community/rasax/community/api/blueprints/core/stories.py#L137). Unfortunately that line of code has been shifted around, but the behaviour has always been like that it seems. I've tracked the change back to March 22nd, 2019 [here](https://github.com/RasaHQ/rasa-x/commit/c0ef9c26e308a5ae105daf0565f0e2c96ef1e931#diff-c2e97d6ff342d629f9cc9b1ddb83887dd23a2761a6961af0094cd541e0769d30R386), when we migrated from MongoDB to SQL.

So the fix for this would be on the backend. Note that we did this change (https://github.com/RasaHQ/rasa-x/pull/3940) recently, which means that we are no longer ignoring `offset`/`limit` sent by the frontend - I assume these two values will be sent correctly (i.e. they will be paginated correctly) once we fix the `X-Total-Count` thing.

**Comment by mjaycub** [comment]
Thanks for checking this out @federicotdn 🙏  We may have accidentally been solving this since the code hasn't changed, but I think now that we've found it we should fix it properly.

I'll tag this with `backend` tag and update the description here for our backlog if that sounds good to you?

**Comment by Tawakalt** [comment]
Closing this as it’s been solved in [another Rasa X issue](https://github.com/RasaHQ/rasa-x/issues/4407)

**Comment by mishra011** [comment]
Hi am facing same issue. I have 38 stories in total but rasa-x UI is showing only 20 and it is training with 20 only. 
Please help.

**Comment by mjaycub** [comment]
@mishra011 can you let us know what version of `rasa` and `rasa-x` you are using?

**Comment by mishra011** [comment]
Hi @mjaycub 
Rasa version: 2.1.2
Rasa X version : 0.34.0

**Comment by mjaycub** [comment]
@mishra011 according to our [changelog](https://rasa.com/docs/rasa-x/changelog/rasa-x-changelog/#bugfixes-13), it looks like we fixed this issue in the `0.36.0` release. 

Today we're up to version `0.41.0` of Rasa X which I would recommend upgrading to from `0.34.0` to get all of the recent bug fixes and features.

**Comment by mishra011** [comment]
Thanks , @mjaycub  I will try newer version and let you know.
