### ISSUE TITLE
Making `rasa interactive` command line tool more user friendly in 3 simple steps

### ISSUE THREAD

**Issue by shubhvachher** [RasaHQ/rasa#7642]
**Description of Problem**:

*   **Ask users if they wish to save each file**; for example, not everyone wants to override their hand created YAML `domain.yml` file while still wanting to save the NLU and story files.
*   **Always show user input text in summary table** (right hand side of screen) in the `interactive` mode. Right now it is sometimes shown and sometimes just the user `intent` is shown. This is useful because most users would run interactive mode and stop it when it fails, change some files to fix the issue and restart interactive mode. They would really love to see exactly their previous inputs in the concise table format rather than having to endlessly scroll back searching for each of their input texts. IMPORTANTLY, it isn't required to save said text in the final story output, so, no changes there.
*   **Have an _EXIT Without Saving_ button in interactive mode**, please. Rarely do the interactive sessions go even just well enough to save. Right now users need to keyboard interrupt out of interactive mode, then select "Exit and Save" mode and then keyboard interrupt out of that to come back to command prompt.

**Overview of the Solution**:

Seems simple to implement technically but haven't got into it. Want to start a discussion first, of course.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @samsucik will get back to you about it soon! ✨

**Comment by samsucik** [comment]
Hi @shubhvachher, thanks for the interesting points!
1. **Ask users if they wish to save each file**: I totally agree with you on this one, especially for the domain file. On the other hand, we need to ensure that users don't accidentally introduce inconsistencies into their data by not saving some important changes. From this point of view, I think we should leave it as "opt-out", but maybe Rasa could check if anything actually changed in the domain (or a new unique story or NLU example was created) and not bother the user with the given file if nothing has changed?

2. **Always show user input text in summary table**: Could you give an example of when the user input is not shown? In general, I agree that it'd be useful to always have it there.

3. **Have an EXIT Without Saving button in interactive mode**: My understanding is that Rasa wants to prevent accidental loss of unsaved changes, hence exiting takes some effort (the quickest way I use is Ctrl+C three times). However, there could still be an option "Exit without saving", given that it's hard to select that one accidentally instead of "Export & quit"...

@TyDunn I'm curious to hear your thoughts here.
