### ISSUE TITLE
`rasa init` misinterprets project path if it contains aliases such as '~'

### ISSUE THREAD

**Issue by hobson** [RasaHQ/rasa#7705]
Rasa Version : 2.2.2 Rasa SDK Version : 2.2.0 Rasa X Version : None Python Version : 3.8.5 Operating System : Linux-5.4.0-60-generic-x86_64-with-glibc2.10 Python Path : /home/hobs/anaconda3/envs/rasaenv/bin/python

**Issue**: User in POSIX environment cannot use `~` shortcut (home directory) to create a `rasa` project in their home directory.

**Error (including full traceback)**: There is no error message or traceback, only unexpected and incorrect behavior.

**Command or request that led to error**: N/A

 $ rasa init
 ...
 ? Please enter a path where the project will be created [default: current direct
 ory] ~/rasaproject 
 ...

**`Created project directory at '/home/hobs/code/tangibleai/rasa/~/rasaproject'.`**

 Finished creating project structure.
 ? Do you want to train an initial model? 💪🏽 No 
 No problem 👍🏼. You can also train a model later by going to the project directory and running 'rasa train'.

 tangibleai/rasa$ ls ~/rasaproject
 ls: cannot access '/home/hobs/rasaproject': No such file or directory
 tangibleai/rasa$ ls -l
 total 572
 drwxrwxr-x 3 hobs hobs 4096 Jan 10 16:15 '~'
 ...

**Content of configuration file (config.yml)** (if relevant): N/A

**Content of domain file (domain.yml)** (if relevant): N/A

submitted on behalf of @billy-horn who is submitting a PR that fixes it on @tangibleai 's fork

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @m-vdb will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
Hi @hobson, thanks a lot for your bug report. It looks like a valid bug, since [here](https://github.com/RasaHQ/rasa/blob/771cc4b4644f6b2f785c353304521ad69d68d8ae/rasa/cli/scaffold.py#L201-L220) we do not [expand](https://docs.python.org/3/library/pathlib.html#pathlib.Path.expanduser) the user home directory.

You mentioned that @billy-horn was fixing it in a fork. In case you have some capacity, it would be great if you could submit a PR here. I'd happily take the review 😄

**Comment by guilherme-mendes** [comment]
Hey there, I would like to know if someone is already working on this issue.

**Comment by billy-horn** [comment]
This issue has been moved over to a new pull request that's being reviewed. I'll delete this one. Thanks!

**Comment by m-vdb** [comment]
@billy-horn do you have the link of the PR?

**Comment by billy-horn** [comment]
@m-vdb 

**Original PR:** https://github.com/RasaHQ/rasa/pull/7706
We were having trouble with the CLA, so instead opened a new PR to circumvent the issue.

**New PR:** https://github.com/RasaHQ/rasa/pull/7790
This PR has been approved, but I have since added some tests to check the path expansion functionality.

I plan on closing #7706 but please let me know your thoughts.

**Comment by m-vdb** [comment]
great! yes please close the duplicate PR 🙏🏻

**Comment by sushii-00** [comment]
Hello, i also would like to take a look at this issue, is it still open?

**Comment by m-vdb** [comment]
Yes it is, there is a linked PR that appears to be stale at this stage, but could be good to look at for context 😄

**Comment by bielrossi15** [comment]
Hey, I am with a group of developers here that might be willing to take this issue !
Is it still open for contribution?

**Comment by bielrossi15** [comment]
Is this issue still open for contribution? I am interested in solving it!

**Comment by m-vdb** [comment]
yes it is 😄

**Comment by AlvaroLeles** [comment]
I want to work on it
