### ISSUE TITLE
Improve merging of small community contributions into minor branches

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#7760]
Our contributors can create small fixes that should go right into the next micro release. However, the contributor will often open a PR targeting the main branch (`main/master`), not a minor branch like `2.2.x`. What's more, the PR will want to merge changes from a fork of our repo. (See #7755 for a recent example.)

If we want to get that contribution quickly into the next micro release, there should be a dead easy way to apply those changes to a minor branch. Could our GitHub bot Roberto take care of it?
*Note: Changing the base branch by editing the PR isn't the way to go -- it brings into the PR a lot of irrelevant commits (everything that's in the main branch but not in the minor one, i.e. things that should only go into the next minor release). We really need something like rebase, but from the forked repo to our minor branch.)*

**Comment by m-vdb** [comment]
Thinking about it, since contributors open pull requests from their own repo to our repo, like you mentioned, we would need write access to their repo, and this seems unrealistic.

One solution I see is a `git rebase --onto 2.2.x main the-branch` when the changes are ready to be merged. We could have some sort of tooling to do it (a label or a command in a comment), but we'd need to create a new branch from the contributor's branch and rebase it in our own repo, and open a new PR for this branch. At which point we (the reviewer?) would take over and ensure that the PR is merged (e.g. fix possible failing checks that were not visible on the PR against master, but are now visible on the PR agains the release branch).

Would that make sense? Is it too complicated? I was trying to think about ways to do it earlier in the process (at the opening of the PR), but all the ideas I have require access to the contributor's repo.

**Comment by samsucik** [comment]
@m-vdb your solution sounds good to me. It's complicated but I don't see a better way around it if we want to have contributions appear quickly in releases. Just making sure, the commits would still be shown with the contributor as their author, right? (So we don't take credit away from our contributors.)

Having thought about this, I also think we could change our contributor guidelines to mention that there are these multiple branches (`main` vs minor) and that if folks are making changes to docs, they should target the latter. If it's code and they think it's minor changes and want to see it in next micro release, then we could recommend tagging someone from Rasa and discussing with them before opening the actual PR. I think many people would not read this and still open PRs only on `main`, but even a few folks who do it right can be great. cc @EmmaWightman

**Comment by m-vdb** [comment]
> Just making sure, the commits would still be shown with the contributor as their author, right? (So we don't take credit away from our contributors.)

I think that's a requirement yes.

**Comment by mprazz** [comment]
Adding this to the Infra board so I can adjust the README asap 😊

**Comment by samsucik** [comment]
@tmbo just curious, has this been addressed or is it captured by some other existing issues? Asking partly because I'm still seeing folks opening PRs from forks and I don't know how to best handle those.

**Comment by tmbo** [comment]
The infra team won't create any automation for this any time soon.
