### ISSUE TITLE
Suppress noisy tensorflow logs on linux and Windows

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#7762]
**Rasa version**:
2.2.4
**Python version**:
3.7.2
**Operating system** (windows, osx, ...):
Windows, Linux

**Issue**:

It seems that the hack to suppress noisy tensorflow logs is no longer working for Windows or Linux. This confuses users unnecessarily.

**Error (including full traceback)**:
example:
```
2021-01-15 12:12:22.059483: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
```

**Definition of Done**:

- [ ] determine the cause of Tensorflow warnings when using `rasa` in non-debug mode & document
- [ ] fix the current issue (that warnings get shown)

**Comment by joejuzl** [comment]
Relates to: https://github.com/RasaHQ/rasa/issues/7738

**Comment by TyDunn** [comment]
Based on [this Slack discussion](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1617097796180900?thread_ts=1617090758.172800&cid=C8LEHMTAM), we are going to move this to Enable

**Comment by twerkmeister** [comment]
This particular warning doesn't seem to be just a nuisance.

Found [a tensorflow issue](https://github.com/tensorflow/tensorflow/issues/38578) on this and it seems like the dependency (at least the specific version) is missing and in the output it also says:

**Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU [...] Skipping registering GPU devices...**
```
[...]
2020-04-15 20:58:07.205269: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] 
Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared 
object file: No such file or directory
[...]
2020-04-15 20:58:07.219842: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] 
Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are 
installed properly if you would like to use GPU. Follow the guide at 
https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for 
your platform. Skipping registering GPU devices...
```


Where is this warning log from @koernerfelicia? Also, looks like you have some PR open to change logging level - what should happen with that? And, was the GPU in fact not usable?

**Comment by koernerfelicia** [comment]
@twerkmeister I think in many cases (and all that I am wanting to address) it *is* just a nuisance -- we get these error messages even when there's no GPU available, hence these libraries don't need to be installed:

See CI logs [here](https://github.com/RasaHQ/rasa/pull/7990/checks?check_run_id=2149382304#step:12:54):
`Ignore above cudart dlerror if you do not have a GPU set up on your machine.`

The libraries it's looking for are CUDA-related libraries, which you *do* need for a GPU setup, but *don't* for a purely CPU setup. I think we're seeing this because you used to have to install a specific version of `tensorflow` to be able to use a GPU ([`tensorflow-gpu`](https://www.tensorflow.org/install/gpu#older_versions_of_tensorflow)), and now even the "standard" `tensorflow` is GPU-compatible. My guess is with the switch to the single tensorflow with GPU suppport they decided to just look for the CUDA libraries either way, complain if they're not found, and let the user decide whether they need the library or not (whereas before, I imagine `tensorflow-gpu` looked for them, and `tensorflow` didn't).

> And, was the GPU in fact not usable?

I haven't observed this issue with a GPU, as I have always had the CUDA libraries installed. I can't imagine that the GPU would be usable without the CUDA libraries (as far as I know, non-CUDA architectures are not supported by `tensorflow`, and I'm not sure we have access to these types of architectures on google compute anyways).


> where is this warning log from

As far as I can tell, the logs are appearing for Windows and Linux users. They can be observed in our CI logs (see link above, for example).

> like you have some PR open to change logging level - what should happen with that

The PR is only useful as a record of what I tried to fix the issue. None of these fixes worked.

Happy to jump on a call to discuss any of this!

**Comment by koernerfelicia** [comment]
Slack discussion [here](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1610714890070700?thread_ts=1610558144.253400&cid=C8LEHMTAM)

**Comment by twerkmeister** [comment]
Thanks for all the context! Makes sense. Will see if there's some setting to let tensorflow go for cpu if there's no gpu anyway!

**Comment by twerkmeister** [comment]
Also not getting this warning on my laptop either, seems there might be a slight difference between local and ci environment

**Comment by koernerfelicia** [comment]
What OS? I think it might just be Linux and Windows

**Comment by twerkmeister** [comment]
locally I am on mac os...

I was just about to benchmark another issue on a google cloud machines using a template from an earlier research machine and got the same warning when using rasa. Turns out that cloud machine only had cuda 10.0 installed, but our tf version looks for cuda 10.1. Seems last version that used cuda 10.0 was 2.0. Did we just upgrade tf recently?

**Comment by koernerfelicia** [comment]
Not *that* recently, think around fall of last year? Not sure exactly, I think this was before I started (Oct). Can find this out for you, though.

CUDA and tensorflow can be a bit tricky -- the standard pip install isn't always compatible with just any old CUDA. You can compile from source for a specific TF/CUDA combination, but this is also a bit of a pain, so I'd try to get an image that has a a compatible tensorflow already installed. This also means you'll have to specifically use that tensorflow in a virtualenv or not use a virtualenv at all. Happy to jump on a call to explain this, we've had various issues with this. There are some details [here](https://www.notion.so/rasa/Running-Experiments-on-Google-Cloud-41c50e7e7b894d69acf08b25e82ef898#2471f799aa3b4c6fbc3cd7b30f2e266d)

**Comment by twerkmeister** [comment]
Hey @koernerfelicia I just got around writing back about the issue - thanks for the pointers for tf/cuda. 

So basically it seems logging behavior is a bit different on the different operating systems. On my mac, i don't get any warnings about libcuda by default. On an ubuntu machine, the logs are much more verbose. The flag that you had already found solves the problem for me. I think it's just a question of where we set the flag so that it is turned on for all sorts of commands.

It should be on during:
* all rasa cli commands 
* test execution
* something else?

**Comment by twerkmeister** [comment]
So it seems that this flag is already set during all invocations of the rasa cli here:

https://github.com/RasaHQ/rasa/blob/c8e6c6bddb1552af29e17c056af2d9324878b057/rasa/__main__.py#L95-L105

which is ...

https://github.com/RasaHQ/rasa/blob/c8e6c6bddb1552af29e17c056af2d9324878b057/rasa/utils/common.py#L64-L81

which is defined here, and sets the same flag, TF_CPP_MIN_LOG_LEVEL=2.

https://github.com/RasaHQ/rasa/blob/c8e6c6bddb1552af29e17c056af2d9324878b057/rasa/utils/common.py#L109-L122

Have also tested that I get the log about libcuda when I just import tensorflow in a python repl, but don't see it when I run rasa train.

So this seems to be about the test setup

**Comment by koernerfelicia** [comment]
@twerkmeister that sounds about right. I think it's important the environment variable is set **before** tensorflow is imported for the first time, not sure if you've already discovered that/whether it's related.

**Comment by koernerfelicia** [comment]
I do think this isn't just limited to the CI (for some OS, like you've already noted). I have seen forum users with these messages in their logs. It looks like the PR you linked relates specifically to pytest?

**Comment by twerkmeister** [comment]
It seems to me that everything that is started from the command line interface, i.e. `rasa train`, `rasa test`, `rasa ....` has the appropriate env variables set. The code I referenced shows that and I tested it on ubuntu machines 🤔 

The problem in CI seems to be that we don't do it during the tests when calling pytest.

For the forum posts, I did a quick search in the forum for `libcuda` and a number of posts come up. A lot of them seem to be related to rasa-x, so that would probably be worth a look there. Second, for the rasa commands where I found it, it would be good to have the exact command, os, and rasa version - maybe it's an older one where it wasn't in there? Or there is some OS where it doesn't work? So these are a bit vague and difficult for me to reproduce. And then third, in custom code when people import some rasa training procedures, we are gonna see these logs as the env variables aren't set by our CLI setup procedures. Which I think is fine.

So for me right now the most actionable things are:
* fixing it for the tests in CI
* checking and fixing it if necessary for rasa-x invocations

And if we really care about it we can track these things on the forum and try to figure out if there's a combination that is problematic?

**Comment by koernerfelicia** [comment]
Yes that seems fair, and I agree we don't have a lot else to go on. Sorry, I wasn't trying to suggest you take any other action, I'd just like to make sure we keep it on our radar.

I think that it's not obvious to people that these logs are often just a nuisance, so I want to make sure we recognize them as such. They can be a red herring if you are trying to debug a problem and don't know what they mean.

**Comment by twerkmeister** [comment]
I am on the rasa x stuff then, and trying to get the updated dependencies for the pytest plugin to run 🙄

**Comment by koernerfelicia** [comment]
@twerkmeister maybe this is a naive question, but is there any reason we would see these logs when running rasa shell in docker? Had a user with these messages in [their logs](https://forum.rasa.com/t/rasa-2-2-fails-but-1-10-works/43706) this morning. Of course, dunno what kind of docker file they're using and what adjustments they've made etc etc.

**Comment by twerkmeister** [comment]
I think in this case it's because of the debug flag. 

I think there's some interaction here between setting the environment variable and setting the tf log level - potentially the latter overwrites the env var again. I think with --debug it's also okay that these logs show up. What do you think?

https://github.com/RasaHQ/rasa/blob/c8e6c6bddb1552af29e17c056af2d9324878b057/rasa/utils/common.py#L109-L122

**Comment by koernerfelicia** [comment]
True! I think you're right and the flag will overwrite the level -- pre-coffee I had the debug levels muddled. Thank you, sorry about the false alarm

**Comment by twerkmeister** [comment]
hmm hmm with respect to rasa x, it seems that is also started through the rasa oss CLI commands and such it should have it's log level set appropriately. I am wondering whether we see the tf logs in the forum more often as people turn on --debug to check if they find some error themselves first and then post that log?
