### ISSUE TITLE
Extend model regression tests for action prediction policies

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#7835]
Currently, the model regression tests can only run tests for the NLU components.
These should be extended to benchmark action prediction policies in Core as well.
We can use the datasets for Carbon bot, Sara, Financial demo as a starting point.
Note: This has to be done in collaboration with Infrastructure squad.
The current setup for model regression tests is described in this [notion document](https://www.notion.so/rasa/The-CI-for-model-regression-tests-92af7185e08e4fb2a0c764770a8e9095)

**Comment by dakshvar22** [comment]
@kedz For reference, @samsucik has already spent some time creating a better test set of stories for Sara [here](https://github.com/RasaHQ/research/tree/sara-real-test-set/projects/sara-real-test-set/tests)

**Comment by kedz** [comment]
@dakshvar22 do you know who I should I reach out to on the infrastructure squad?

**Comment by dakshvar22** [comment]
@tczekajlo Should be able to help you with this.

**Comment by kedz** [comment]
@tczekajlo can you point me in a direction to get started? From this [notion page](https://www.notion.so/rasa/The-CI-for-model-regression-tests-92af7185e08e4fb2a0c764770a8e9095) I can see how to add model configs or datasets but it isn't clear how to add a new test. In this case, we want to start regression testing our dialogue policy models as well.

**Comment by dakshvar22** [comment]
@kedz I would suggest coming up with a workflow locally and answering these questions - 
1. What commands do you want to run as part of the test?
2. What information do you want to extract from the results of the test?
3. How do you want to display this information to the creator of the PR?
4. How do you envision these tests to be run on the PR. Take a look at how they are done for NLU, how different would it be for Core?
5. What set of configurations do you want to be able to run?
6. Do the tests differ in the scheduled version of these tests v/s PR version of them?

Once you have this information, I think @tczekajlo will be able to help you better.

**Comment by kedz** [comment]
@dakshvar22 I understand how to run the tests from a pull request but I can figure out where the actual test code for nlu is located. Do you know where this is?

**Comment by dakshvar22** [comment]
Okay here are some resources to help you out - 

1. How is a Rasa assistant evaluated - https://rasa.com/docs/rasa/testing-your-assistant
2. Code where test commands are run currently in model regression tests - https://github.com/RasaHQ/rasa/blob/main/.github/workflows/ci-model-regression-on-schedule.yml#L168

Don't worry about (2), that's what Tomasz can help you out with. The first resource is what will be useful for you to come up with a workflow locally.

**Comment by kedz** [comment]
Thank you!

**Comment by kedz** [comment]
@tczekajlo So we want to train and evaluation some rasa core configs as part of the CI for model regression tests. This would involve calling:
`poetry run rasa train core --quiet -s $DATASET/train -c configs/$CONFIG -d $DATASET/domain.yml --out models/$DATASET/$CONFIG`

and
      
`poetry run rasa test core --quiet -s $DATASET/test -m models/$DATASET/$CONFIG --out results/$DATASET/$CONFIG`

This produces a file `results/$DATASET/$CONFIG/story_report.json` that contains weighted, macro, and micro averaged metrics for the dialogue policy configuration, similar to files produced by the `rasa test nlu` command.

The results can still be read by the same scripts as used by nlu regression test:

```
poetry run python .github/scripts/mr_publish_results.py
poetry run python .github/scripts/mr_generate_summary.py
```

We only need to modify those two scripts to also read "story_report.json" if it finds it in the results directory. 

The results could be presented similarly to the nlu models results. 

As of right now I don't think there is much of a difference between PR and scheduled versions of these tests.

I have made the modifications to mr_publish_results.py and mr_publish_results.py, and created an example policy regression test work flow that would work similarly to ci-model-regression-tests.yml workflow, but instead of looking for status:model-regression-tests, it would look for status:policy-regression-tests, on this [draft PR.](https://github.com/RasaHQ/rasa/pull/7897). I haven't worked with gitrunner/git hub actions before so I haven't actually been able to test this yet. If you have pointers on how I can do that or comments on any of the above please let me know. Thank you!

**Comment by kedz** [comment]
@samsucik Can I move `stories-good-yaml` into the training-data repo for you? We currently don't have any datasets in there with train/test stories that I could use for policy regression tests.

**Comment by samsucik** [comment]
@kedz sure, feel free to move it, just don't spend too much time organising or documenting those things because I'll do it pretty soon 🙂  For training, just take the current version from [here](https://github.com/RasaHQ/rasa-demo/tree/master/data), though the exact version of that also might require some changes in the future.

One major thing I should point out (and I realise I didn't previously think of it): Testing Core requires also running the action server (and potentially also a duckling server?). So it'll be a bit more than just `rasa test core`.

**Comment by tczekajlo** [comment]
> @tczekajlo So we want to train and evaluation some rasa core configs as part of the CI for model regression tests. This would involve calling:
> `poetry run rasa train core --quiet -s $DATASET/train -c configs/$CONFIG -d $DATASET/domain.yml --out models/$DATASET/$CONFIG`
> 
> and
> 
> `poetry run rasa test core --quiet -s $DATASET/test -m models/$DATASET/$CONFIG --out results/$DATASET/$CONFIG`
> 
> This produces a file `results/$DATASET/$CONFIG/story_report.json` that contains weighted, macro, and micro averaged metrics for the dialogue policy configuration, similar to files produced by the `rasa test nlu` command.
> 
> The results can still be read by the same scripts as used by nlu regression test:
> 
> ```
> poetry run python .github/scripts/mr_publish_results.py
> poetry run python .github/scripts/mr_generate_summary.py
> ```
> 
> We only need to modify those two scripts to also read "story_report.json" if it finds it in the results directory.
> 
> The results could be presented similarly to the nlu models results.
> 
> As of right now I don't think there is much of a difference between PR and scheduled versions of these tests.
> 
> I have made the modifications to `mr_publish_results.py` and `mr_publish_results.py`, and created an example policy regression test workflow (`.github/workflows/ci-policy-regression.yml`) that would work similarly to ` .github/workflows/ci-model-regression.yml` but instead of looking for `status:model-regression-tests`, it would look for `status:policy-regression-tests`, on this [draft PR](https://github.com/RasaHQ/rasa/pull/7897). I haven't worked with gitrunner/git hub actions before so I haven't actually been able to test this yet. If you have pointers on how I can do that or comments on any of the above please let me know. Thank you!



> @tczekajlo So we want to train and evaluation some rasa core configs as part of the CI for model regression tests. This would involve calling:
> `poetry run rasa train core --quiet -s $DATASET/train -c configs/$CONFIG -d $DATASET/domain.yml --out models/$DATASET/$CONFIG`
> 
> and
> 
> `poetry run rasa test core --quiet -s $DATASET/test -m models/$DATASET/$CONFIG --out results/$DATASET/$CONFIG`
> 
> This produces a file `results/$DATASET/$CONFIG/story_report.json` that contains weighted, macro, and micro averaged metrics for the dialogue policy configuration, similar to files produced by the `rasa test nlu` command.
> 
> The results can still be read by the same scripts as used by nlu regression test:
> 
> ```
> poetry run python .github/scripts/mr_publish_results.py
> poetry run python .github/scripts/mr_generate_summary.py
> ```
> 
> We only need to modify those two scripts to also read "story_report.json" if it finds it in the results directory.
> 
> The results could be presented similarly to the nlu models results.
> 
> As of right now I don't think there is much of a difference between PR and scheduled versions of these tests.
> 
> I have made the modifications to `mr_publish_results.py` and `mr_publish_results.py`, and created an example policy regression test workflow (`.github/workflows/ci-policy-regression.yml`) that would work similarly to ` .github/workflows/ci-model-regression.yml` but instead of looking for `status:model-regression-tests`, it would look for `status:policy-regression-tests`, on this [draft PR](https://github.com/RasaHQ/rasa/pull/7897). I haven't worked with gitrunner/git hub actions before so I haven't actually been able to test this yet. If you have pointers on how I can do that or comments on any of the above please let me know. Thank you!

I'll try to take a look at it tomorrow

**Comment by dakshvar22** [comment]
@tczekajlo I've added this issue to the infrastructure squad's inbox as well so that you folks can take up the implementation in one of the sprints once we hand out the scope document([in progress](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1612896958028200)).
