### ISSUE TITLE
Investigate `test_rasa_data`: All conversions take 10+ seconds

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#8128]
**Rasa version**: 2.3.4 (used `main` branch)

**Rasa SDK version** (if used & relevant): 2.3.1

**Rasa X version** (if used & relevant):

**Python version**: 3.7 / 3.8

**Operating system** (windows, osx, ...): MacOS / Windows

**Issue**:
The conversions in `test_rasa_data.py` take too much time — one of the reasons is probably that we execute CLI commands in these tests, and CLI is slow in general.

There are the tests that need to be checked: 
- `test_rasa_data_convert_nlg_to_yaml`
- `test_rasa_data_convert_nlu_to_yaml`
- `test_rasa_data_convert_stories_to_yaml`

See more details about time measurements: https://docs.google.com/spreadsheets/d/1tDRD0vWaLW91W1wPj5h__dwXuXioRt9aBPYyF1n4MjI/edit#gid=57091041 

**Definition of done**:
- These tests run in less than 5 seconds

**Command or request that led to error**:
```
pytest tests/test_rasa_data.py
```

**Comment by Imod7** [comment]
Also, a reason of these tests being slow might be that they are all writing to files in the disk. Maybe the use of [mock_open](https://docs.python.org/3/library/unittest.mock.html#mock-open) is relevant and can help in speed as described in an example also [here](https://stackoverflow.com/questions/20531072/writing-a-pytest-function-to-check-outputting-to-a-file-in-python).

**Comment by wochinge** [comment]
This will be fixed by https://github.com/RasaHQ/rasa/pull/8141 + replacing the any policy imports in these modules with the usage of string constants (we currently only do imports to access the policy names) (see [here](https://github.com/RasaHQ/rasa/pull/8141#discussion_r591579752
) for more details.

This brings down the test duration for the module from 140 seconds to 34 seconds. No test takes longer than 2.2 seconds


<img width="972" alt="Screenshot 2021-03-10 at 16 05 19" src="https://user-images.githubusercontent.com/7667273/110650074-7f9fa080-81ba-11eb-9112-50130eb14c4a.png">
<img width="1063" alt="Screenshot 2021-03-10 at 16 05 25" src="https://user-images.githubusercontent.com/7667273/110650082-81696400-81ba-11eb-9079-8df5096c528c.png">

cc @RasaHQ/enable-squad

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/8141
