### ISSUE TITLE
Support for multiple tokenizers in a pipeline

### ISSUE THREAD

**Issue by sammerpuranpost** [RasaHQ/rasa#8139]
**Description of Problem**: Since Rasa 1.8, it is not possible to have multiple tokenizers in one pipeline. Since we need multiple tokenizers but also do not want to miss out on new Rasa Features we would like to have the option to have multiple tokenizers, if that does not break the code <span class="error">[forum]</span>[https://forum.rasa.com/t/rasa-2-3-4-multiple-tokenizers-in-pipeline/40830](https://forum.rasa.com/t/rasa-2-3-4-multiple-tokenizers-in-pipeline/40830)

**Overview of the Solution**: In the code of components.py there is a check if the pipeline has multiple tokenizers. One could remove that check

**Examples** (if relevant):

**Blockers** (if relevant): I do not know, if adding the option of multiple tokenizers would break something

**Definition of Done**: What needs to be there to consider this feature as done?

*   [] Tests are added
*   <span class="error">[X]</span> Feature described the docs
*   <span class="error">[X]</span> Feature mentioned in the changelog
*   <span class="error">[X]</span> If not possible to have this feature, an explaination somewhere in the documentation would be appreciated

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @joejuzl will get back to you about it soon! ✨

**Comment by joejuzl** [comment]
Hi @sammerpuranpost 

What is your use case for needing multiple tokenizers in your pipeline?

In general having multiple tokenizers is problematic because then they have dependencies on each other and the order then run. If you need to tokenize in different ways it is probably best to create a custom tokenizer which combines the functionality of a multiple tokenizers.
