### ISSUE TITLE
[Diet Classifier] ValueError: Number of examples should be the same for all data with entities

### ISSUE THREAD

**Issue by sammerpuranpost** [RasaHQ/rasa#8154]
**Rasa version**: 2.3.4

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.6

**Operating system** osx,linux:

**Issue**:
I have a dataset, which contains entities, text and intents. However when I want to train the DIET classifier, it complains that all sets should have the same number of examples. But because not every sample has an entity, this is not possible

**Error (including full traceback)**:

```
File "/app/apis/train.py", line 334, in async_model_training
    train(quid, data_filename, pipeline)
  File "/app/nlu.py", line 59, in train
    trainer.train(train_data)
  File "/opt/venv/lib64/python3.6/site-packages/rasa/nlu/model.py", line 209, in train
    updates = component.train(working_data, self.config, **context)
  File "/opt/venv/lib64/python3.6/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 806, in train
    model_data = self.preprocess_train_data(training_data)
  File "/opt/venv/lib64/python3.6/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 788, in preprocess_train_data
    label_attribute=label_attribute,
  File "/opt/venv/lib64/python3.6/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 701, in _create_model_data
    model_data.add_data(attribute_data)
  File "/opt/venv/lib64/python3.6/site-packages/rasa/utils/tensorflow/model_data.py", line 488, in add_data
    self.add_features(key, sub_key, features)
  File "/opt/venv/lib64/python3.6/site-packages/rasa/utils/tensorflow/model_data.py", line 535, in add_features
    self.num_examples = self.number_of_examples()
  File "/opt/venv/lib64/python3.6/site-packages/rasa/utils/tensorflow/model_data.py", line 450, in number_of_examples
    f"Number of examples differs for keys '{data.keys()}'. Number of "
ValueError: Number of examples differs for keys 'dict_keys(['entities', 'intent', 'text'])'. Number of examples should be the same for all data.
```

**Command or request that led to error**:
```
train component DIETClassifier
```

**Content of configuration file (pipeline.yml)** (if relevant):
```yml
language: "de"

pipeline:   
- name: "post.all_tokenizers.AllTokenizer"
- name: "rasa.nlu.featurizers.sparse_featurizer.regex_featurizer.RegexFeaturizer"
- name: "rasa.nlu.extractors.crf_entity_extractor.CRFEntityExtractor"
  features: [
    ["low", "upper"], 
    ["bias", "low", "prefix5", "prefix2", "suffix5", "suffix3", "suffix2", "upper", "digit", "pattern"], 
    ["low", "upper"]]
  max_iterations: 80
  L1_c: 1
  L2_c: 1e-3
- name: "rasa.nlu.extractors.entity_synonyms.EntitySynonymMapper"
#- name: "post.stemmers.german.GermanStemmerLight"
#- name: "post.normalizers.token_filters.EntityTokenFilter"
- name: "rasa.nlu.featurizers.sparse_featurizer.count_vectors_featurizer.CountVectorsFeaturizer"
  "lowercase": true
  "analyzer": 'char_wb'
  "strip_accents": "unicode"
  "min_ngram": 3
  "max_ngram": 6
  "OOV_token": "_oov_"
- name: "DIETClassifier"
  ENTITY_RECOGNITION: False
  embed_dim: 300
  epochs: 100
  C2: 0.001
  mu_neg: -0.6
  mu_pos: 0.85
  intent_tokenization_flag: true
  intent_split_symbol: "+"
  token_pattern: None
  random_seed: 42
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by samsucik** [comment]
Hi @sammerpuranpost, first, the error message is misleading -- it refers to the fact that some feature types weren't generated for all input examples (hence, from within DIET it looks as if there were different numbers of examples for different feature types).

Now disregarding the error message wording (which we'll have to improve): I don't quite understand what could be causing the error. I tried to reproduce it but I couldn't get it. Maybe because I don't have access to the same tokenizer as you, maybe it's because my domain and training data is different. Could you, please, confirm that you're getting the same error when using `WhitespaceTokenizer` instead of the current one? Also, could you share an example domain file and some minimalistic NLU training data that leads to that error?

_Note: You may want to update the config parameters for DIET because many of them are invalid -- they were either removed or are called differently today. Have a look especially [here](https://rasa.com/docs/rasa/2.0.x/migration-guide#rasa-17-to-rasa-18) 🙂_

**Comment by sammerpuranpost** [comment]
Hi @samsucik 
I changed it to the WhitespaceTokenizer and it worked, so my guess it is because of my tokenizer. Is there a guide how to implement/adapt the tokenizers to fit to the new Rasa version?

**Comment by samsucik** [comment]
Right, it's great to hear that we know where the issue is! Unfortunately, I don't think we have guides for how to migrate custom-built components. However, without spending too much time trying to identify the exact issue, I guess it should suffice to take all the tokenizing logic from your old tokenizer and move it into the `tokenize` method of a new custom one (as mentioned [here](https://rasa.com/docs/rasa/2.0.x/components#custom-components)). What do you think?

**Comment by sammerpuranpost** [comment]
Yeah that is the way I thought, but it is a bit complicated in our case with our tokenizers :D But will try to see if I can make it work

**Comment by koernerfelicia** [comment]
@sammerpuranpost can you tell us a bit more about the tokenizer? I ask because I'm wondering if we can help users by adding some sort of shape-checking to to the tokenizer base class. 

A common issue that results in weird behaviour is the tokens not being aligned with features and tokens being split inconsistently.

**Comment by dakshvar22** [comment]
Reading from the discussion above, I wouldn't consider this as a bug since the problem seems to be with the custom tokenizer.

**Comment by TyDunn** [comment]
@sammerpuranpost If you don't believe this is a bug with your custom tokenizer, please reopen
