### ISSUE TITLE
`rasa export` with minimum timestamp fails to export events to rasa db

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#8167]
**Rasa version**: 2.3.4

**Rasa X version** (if used & relevant): 0.37.1

**Python version**: 3.7

**Operating system** (windows, osx, ...): MacOS

**Issue**:

When running `rasa export --minimum-timestamp <date>`, the events are not exported to the tracker db or the  rasa db. 

With the same endpoints & environment, running `rasa export --conversation-ids <some id>`, the conversations are exported successfully and appear on the conversation screen in the target Rasa X deployment.

In both cases success is reported in the logs with `Done! Successfully published <> events 🎉`

**Error (including full traceback)**:
This error was not consistent in appearing but it showed up more than once when re-attempting export with minimum timestamp:

```
Fetching events for 68045 conversation IDs:
Selected 1380978 events for publishing. Ready to go 🚀
Done! Successfully published 1380978 events 🎉
Traceback (most recent call last):
  File "/home/melinda/.cache/pypoetry/virtualenvs/rasa-beEgzbjH-py3.8/bin/rasa", line 5, in <module>
    main()
  File "/home/melinda/rasa/rasa/__main__.py", line 116, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/melinda/rasa/rasa/cli/export.py", line 175, in export_trackers
    rasa.utils.common.run_in_loop(_export_trackers(args))
  File "/home/melinda/rasa/rasa/utils/common.py", line 312, in run_in_loop
    loop.run_until_complete(asyncio.gather(*pending))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
asyncio.exceptions.CancelledError
```

**Command or request that led to error**:
```
rasa export --minimum-timestamp 1568851200.00000
```

**Content of endpoints file (endpoints.yml)** (if relevant):
```yml
tracker_store: # sara-docker db
  type: sql
  dialect: postgresql
  url: xxx:5432
  username: xxx
  password: xxx
  db: tracker

event_broker: #sara-k8s event broker 
  type: "pika"
  url: "xxx"
  port: 5672
  username: xxx
  password: xxx
  queues:
    - "rasa_production_events"  
```

**Comment by wochinge** [comment]
@RasaHQ/enable-squad Might be a good one for the refinement on Friday as this is key for customers migrating from pure Rasa Open Source deployments to Rasa X

**Comment by joejuzl** [comment]
Hi @melindaloubser1 I'm having a bit of trouble replicating this bug. 

What do you mean exactly when you say:

> the events are exported to the tracker db, but not to the rasa db.

Are the events successfully pushed onto rabbitmq?

**Comment by melindaloubser1** [comment]
What I mean is that after running the export, I go check in the postgres db, and I see that the `events` table in the `tracker` db has the expected large volume of events in it, however the `conversations` table (and all other tables) in the `rasa` db do  not have any conversations/messages/logs in them. The events must have been pushed to rabbitmq successfully to make it to the tracker database, but I'm not sure what the process is for them to get into the conversations table as well.

**Comment by melindaloubser1** [comment]
Does it work as expected for you?

**Comment by joejuzl** [comment]
So I thought that the `tracker store` `db` is where events are saved straight away when you communicate with Rasa and is independent of the `event broker` or `Rasa X`.
And that `rasa export` takes events from the `tracker db` and puts them on the `event broker`, where they are then consumed by `Rasa X` and put in the `rasa db`.

When I directly hit the Rasa api (brought up by `rasa run --enable-api`) I see the events immediately in the `tracker store`. 
Then when I do `rasa export --minimum-timestamp ...` I see the events get pushed on to the `event broker`. 
And then if I start Rasa X I see them enter the `conversation_events` table in `rasa.db` and they are visible in the webpage.

This would lead me to believe that problem is that the events are not being saved to the tracker store, before the export command is even run.

However my setup is not 100% realistic, and I don't have much experience with real deployed setups etc.

Does what I'm saying make sense? Or is there also a way to use the `export` command to export to a `tracker db`? And if so where are the events coming from?

**Comment by melindaloubser1** [comment]
No I think you're right and I misunderstood something; I actually just found a completely separate bug that would explain my very many events perfectly without any export happening.

**Comment by melindaloubser1** [comment]
If you want the same set up I was working with, you can use Sara's docker & k8s deployments.

**Comment by melindaloubser1** [comment]
We can close in favour of #8277
