### ISSUE TITLE
Investigate feasibility of sending metadata about tokens / pipelines with messages

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#8533]
**Background**

Practice CDD and research met to discuss Tokenisation in Rasa OSS and Rasa X. There notes are [here](https://www.notion.so/rasa/Tokenisation-in-Rasa-OSS-and-Rasa-X-009649ac5c284cd8ad3301d1177e8363?d=ddf25c6f-83d4-4c95-a755-1232bcadad2c#94ee03d3232949f4bfbc18a71c796753).

They decided on a best course of action. However, it would require changes to Rasa Open Source.

**Defintion of Done**
- [x] Determine if it is feasible to add metadata about tokens / pipelines to messages (i.e. we would slightly more than double the amount of message text data that we send across the broker for each event)

**Comment by chdorner** [comment]
Maybe I can expand on the idea that we've ended up with in [Tokenisation in Rasa OSS and Rasa X](https://www.notion.so/rasa/Tokenisation-in-Rasa-OSS-and-Rasa-X-009649ac5c284cd8ad3301d1177e8363).

Since Rasa Open Source already processes messages and tokenises them, we could always defer to Rasa Open Source for this, and with that always stay in sync with future or custom tokenisers. So the goal would be for Rasa X to stop caring about "tokenisation" and only care about "tokens", however this would mean that Rasa Open Source along with the message of the event sends the tokens, which Rasa X/Enterprise can store alongside the event and then use for hinting the user and enforcing the creating of "correct entities".

There is one edge case that we have talked about but don't have a good solution for yet, which is that when the tokenisation configuration in the pipeline changes, this would render already processed and stored tokens wrong and would then allow users to again create invalid entity definitions. Any ideas and suggestions for this would be highly appreciated.

**Comment by edmacovaz** [comment]
@chdorner I think @dakshvar22 mentioned that we could (or perhaps even do) store a kind of ID of the pipeline for each message, so we could match that to Rasa open source to find things that were out of date. Then if we need to update them we need a mechanism for Rasa X to "request reprocessing" of messages.

**Comment by chdorner** [comment]
> Then if we need to update them we need a mechanism for Rasa X to "request reprocessing" of messages.

This is the part that @TyDunn was pointing at with the comment [here](https://www.notion.so/rasa/Tokenisation-in-Rasa-OSS-and-Rasa-X-009649ac5c284cd8ad3301d1177e8363#94ee03d3232949f4bfbc18a71c796753). There is an effort happening right now to more cleanly separate Open Source and Enterprise (see [here](https://www.notion.so/rasa/Rasa-Enterprise-High-Level-Architecture-4febe548458c4f5787f0d4b8379f3da2)).
So we'll need to make sure that our solution of "pre-processing" a whole bunch of messages for tokenisation fits into this larger effort of creating a better separation.

**Comment by joejuzl** [comment]
See this [document](https://www.notion.so/rasa/Sending-tokens-with-events-to-Rasa-X-05fe8895e4aa416e8ca8e3e1f339bc91) for a quick analysis of sending tokens with events to Rasa X.

**Comment by joejuzl** [comment]
closing in favour of #8924
