### ISSUE TITLE
Investigate higher number of sentry bugs

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#8574]
We are hitting the limit of 50k errors/month. 
We should see why this number is higher. 
Is it because of:
- More users?
- User errors that should be ignored?
- More bugs?
Should we upgrade to the next sentry plan?

## Definition of done:
- Find the cause(es) for more bugs
- Determine if we should upgrade to next sentry plan
- Open followup issues if necessary

**Comment by m-vdb** [comment]
Received this Sentry report in my inbox on Monday: 
<img width="582" alt="Screenshot 2021-05-12 at 08 34 22" src="https://user-images.githubusercontent.com/1931615/117973919-3dffb300-b32d-11eb-939b-43cb86940f5e.png">

**Comment by wochinge** [comment]
## Investigation Results

- We had 280 000 error events in the last 30 days
- [Tom already bumped the event limit to 500 000](https://rasa-hq.slack.com/archives/C01HHMR4X8S/p1621278769243300?thread_ts=1619165789.028100&cid=C01HHMR4X8S). This costs 77 $ per month more than 50k
- **[There has been no increase in users](https://analytics.amplitude.com/rasa/chart/o8wcvmi/edit/yz7ys0a)**
- There has been an increase in daily (resolved + unresolved) events on April 29. We're on a high level ever since. We went from ~500 events to ~1500 per day.
    - [The issue causing most events is already handled](https://sentry.io/organizations/rasahq/issues/2020529812/?end=2021-05-19T23%3A59%3A59&project=2801673&query=&sort=freq&start=2021-04-20T00%3A00%3A00&utc=true) (~120k)
    - A few users are causing most of the bugs
        - Unfortunately there is no client side throttling . We can change the [sampling rate](https://docs.sentry.io/platforms/python/configuration/sampling/) but I'd rather pay more than lose visibility
<img width="1677" alt="Screenshot 2021-05-19 at 12 04 59" src="https://user-images.githubusercontent.com/7667273/118804790-68a9b880-b8a5-11eb-9887-1eedaa4a319b.png">


- [By ignoring `OSErrors`](https://github.com/RasaHQ/rasa/pull/8687) and [fixing Pika errors](https://github.com/RasaHQ/rasa/pull/8712) we already made huge step in the right direction

## Next steps

- [ ] Tackle unresolved issue which cause a lot of events
    - 18 000: Telegram: [https://sentry.io/organizations/rasahq/issues/2228387098/?end=2021-04-29T23%3A59%3A59&project=2801673&query=is%3Aunresolved&sort=freq&start=2021-04-29T00%3A00%3A00&utc=true](https://sentry.io/organizations/rasahq/issues/2228387098/?end=2021-04-29T23%3A59%3A59&project=2801673&query=is%3Aunresolved&sort=freq&start=2021-04-29T00%3A00%3A00&utc=true) (~ 700 per day)
    - 24 000, redis: [https://sentry.io/organizations/rasahq/issues/2394425410/?project=2801673&query=&sort=freq&statsPeriod=30d](https://sentry.io/organizations/rasahq/issues/2394425410/?project=2801673&query=&sort=freq&statsPeriod=30d)
    - 12 0000, tracker-store:[https://sentry.io/organizations/rasahq/issues/2260221914/?project=2801673&query=&sort=freq&statsPeriod=30d](https://sentry.io/organizations/rasahq/issues/2260221914/?project=2801673&query=&sort=freq&statsPeriod=30d)
- [ ] Ignored and discard the `ValueError` for environment variables[ which caused ~120k events](https://sentry.io/organizations/rasahq/issues/2020529812/?end=2021-05-19T23%3A59%3A59&project=2801673&query=&sort=freq&start=2021-04-20T00%3A00%3A00&utc=true). **This means that this issue will no longer count towards our quota** (see 4.1 [here](https://docs.sentry.io/product/accounts/quotas/#what-counts-toward-my-quota-an-overview)). This operation is revertible in case we think we made the wrong decision at same point.
- [ ] Do the same for the `OSErrors`
- [ ] I suggest setting the quota back to 200 000. If we discard the ValueError and the OSErrors this accounts for roughly 162 000 errors which leaves us with ~120 000 errors. 200 000 errors should hence still give us plenty of buffer.

**Not suggested next steps**
    - Introduce a separate alert for issues with more than 5000 events per week. I wouldn't do this as these are mostly caused by very few users. Issues which impact more users are covered by existing rules.

**Comment by m-vdb** [comment]
the `ValueError` seems a bit tricky: are we completely sure it's because of a usage error? I remember that there was a recent issue with how Rasa X discovered yaml files, and it tried to read the `.github/` folder of a git repository (in this case the culprit was Rasa X).

**Comment by wochinge** [comment]
I can't discard the `ValueError` 🤦🏻 It's a feature that requires a business plan. Let's keep it for now. Users will eventually move to newer releases which don't send a sentry event for this
![Screenshot 2021-05-20 at 09 56 38](https://user-images.githubusercontent.com/7667273/118941253-d14e6f00-b951-11eb-83e5-e5a42f0bb182.png)
