### ISSUE TITLE
[CI] Problem with the 'Assign default project to issues' workflow

### ISSUE THREAD

**Issue by HotThoughts** [RasaHQ/rasa#8597]
The 'Assign default project to issues' workflow is designed to take effect when opening an issue. It will move issues with label `tool:trivy` and `tool:sentry` to Enable project and issues with label `tool:model-regression-tests` to Research project. 

Two kinds of problems here:
1. Automated created issue does not come with labels. For example, [this issue created by sentry](https://github.com/RasaHQ/rasa/issues/8582) does not come with labels, and hence the workflow run triggered by the issue was [skipped many steps](https://github.com/RasaHQ/rasa/runs/2486735725?check_suite_focus=true). We want to add labels to it when sentry creating the issue.
2. The workflow could not be triggered by the opening of some issues, for example, I couldn't find the workflow run for [this issue](https://github.com/RasaHQ/rasa/issues/8594). One possible guess is that issues opened by github-action could not be identified.

**Comment by HotThoughts** [comment]
@m-vdb ping you since you know the workflow the best. Do you think it is something you could work on or infra squad could take over?

**Comment by m-vdb** [comment]
holy crap, yes I can take a look!

**Comment by m-vdb** [comment]
I think that for 2. your initial assumption was right, I found this in the docs:
> When you use the repository's GITHUB_TOKEN to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run

So I would use the `RASABOT_GITHUB_TOKEN` secret.

But in both cases, labels are added _after_ the issues are created. I think that we can easily modify the workflow to support label addition (listen to the `labeled` event type for `issues`) on 1 condition: that if an issue is already in a project, it's not moved around. Otherwise it could get messy. This behaviour is already implemented in the GH action for different columns in the same project, but we need to implement this for any project in our org. It shouldn't be too hard to implement, I'm a bit concerned about the time it would take to run, but it's easily verifiable.
