### ISSUE TITLE
Warn user if they have not defined a form but used `active_loop: form` in training data

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#8760]
**Description of Problem**:
This issue is one of two* created from this user issue [here.](https://github.com/RasaHQ/rasa/issues/8729)

It seems if `active_loop: some_form` is specified in a story but `some_form` is not specified in the domain, TEDPolicy crashes due to an empty tensor.

(see user issue for more info)

**Overview of the Solution**:
We should warn the user if they have not defined the form but included `active_loop: some_form` in their stories or rules, maybe during `rasa data validate` or before they start training. Note that this is not the same as an action not being defined, which we already check and warn for.

*The [other issue](https://github.com/RasaHQ/rasa/issues/8759) is to handle this more gracefully.

**Definition of Done**:
- [ ] Tests are added
- [ ] Users are warned in `data validate` if they haven't defined a form but have set the active loop to that form in their training data (stories and rules)

**Comment by wochinge** [comment]
@usc-m I think this could be also an interesting one as this forces you to get familiar with tracker events which are basically the essence which drives Rasa Open Source and somewhat even Rasa X

**Comment by usc-m** [comment]
I've come up with a solution for this on the 'active_loop' directive - but I've also noticed the action validation mechanism doesn't actually catch any of these missing form names.

Looking at the minimal example in the user ticket (and also in the forms documentation), a story using a form refers to an action with the same name as the form. Since it has the same name as the form, it doesn't have the 'action_' prefix, and the validator only validates actions which start with that prefix (from what I can see doing some quick tests). Is there a particular reason we have the validator looking specifically for this prefix?

**Comment by wochinge** [comment]
> Since it has the same name as the form, it doesn't have the 'action_' prefix, and the validator only validates actions which start with that prefix (from what I can see doing some quick tests). Is there a particular reason we have the validator looking specifically for this prefix?

Users only need to explicitly add an action for the form if they [customize the form](https://rasa.com/docs/rasa/forms#advanced-usage). So a missing action for the form is not an error.

> is there a particular reason we have the validator looking specifically for this prefix?

Good point! We should actually also validate that responses used in stories are also part of `responses` in the domain 🤔
