### ISSUE TITLE
Build a Tokenizer that works well with Duckling and SpaCy

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#8794]
**Description of Problem**: In the financial demo, SpaCy tokenizer would be needed for SpaCy to extract entities correctly, but using that degrades the performance of Duckling's entity extraction in comparison to the WhitespaceTokenizer. We need a tokenizer that works well for SpaCy _and_ Duckling. See [Slack thread](https://rasa-hq.slack.com/archives/C4Q4X95M4/p1622541019001700).

**Overview of the Solution**: Find out what causes the performance drop in Duckling entity extraction when SpaCy tokenizer is used and build a custom tokenizer that fixes this.

**Definition of Done**:

*   [ ] We have a new SpacyAndDucklingTokenizer component that works for both SpaCy and Duckling
*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog

**Comment by koaning** [comment]
Ah yeah, I hit this issue before too with tools like [dateparser](https://github.com/scrapinghub/dateparser). There's a bunch of great parsing tools that assume access to the full text as opposed to tokens. 

Do we really want to have a `SpacyAndDucklingTokenizer` in our stack though? I'm wondering if instead it makes more sense to build a spaCy compatible plugin for duckling.

**Comment by kaustuk** [comment]
Hi @JEM-Mosig , Just curious, How does any tokenizer affect duckling performance? Because a per code here https://github.com/RasaHQ/rasa/blob/690f8b891305e5bc36c22febd6e56da26a66be6e/rasa/nlu/extractors/duckling_entity_extractor.py#L182 we are simply passing the user text and not the tokens to Duckling. 

Correct me if I have missed some things.
