### ISSUE TITLE
Investigate what model information we want to include in events

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#8815]
We need more information to estimate the effort required for [Attach model information to all events Rasa Open Source sends to Rasa X](https://www.notion.so/rasa/Attach-model-information-to-all-events-Rasa-Open-Source-sends-to-Rasa-X-42b2a46a2dbd4a71a448acf4c9b7e520)

**Background**
- [Slack thread](https://rasa-hq.slack.com/archives/C36SS4N8M/p1622486640301200?thread_ts=1622478683.299700&cid=C36SS4N8M)
- [Sending tokens with events to Rasa X](https://www.notion.so/rasa/Sending-tokens-with-events-to-Rasa-X-05fe8895e4aa416e8ca8e3e1f339bc91)
- https://github.com/RasaHQ/rasa/issues/5948

**Definition of done**
- [x] Determine what model information we want to include
- [x] Determine whether this would require breaking changes

**Comment by TyDunn** [comment]
More context: https://github.com/RasaHQ/rasa/issues/8839

**Comment by wochinge** [comment]
@koernerfelicia What do you think we need? Happy to jump on a call for some brainstorming (note that I'll be on vacation form Thursday to Monday (back on Tuesday)). 

Some ideas:
* model name
* unique model fingerprint (needs to include config + used training data + used Rasa Open Source version)
* if available: Git commit hash (might be a bit tricky - especially if people train on a dirty git state)

**Comment by wochinge** [comment]
[And even more](https://www.notion.so/rasa/Distinguish-between-generations-of-data-4ea446dde29a43c0ad7bbd2ea502346f):

**Comment by koernerfelicia** [comment]
@wochinge I think the model name is not informative enough (unless we expect users to be disciplined about renaming models when they are changed+retrained, or create some functionality around this).

git commit may be tricky for the reasons you alluded to, and also won't necessarily correspond to a trained model(?)

I think unique model fingerprint could work. I'm trying to get some input from others working on evaluation in the thread [here](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1623136315014700?thread_ts=1622448053.285600&cid=C8LEHMTAM) to make sure I haven't missed anything.

Important is that for any change that would affect prediction (as far as I can think of: config, domain, training data, rasa version) a unique identifier is produced for the trained model.

**Comment by wochinge** [comment]
Thanks for the feedback! In my opinion we also need a way to go from model to used config / data. Otherwise you'll know model was used but you don't know what's inside this model. From that perspective the git commit would be neat. We could e.g. also print a warning if a model is trained on a dirty git state. 

> and also won't necessarily correspond to a trained model(?)

What do you mean by that? Unless they train on a dirty state we should be good.

how about a short brain storm meeting tomorrow @koernerfelicia ? Are you the one handling this in Research or does it make sense to pull somebody else in (e.g. related to the training data generations)?

**Comment by koernerfelicia** [comment]
>  Unless they train on a dirty state we should be good.
I guess this is my concern. Do we not almost encourage that by allowing users to train a model in rasa x itself?

A brainstorm sounds good (note that tomorrow I can only do the afternoon). I'm only working on evaluation, I'm not sure who else might need to be involved regarding training data generations.. I'll make a post in `product-research`

**Comment by wochinge** [comment]
> Do we not almost encourage that by allowing users to train a model in rasa x itself?

Very true. We can definitely discuss the approach in Rasa X though (better if we don't have to but it's definitely an option)

**Comment by wochinge** [comment]
**Summary from the call:**

* We need a unique model identifier in each event caused by a model to tie model predictions to a model 
  - This doesn't have to be a fingerprint of config/domain/TrainingData. The only use case for this would be if multiple models would be trained with exactly the same specifications which seems like an edge case and possible might indicate weird user behavior
  - **Is this change breaking?** It depends. Every event already supports the `metadata` field and we can just add this additional information there. A very neat location would be [here](https://github.com/RasaHQ/rasa/blob/130a576f97dd16f04d03762d6fa97d79d3ec8c1c/rasa/core/tracker_store.py#L237) which would require changes to the `TrackerStore` interface. One could argue that details about the model should be added by the model itself though and that this hence should happen outside of the `TrackerStore`. Hence, I'd lean towards not breaking.
* Connecting models and predictions is only one part and only has limited benefit. Ideally we can also tie a model to the used training data (the config is already part of the model so we can always do that). There would be two ways
  - using the Git commit hash: Seems the best option but this requires a clean state. Especially with Integrated Version Control in Rasa X we never have a clean state. So this would require changes in the mechanics of Integrated Version Control. If they train through the CI we'd always be good
  - storing the training data with the model: This could be a fallback option in case users don't use Git  (at least for NLU this is already implemented and can be toggled via CLI param)
* we also need a way to detect which training examples have been used by the previous model during fine tuning. This could e.g. be done by including a lookup table with hashes for each data point (e.g. NLU example, trackers). With the graph model this could potentially also be part of the cache 🤔  


**Suggested next steps:**
* Generate a unique model identifier and embed it in the `fingerprint.json` of a model and in each event
* Create a followup issue for adding the current commit hash to a model and discuss how this could be done in Rasa X (also discuss the fallback option which means adding training data to the model). This definitely needs some wider discussions due to the Rasa X implications.
* Wait for the model architecture changes to be implemented to tackle the improved finetuning part

cc @TyDunn @koernerfelicia @dakshvar22

**Comment by koernerfelicia** [comment]
cc: @tttthomasssss

**Comment by wochinge** [comment]
@TyDunn What's needed to wrap this spike up?

**Comment by TyDunn** [comment]
@wochinge I'd think we'd need to:
- [ ] Create a new issue that 1) outlines what model information we want to include in events, 2) includes a definition of done, and 3) added to 3.0 milestone
- [ ] Make sure that issue is linked in the 3.0 action plan item for adding model information to events
- [ ] Close this issue

**Comment by wochinge** [comment]
I think for that we'd need to decide whether we want to the 2nd item as part of Rasa Open Source 3.0 or not, right? What about if I create two separate issues: one for the unique id as part of the model fingerprint and then one for connecting model to used training data. Product can then decide on the priority of the latter?

**Comment by TyDunn** [comment]
Sounds good. What about sending tokens with events to Rasa X?

**Comment by wochinge** [comment]
@TyDunn I think that should be handled in a separate issue which is created out of the spikes over there. The token has other implications (e.g. it only affects `UserUttered` events) and other difficulties (what to do if tokens outdate etc.)

**Comment by TyDunn** [comment]
Okay. In sprint planning, when you were off, we discussed that we thought it would be part of this. @joejuzl can you create an issue for sending tokens with events and then close the investigation issue?

**Comment by wochinge** [comment]
* Add model identifier (tie model predictions to models): https://github.com/RasaHQ/rasa/issues/8914
* Tie models to training data: https://github.com/RasaHQ/rasa/issues/8916

I haven't added the second issue to the action plan as we need alignment with training workflows on Rasa X.
