### ISSUE TITLE
Docs couldn't deploy 5 times in a row

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#8816]
See build details here: https://app.netlify.com/sites/rasahq-docs-rasa-v2/deploys
Latest build: https://app.netlify.com/sites/rasahq-docs-rasa-v2/deploys/60b914bd9defcc00089ffc81

**Stacktrace**:
```bash
7:49:18 PM: ────────────────────────────────────────────────────────────────
7:49:18 PM:   1. Build command from Netlify app                             
7:49:18 PM: ────────────────────────────────────────────────────────────────
7:49:18 PM: ​
7:49:18 PM: $ yarn run build
7:49:18 PM: yarn run v1.22.5
7:49:18 PM: $ docusaurus build --out-dir build/docs/rasa
7:49:20 PM: Creating an optimized production build...
7:49:49 PM: [info] [webpackbar] Compiling Client
7:49:49 PM: [info] [webpackbar] Compiling Server
8:05:20 PM: [success] [webpackbar] Client: Compiled successfully in 15.52m
8:09:07 PM: Killed
8:09:07 PM: error Command failed with exit code 137.
8:09:07 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Local steps to reproduce**:
- `git checkout documentation`
- `cd docs && yarn`
- `yarn run build` (this fails in Netlify)

**Comment by m-vdb** [comment]
@lunelson FYI I created a ticket. Been trying to reproduce locally (cf. repro steps above) and the first thing that strikes me is that it takes ~ 6 minutes on my machine for the client, and 9 minutes for the server. Second thing that strikes me is that it doesn't fail:
<img width="732" alt="Screenshot 2021-06-04 at 15 23 56" src="https://user-images.githubusercontent.com/1931615/120807996-e24dd180-c548-11eb-9d01-038c4a5a33cb.png">


Could it be a case of timeout or OOM issue?

**Comment by lunelson** [comment]
@m-vdb from a bit of searching, it seems that the exit code 137 and the point in the log where it says "Killed" could be an indication that it's running out of memory, yes. 

It looks a lot like we need to try upgrading docusaurus, since it's now in beta and much farther along. Maybe some of these errors will have been solved. I'll try to see how I can fit this in

**Comment by samsucik** [comment]
@m-vdb I'm unable to run the docs locally and am wondering if it might be the same issue as above (I can't log into Netlify to see what the exact error message there is).

In a clean conda env with Python 3.8, when I checkout either `main` or `2.7.x` and run `make install install-docs`, then running `make livedocs` gives me this (note: I get the same error when using your steps listed above):
```shell
cd docs/ && poetry run yarn start
yarn run v1.22.10
$ yarn pre-build && yarn develop
$ yarn copy-md-files && yarn variables && yarn program-outputs && yarn included-sources && yarn autodoc && yarn telemetry
$ node scripts/copy_md_files.js
Copying markdown files
$ node scripts/compile_variables.js
Computing docs variables and writing to ./docs/variables.json
$ node scripts/compile_program_outputs.js
Computing program outputs
$ node scripts/compile_included_sources.js
Computing included sources
$ echo 'Generating autodoc' && pydoc-markdown
Generating autodoc
$ node scripts/compile_telemetry_reference.js --unhandled-rejections=strict
Compiling telemetry reference
$ docusaurus start --port 3000
Starting the development server...
no versions.json file found
Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file ../src/coroutine.cc, line 134.
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [livedocs] Error 1
```

**Comment by lunelson** [comment]
I'm trying to look in to this, but every time I go back to the docs I have new python issues. Currently I can't get past `make install`.

@samsucik the branch that's failing to build is the `documentation` branch: could you try checking that out and building locally? I think the remote build is probably failing due to running out of memory, and this lies either with Docusaurus itself, or (more likely) with Webpack. 

I had wanted to test how the build would perform if we remove some of the past versions, which would require modifying the following locations: removing some lines from `versions.json`, and some sub-folders from each of `versioned_docs` and `versioned_sidebars`, to pare it all down to no more than 5 versions total, for example, and see what that does. 

I fear we may have to enforce a limit ultimately, on the number of past versions that we maintain.

```
.
└── docs/
    ├── versions.json
    ├── versioned_docs/
    │   └── ...
    └── versioned_sidebars/
        └── ...
```

**Comment by samsucik** [comment]
@lunelson I get the error with the `documentation` branch too (that's what I meant when I said "I get the same error when using your steps listed above").

**Comment by lunelson** [comment]
@samsucik OK, just wanted to be sure

@m-vdb I did some troubleshooting of the `poetry install` issues with @alwx on but succeeded only in identifying that there _is_ a problem, probably with `poetry` and possibly related to macOS 11.x. 

For the moment therefore I can only repeat my recommendation to trim the number of versions built down to 5 or 6 max and see if that fixes it.
