### ISSUE TITLE
Flaky performance tests

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#8972]
**List of flakey performance tests**
- https://github.com/RasaHQ/rasa/runs/2895478026, https://github.com/RasaHQ/rasa/runs/2896964448
- https://github.com/RasaHQ/rasa/runs/2895478108, https://github.com/RasaHQ/rasa/runs/2896964566
- https://github.com/RasaHQ/rasa/runs/2893348548, https://github.com/RasaHQ/rasa/runs/2893756613
- https://github.com/RasaHQ/rasa/runs/2873436215, https://github.com/RasaHQ/rasa/runs/2874756174

**Definition of Done**
- [ ] Understand what's going on with these tests
- [ ] Document the issues
- [ ] Address them if effort needed is ~1, otherwise open follow-up issues

**Comment by twerkmeister** [comment]
So there's two problems here and both seem to be related to the IntentTED policy branches.

First, a memory leak test that would time out because a IntentTED is in the default config now and the test had to train two policies instead of one. I commented on the IntentTED PR to have this fixed and it's being addressed. https://github.com/RasaHQ/rasa/pull/8913#issuecomment-872783746

The second one is a failing test that checks imports for tensorflow eager. This one should be deterministic. I am assuming that during the work in progress on the branch this import was added sometimes for debugging purposes. I would ignore this one for now and see if it resurfaces.
