### ISSUE TITLE
Form - user wants to reenter information

### ISSUE THREAD

**Issue by kapilkathuria** [RasaHQ/rasa#9006]
**Description of Problem**:
as  a user
i want to reset the user information entered in the form
so that i can correct the information entered

Why is this feature needed? Please link any relevant
This feature is needed because user entered incorrect information in form and now user wants to correct it.

**Overview of the Solution**:

User should be shown entered information with option to confirm or cancel the data entered. If user selects cancel, all slots in current form can be reset and same form can be launched again.

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Note**:
If provided description is not enough or clear, I can try providing more information.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @koaning will get back to you about it soon! ✨

**Comment by koaning** [comment]
It sounds like this might be solved with a custom action. You can use `SlotSet` events to set slots to `None`. Is there a reason why this might not work for you?

**Comment by kapilkathuria** [comment]
thanks for your revert on this and considering this feature request.

yes, as per my understanding: this can be done with 

1. separate custom action (set slots to None). 
2. along with that we will need to notify user to send specific message again so that required form will be activated again

I thought this feature out of box could be much more neat than above, and other community members might have similar requirement.

happy to see further thoughts on this.

**Comment by koaning** [comment]
The benefit of using a custom action is that you're able to customise the experience 100% to what makes sense for your situation. The downside of making a custom action like this one as a stand-alone feature is that many users will want to make small adjustments to it. Instead of supporting every small adjustment possible, it's much easier for us to just keep maintaining custom actions as-is.

If you need help with implementing such a function, feel free to ask it in a question on our forum over at https://forum.rasa.com.

**Comment by kapilkathuria** [comment]
problem is not implementing custom action. problem is asking user to send specific message again so that required form will be activated again - i don't think it's best thing to do.
