### ISSUE TITLE
Expose more specific training errors to Rasa X

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#9047]
Errors that Rasa Open Source encounters while training are sent to Rasa X as `ClientError`s. 

However, Rasa Open Source does not send any specific information to Rasa X.

All Rasa X gets from Open Source is a generic “something failed while training” error message.

**Comment by TyDunn** [comment]
@wochinge There is an important, urgent customer issue to expose specific training errors in the UI of Rasa X. Any idea of what it would take to enable Rasa Open Source to send errors with more details? Would this fix likely require a minor release?

cc @chdorner @Tawakalt

**Comment by wochinge** [comment]
I think the best approach would be to use different return codes depending on the error type or extend the `ErrorResponse` to add things in a structured way. Both would require a minor release.

> not send any details back that could help us to surface model training errors to the user. 

It's certainly not ideal, but pretty sure you can also extract the relevant information from the `message` field in the error response?

**Comment by chdorner** [comment]
You are totally right @wochinge! We completely missed the `{e}` [here](https://github.com/RasaHQ/rasa/blob/7616dcc966c1e8d2cd6ded66c03bc85b4aa81169/rasa/server.py#L1101) and it wasn't obvious on the Rasa X side since `aiohttp` seems to swallow the response body by default on exceptions! 🤦‍♂️ 

We'll have an error project meeting tomorrow, but I'm pretty sure that having more structured training errors will be deprioritized. This should give us enough information on the errors for an initial MVP.

**Comment by chdorner** [comment]
Sorry for the delay. We're all good for the initial version with the training error information we currently get from Open Source. We might need to pick the topic of more structured training errors up again in the future but that will happen when the time comes. Thanks for your help @wochinge!
