### ISSUE TITLE
Break up rasa.core.featurizers.tracker_featurizers into separate modules.

### ISSUE THREAD

**Issue by kedz** [RasaHQ/rasa#9056]
**Description of Problem**: It was suggested that that `rasa/core/featurizers/tracker_featurizers.py` is now quite large with the addition of `IntentMaxHistoryTrackerFeaturizer` and that this module should be broken into smaller modules ([see this comment](https://github.com/RasaHQ/rasa/pull/8913/files#r661356109)), possibly for each class: `TrackerFeaturizer`, `FullDialogueTrackerFeaturizer`, `MaxHistoryTrackerFeaturizer`, and `IntentMaxHistoryTrackerFeaturizer`.

In doing so one should also split the corresponding tests in `tests/core/featurizers/test_tracker_featurizers.py`. Additionally, `rasa/core/featurizers/tracker_featurizers/__init__.py` should be created which imports all tracker featurizers into the `rasa.core.featurizers.tracker_featurizers` namespace so that [this logic](https://github.com/RasaHQ/rasa/blob/f6125237c4b3d1a7d1489fffad2e4bf521e98e93/rasa/core/policies/ensemble.py#L460) for loading a serialized tracker featurizer is not broken.

**Comment by samsucik** [comment]
I think this one is actually blocked by #8798 because the tracker featuriser tests are a mess right now and it makes no sense to split them into featuriser-specific files before they're in a good shape as such.

Definition of done (once #8798 is done) could be:
1. Broke down `tracker_featurizers.py` into separate modules
2. Added `__init__.py` to exposes all featurisers and verified that `get_featurizer_from_dict` works with all
3. Split tests into separate files while ensuring as little code duplication as possible and also ensuring that coverage doesn't decrease for any individual featuriser

**Comment by JEM-Mosig** [comment]
This might become redundant if the [disentangling spike](https://github.com/RasaHQ/rasa/issues/9049) yields a plan that we want to go through with.
