### ISSUE TITLE
`rasa interactive` stuck on `action_default_fallback` if it is triggered at the beginning

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#9080]
**Rasa version**: 2.7.1

**Python version**: 3.6

**Operating system** (windows, osx, ...): macOS

**Issue**: When running `rasa interactive`, if `action_default_fallback` is triggered right after the first user utterance then the `rasa interactive` process is stuck in a loop where `action_default_fallback` is predicted each time. This does not happen when following the same conversation path on `rasa shell` which indicates the bug is with `rasa interactive` only. I am attaching a screengrab of this happening.

[https://user-images.githubusercontent.com/8708249/124949101-e7fa7380-e02e-11eb-9680-e72f421e3b80.mov](https://user-images.githubusercontent.com/8708249/124949101-e7fa7380-e02e-11eb-9680-e72f421e3b80.mov)

**It should be noted that this stuck in loop behaviour is only observed if `action_default_fallback` is triggered right at the beginning and not anywhere in the conversation.**

Based on the chat history visible, my hunch is that when `action_default_fallback` gets accepted the first time, it reverts back the last user utterance and the `action_listen` just before it which is correct but then for some reason it again adds an `action_listen` and tries to query the ensemble for another action. At this point, `TEDPolicy's` prediction confidences are too low and hence again `action_default_fallback` is predicted. This keeps happening in a loop.

The above behaviour can be reproduced on moodbot from `examples/moodbot`.

**Error (including full traceback)**: No error traceback. The problem is described above.

**Command or request that led to error**:

rasa train rasa interactive

**Content of configuration file (config.yml)** (if relevant):

<pre>anguage: en

pipeline:

*   name: "SpacyNLP"
     model: "en_core_web_md"
*   name: "SpacyTokenizer"
*   name: "SpacyFeaturizer"
*   name: "DIETClassifier"
     entity_recognition: False
     epochs: 50

policies:

*   name: TEDPolicy
     max_history: 5
     epochs: 50
*   name: MemoizationPolicy
*   name: RulePolicy</pre>

**Content of domain file (domain.yml)** (if relevant): Domain from `examples/moodbot`.

**Definition of Done:**

*   `rasa interactive` doesn't stuck if `action_default_fallback` is triggered right after the first user utterance
*   add tests to check the scenario above

**Comment by ftarlaci** [comment]
I am experiencing a very similar problem described in the original post. I have the same pipeline as well. 

Rasa Version      :         2.6.2
Minimum Compatible Version: 2.6.0
Rasa SDK Version  :         2.6.0
Rasa X Version    :         0.40.0
Python Version    :         3.7.6
Operating System  :         Darwin-20.4.0-x86_64-i386-64bit


In addition to the details posted above, I experience being stuck in the loop even when there is a call to  `action_default_fallback` in the middle of the conversation due to confidence not being above the threshold (set to 0.3). In many cases, the intent is classified correctly (although below the threshold),  but the response is always the fallback action. 

This happens in the shell, as well as, in rasa x.
