### ISSUE TITLE
Create custom SSL context in Rasa OSS

### ISSUE THREAD

**Issue by mvielkind** [RasaHQ/rasa#9085]
**Description of Problem**:
When an action server is deployed with a custom SSL certificate the necessary CA certificates also need to be available within Rasa OSS.

**Definition of Done**:

**Comment by joejuzl** [comment]
So, status so far:
- I have created a PR that allows a local certificate file to be specified in endpoints.yaml
- I have tried it locally with test certificates:
  - I started the action server using the generated self-verified certificate.
  - When not supplying the cert to rasa I get exactly the same error as JPMC.
  - When adding the path to the same certificate running a custom action then works.
- HOWEVER, This is not exactly the same set-up as JPMC:
  - They use some kind of SSL termination between the k8s pods rather than providing a cert to the action server.
  - I don't know exactly what kind of certificate they are using.
  - @Matthew @Mariana is there a better way to realistically test this?

Also, we are currently in a minor freeze. This means there won't be any minor releases until 3.0 (around October).
This means we will have to release it as a micro, which is not ideal as it's not a bugifx... But as this seems v high prio it's the only option I can think of.

**Comment by m-vdb** [comment]
@joejuzl can this be closed?
