### ISSUE TITLE
Followup to Segment growth investigation: check if AWS Linux events have CI false/true

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#9100]
**Context**:
Looking into the recent linear growth in Segment data, the initial findings were published in this [thread](https://github.com/RasaHQ/rasa/issues/8694#issuecomment-876550454).
The action that was taken was to [update the telemetry CI check with AWS CI environment variables](https://github.com/RasaHQ/rasa/pull/9083) to verify the hypothesis whether the events contributing to the growth are part of a CI pipeline.

**Definition of Done**:
- [ ] check if CI `true` hypothesis was correct
- [ ] update explanation for cause behind Segment data growth

**Comment by m-vdb** [comment]
@ancalita numbers are going down now, but the proportion of `ci=true` events didn't increase significantly, see numbers [here](https://metabase.rasa.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE5MjgsImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwiYnJlYWtvdXQiOltbImZpZWxkIiwxNTUyMyx7InRlbXBvcmFsLXVuaXQiOiJtb250aCJ9XSxbImZpZWxkIiwxNTUxNyxudWxsXV19LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6ImxpbmUiLCJkaXNwbGF5SXNMb2NrZWQiOnRydWUsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsic3RhY2thYmxlLnN0YWNrX3R5cGUiOm51bGx9fQ==).

I'm not sure if the hypothesis is correct or not, because to validate it it would have required users to upgrade to a newer version of Rasa. I'd say we can close this issue for now. We can always reopen later.
