### ISSUE TITLE
Deprecate MITIE tokenizer/featurizer support?

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#9124]
**Context**

*   We want to support one way to solve problems (if possible)

**Information to feed into deprecation decision**

*   <span class="error">[x]</span> Usage stats from telemetry
*   <span class="error">[x]</span> Identification of alternatives for Chinese users
*   <span class="error">[x]</span> What is the maintenance cost of keeping it in place?
*   <span class="error">[x]</span> Could it be moved into nlu-examples?

**Definition of done**

*   [ ] Confirm that we want to Deprecate MITIE tokenizer/featurizer (context [here](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1626174843350600))
*   [ ] Update docs with new recommendation
*   [ ] Add deprecation warning in the 3.0 code
*   [ ] Add deprecation warning in the 3.0 docs

**Comment by alopez** [comment]
assignee: @aeshky 
reviewer: @kedz

**Comment by aeshky** [comment]
@koaning you raised the [question](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1626174843350600) of whether to deprecate the [`MITIE tokenizer`](https://github.com/RasaHQ/rasa/blob/main/rasa/nlu/tokenizers/mitie_tokenizer.py) and the [`MITIE featurizer`](https://github.com/RasaHQ/rasa/blob/main/rasa/nlu/featurizers/dense_featurizer/mitie_featurizer.py). As a result, we created this issue to come to a decision and document the process. 

I sent you an invitation to discuss the following:
1) You ran a metabase query to find out how often `MITIE` is used, and reported 2000+ runs in the last month ([here](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1626176302351800?thread_ts=1626174843.350600&cid=C8LEHMTAM)). Is this for both the tokenizer and featurizer? Any tips on how I can run the query myself, or should I just follow the [Metabase docs](https://www.metabase.com/docs/latest/users-guide/start.html)?
2) Is `MITIE` only used for Chinese? What is our main alternative to it? According to the docs the [`JiebaTokenizer`](https://rasa.com/docs/rasa/next/components#jiebatokenizer) is our main Chinese tokenizer. What do we recommend as a featurizer for Chinese?
3) What is the maintenance cost of keeping  the two `MITIE` components in place?
4) Is it appropriate to move them to `rasa-nlu-examples`?
5) Xiaoquan Kong referred to a BERT-based solution ([here](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1626174932350900?thread_ts=1626174843.350600&cid=C8LEHMTAM)). Is this a custom component that they've implemented, or are they referring to a Rasa component? They also recommended `THULAC`: can I confirm that we don't have a Rasa component for this? 

It would be great to meet and discuss this, and I'll summarise our discussion below. But if you have a quick answer to any of the above feel free to comment. Thanks!

**Comment by aeshky** [comment]
**Summary from my meeting with @koaning**

1. All of the `MITIE` components can potentially be deprecated, especially since we already have alternatives for entity extraction and nlu classification. Aciel to check the usage of the different components on metabase.
2. `MITIE` is mostly used for Chinese and mainly on older versions of Rasa. Aciel to confirm this on metabase.
3. `JiebaTokenizer` is indeed our main Chinese tokenizer. Aciel to compare the usage of `JiebaTokenizer` vs. `MitieTokenizer` on metabase.
4. We will not have usage statistics for customers running `MITIE` inside Docker containers (we already checked this on metabase).
5. Vincent is happy for `MITIE` to move to `nlu-examples` where he would maintain it at his own pace. He also suggested to alternatively move it to a separate git repo.
6. Regarding the maintenance cost: `MITIE` has not been causing us problems: there are only two recent issues both raised internally, including this one.
7. We don't usually recommend `MITIE` to users, which supports deprecation.
8. When Xiaoquan Kong referred to a "BERT-based solution" he was talking about a custom component that he wrote.

**Comment by aeshky** [comment]
### Usage stats from telemetry
Filetered by language: zh (since we have kept MITIE mainly for chinese).

`JiebaTokenizer`: 2000 since Feb 2021
`MitieTokenizer`:  842 since Ocr 2020
This means that the `JiebaTokenizer` is used much more than the `MitieTokenizer`

**Comment by aeshky** [comment]
Based only on usage statistics, I recommend not deprecating `MITIE`. 
However, if we think it doesn't fit our long term strategy of having one solution for each problem (i.e., one pipeline for Chinese) then we need to coordinate with dev-rel to come up with our recommended pipeline for Chinese.

**Comment by koaning** [comment]
@aeshky it's a bit strange that the number 2000 appears *that* often in the stats. Are you sure it's the correct count or is that an upper limit from our telemetry stats?

**Comment by aeshky** [comment]
@koaning I should have clarified: yes it's the upper limit, so we have to rely on the dates.

**Comment by alopez** [comment]
@TyDunn per @aeshky's comment above, it's not clear that we should deprecate this, so I'm closing it for now and unassigning Aciel.

**Comment by m-vdb** [comment]
Closing as we have another ticket representing this work
