### ISSUE TITLE
Investigate retracing warning on CI

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#9534]
### What problem are you trying to solve?

We've been observing retracing warnings on CI. Retracing is expensive, so we should figure out whether this is something we can avoid.

### What's your suggested solution?

We'll need to:

1.  figure out under which conditions we see this warning (possible factors: OS, python version, pytest, CI...). Note that we generally [suppress TF warnings](https://github.com/RasaHQ/rasa/pull/8718), but that this has failed in the past for different configurations, so it may be that the warning is actually more common and we see it only here because of some interplay with failed tests, CI, etc..
2.  figure out if the warnings are on us (it's possible that they may be on Keras side, in which case we should open an issue with them similar to [here](https://github.com/tensorflow/tensorflow/issues/38561)). There have also been reports of erroneous retracing warnings (see linked issues in Keras issue).
3.  if they're on us, figure out whether we can avoid re-tracing (see [here](https://www.tensorflow.org/guide/function#controlling_retracing))

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

*   [ ] figured out the root cause of the retracing warnings
*   [ ] either: can't/won't fix, fix, or create issue with Keras or TF

**Comment by A150852** [comment]
My observation - In multiprocessing setting, invoking predict() causes this warning and when processing large amounts of data it errors out eventually(may be memory leakage). Setting experimental_relax_shape=True for the function being invoked by multiple processors resolves the issue. Also using model(input) instead of model.predict(input) resolves the issue. So key issue seems to be due to retracing even when input shape changes. Issue persists even on using tensors as input instead of python object
