### ISSUE TITLE
`/restart` and other commands don't work when trained with e2e TED

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#9587]
### Rasa Open Source version

Rasa Version : 2.8.6 Minimum Compatible Version: 2.8.0 Rasa SDK Version : 2.8.1 Rasa X Version : None Python Version : 3.8.0 Operating System : macOS-10.16-x86_64-i386-64bit Python Path : /Users/johannes/miniconda3/envs/rasa-master/bin/python

### What happened?

When TED policy is trained with end-to-end features, the `/restart` command is interpreted as text (TED makes a text-based prediction that seems to overrule the hard-coded one) and thus doesn't trigger a restart.

I've seen this also for some situations where I typed a `/<intent_name>` and it was still "interpreted as text" by TED. The `/stop` command always works, though.

### Command / Request

We can see this in the `examples/e2ebot` example. Train with `--augmentation 0` for it to learn something correct at all, and then run `rasa shell`:

Bot loaded. Type a message and press enter (use '/stop' to exit): Your input -> hi hi! Your input -> /restart great! here's what I found ...

**Comment by ka-bu** [comment]
Looks like it could be due to the `RegexInterpreter` passing on the text from the command line as "text" attribute here: https://github.com/RasaHQ/rasa/blob/2.8.x/rasa/shared/nlu/interpreter.py#L151

**Comment by JEM-Mosig** [comment]
Actually, the problem is that those actions are not intended to work without RulePolicy or MappingPolicy/

**Comment by ka-bu** [comment]
Ah ok, yeah, those policies will overrule TED. And I just wondered a bit what TED sees/uses from the message with `/<intent_name>`  later. But since the rule policies win, a `DefinePrevUserUtteredFeaturization` with `use_text_for_featurization=False` should be added by the ensemble which will effectively mean all policies will ignore the funny "/<intent_name>" text. (Correct me if I'm wrong :D).

**Comment by ka-bu** [comment]
Regarding the "/restart" - That text will be turned into {TEXT: "/restart", INTENT: { ... "restart" with confidence 1}} by the RegexInterpreter if it parses this text. Imho this should never reach the RegexInterpreter or should be turned into an Action-> Event -> "applied event" afterwards. If we can still see this as a message, then it looks like the restart was never "applied".

**Comment by ka-bu** [comment]
Some links on that:
- [processor will pass the "/restart" through the RegexInterpreter in it's "parse_message"](https://github.com/RasaHQ/rasa/blob/main/rasa/core/processor.py#L584) - if it ever gets it as input 
- [in `_handle_message_with_tracker` that parsed message becomes an `UserUttered`](https://github.com/RasaHQ/rasa/blob/main/rasa/core/processor.py#L615)
- and that seems to happen on purpose, because we have the [`_should_handle_message` which checks whether the extracted intent is `RESTART`](https://github.com/RasaHQ/rasa/blob/main/rasa/core/processor.py#L636)
- that check is then used in the for loop in  `_predict_and_execute_another_action` [here](https://github.com/RasaHQ/rasa/blob/main/rasa/core/processor.py#L676)
- ..... but the "restart" message is never removed from the tracker / applied the same way it would be applied via the "applied events"
- and it cannot be removed later via the trackers applied events method because that will only remove it if it is a proper Action (not a message with that restart text)
- which also means that the policies will *always* ignore the restart and just see everything before (plus the funny user uttered)

So it looks to me like:
- we need to replace the `UserUttered` with the right Restart event [here](https://github.com/RasaHQ/rasa/blob/main/rasa/core/processor.py#L615)

@JEM-Mosig , does that make sense or am I missing something?

**Comment by wochinge** [comment]
> we need to replace the UserUttered with the right Restart event here

It's fine isn't it? We add the `UserUttered`, `RulePolicy` predicts `action_restart`, we run the action which does the `RestartedEvent` and we end with an empty tracker

**Comment by ka-bu** [comment]
Oh ok, I forgot that eventually rule policy does create the restarted event :D

**Comment by JEM-Mosig** [comment]
Yes, I think as long as we want to stick to the requirement that RulePolicy must be there for default intent handling, we're fine. I'll close the issue.

**Comment by JEM-Mosig** [comment]
> It's fine isn't it? We add the UserUttered, RulePolicy predicts action_restart, we run the action which does the RestartedEvent and we end with an empty tracker

Actually, this isn't the whole story! Because even though RulePolicy predicts `action_restart`, it is _overruled by text-based predictions of TED_!

For example, with e2e bot:
```bash
Your input ->  /restart                                                                                                                                                      
2021-09-14 10:05:22 DEBUG    rasa.core.lock_store  - Issuing ticket for conversation '850c5615aa4441daa609d228d79ba665'.
2021-09-14 10:05:22 DEBUG    rasa.core.lock_store  - Acquiring lock for conversation '850c5615aa4441daa609d228d79ba665'.
2021-09-14 10:05:22 DEBUG    rasa.core.lock_store  - Acquired lock for conversation '850c5615aa4441daa609d228d79ba665'.
2021-09-14 10:05:22 DEBUG    rasa.core.tracker_store  - Recreating tracker for id '850c5615aa4441daa609d228d79ba665'
2021-09-14 10:05:22 DEBUG    rasa.core.processor  - Received user message '/restart' with intent '{'name': 'restart', 'confidence': 1.0}' and entities '[]'
2021-09-14 10:05:22 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 9 events.
2021-09-14 10:05:22 DEBUG    rasa.core.policies.ted_policy  - User intent lead to 'utter_suggest_cuisine'.
2021-09-14 10:05:22 DEBUG    rasa.core.policies.ted_policy  - User text lead to 'utter_search_restaurants'.
2021-09-14 10:05:22 DEBUG    rasa.core.policies.ted_policy  - TED predicted 'utter_search_restaurants' based on user text.
2021-09-14 10:05:22 DEBUG    rasa.core.policies.rule_policy  - Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
[state 2] user intent: greet | previous action name: utter_greet
[state 3] user text: /restart | previous action name: action_listen
2021-09-14 10:05:22 DEBUG    rasa.core.policies.rule_policy  - There is no applicable rule.
2021-09-14 10:05:22 DEBUG    rasa.core.policies.rule_policy  - Predicted default action 'action_restart'.
2021-09-14 10:05:22 DEBUG    rasa.core.policies.ensemble  - Made e2e prediction using user text.
2021-09-14 10:05:22 DEBUG    rasa.core.policies.ensemble  - Added `DefinePrevUserUtteredFeaturization(True)` event.
2021-09-14 10:05:22 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_TEDPolicy.
2021-09-14 10:05:22 DEBUG    rasa.core.processor  - Predicted next action 'utter_search_restaurants' with confidence 0.97.
```

**Comment by ka-bu** [comment]
(🥳 .... at least that means I understood the ensembles correctly 😅 )

More context / description of ensembles for everyone here: https://www.notion.so/rasa/Policy-Ensembles-9ed9379d2ec74188b8ba8c4f6cee3f08

**Comment by ka-bu** [comment]
And btw, I think also if we do **not** use TED in end to end mode, the rules might fail - in that weird case where one uses the `use_nlu_confidence_as_score` flag (which is debatable in itself imho).

**Comment by m-vdb** [comment]
closing as stale
