### ISSUE TITLE
TF2.6 upgrade for 3.0

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#9832]
**Context**

We have [already upgraded](https://rasa-hq.slack.com/archives/C36SS4N8M/p1633694585275700) `Rasa Open Source 2.8.9` to TF2.6

**Definition of done**
- [ ] Rasa Open Source 3.0 running on TF2.6
- [ ] Let Enable know that `Python 3.9` upgrade is unblocked
- [ ] Run the model regression tests.

**Comment by koernerfelicia** [comment]
I started merging [this PR](https://github.com/RasaHQ/rasa/pull/9869) because I (incorrectly) thought I was responsible for it. I got stuck on:
- [ ] failing docs test. I think that the `example_component.py` file might just be gone, in which case we either need a new one to demonstrate the new component architecture, or scrap the link to it in the docs. Note I had to bump pydoc-markdown back down (reverting [this](https://github.com/RasaHQ/rasa/pull/9307/files)) because of the dependency conflict outlined in the comments of the PR
- [ ] tests/test_default_project.py::test_default_project_has_no_warnings there seem to be warnings related to deprecations: not sure if this is because the warnings are new in 2.6 or because the TF log suppression somehow fails now that we are on 2.5. Either way, we should be able to remove [this](https://github.com/RasaHQ/rasa/blob/main/tests/test_default_project.py#L16-L22)
